### ISSUE TITLE
move to map ID instead of full TileJSON

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#103]
For MapBox-hosted maps, we could move to just providing a map ID instead of a full TileJSON URL to instantiate since 90% of it is unchanged between maps. /cc @yhahn

**Comment by yhahn** [comment]
y this is the trend @tmcw is pushing in mapbox.js and i think it's been helpful for devs. Would be a good change for a future release.

**Comment by incanus** [comment]
@yhahn can you look into tweaking the embed text on hosting for this? I'm not sure if we want to get rid of the TileJSON mention entirely or just reference that both it and the map ID can be used by the iOS SDK.
