### ISSUE TITLE
RMUserTrackingBarButtonItem needs initWithCoder

### ISSUE THREAD

**Issue by tracyharton** [mapbox/DEPRECATED-mapbox-ios-sdk#106]
for easy IB button placement

**Comment by incanus** [comment]
This is a great idea. I will look into it.

**Comment by incanus** [comment]
@tracyharton, let me know what you think about this.

**Comment by tracyharton** [comment]
Seems to work great!  thanks!

I did have to add "[RMUserTrackingBarButtonItem class];" somewhere, ie: root, to prevent the linker from removing the otherwise unused class, but I have to do that for RMMapView as well.  Maybe there's a better linker option to set in the MapView project..

In any case, one less thing to set programmatically...

/tracy

**Comment by incanus** [comment]
Yeah, I think you want -ObjC.

**Comment by tracyharton** [comment]
That keeps all classes in, but I was wondering if there's a per-file method as I'd rather not include the kitchen sink...

/tracy
