### ISSUE TITLE
investigate shape bounding box behavior

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#109]
See https://github.com/mapbox/mapbox-ios-sdk/issues/97#issuecomment-8197642 in #97. 
1. What meaning does a single `coordinate` have in the context of a multi-point shape? 
2. Can the bounding box be set automatically so that the developer doesn't have to worry about it?

**Comment by asutula** [comment]
The only way I can get an annotation to show up on the map is to set the annotation's coordinate to some reasonable value (setting only the bounding box doesn't seem to work). I'm just using the first point in my polyline. This works for now, but I wonder how it will affect polyline annotations being drawn on the map... For example, if my polyline runs west to east, my annotation coordinate is the eastern most end of the polyline, and the viewable map area is over the western end of my polyine, but doesn't contain the annotation coordinate... Will the polyline annotation be drawn?

**Comment by incanus** [comment]
Yeah, I will research this in that issue. IIRC the draw is based on the bounding box, so again I'm not sure why a coordinate would be needed, but it apparently is. I will try to tighten this up.

**Comment by tracyharton** [comment]
I've also noticed two oddities/issues:

1) You _must_ set the bounding box in addition to the coordinate if your shape is large, else it will stop displaying once the coordinate is offscreen.

2) The shape is displayed such that the upper left is at the coordinate, ignoring the actual coordinates used to draw the shape.  There's an offset missing in there, but a workaround is to set the coordinate to the nw coordinate of the shape.

**Comment by incanus** [comment]
Assigned to [Tender discussion #245](http://support.mapbox.com/discussions/mapbox-ios-sdk/245-layerforannotation-ios-please-help).

**Comment by incanus** [comment]
In the above commit, I've added some new convenience classes for points, polylines (open), and polygons (closed, optionally with interior cutouts). These annotations create and manage their own layers, effectively `RMMarker` and `RMShape` instances. 

These work around the above problems with shapes by getting all of their points upfront, so that in addition to drawing, they can also update the bounding box properly. The old way doesn't allow for incremental addition to the points drawn to keep updating the bounding box.  

I'm still working on the root problem, but these classes, or subclasses of them, may work well for most uses.

**Comment by incanus** [comment]
Ok, @asutula @tracyharton can you give this a swing now? Regardless of the new convenience classes, I've just put in a fix for `RMShape` to try to update its `annotation`'s `coordinate` and `boundingBox` properly by both tracking points added to the shape as well as attempting update when redrawing or getting assigned an `annotation`.
