### ISSUE TITLE
consider arbitrary "clusters"

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#112]
See http://support.mapbox.com/discussions/mapbox-ios-sdk/184-marker-groups

Might be nice to have arbitrary clusters made from arrays of points that aren't necessarily geographically proximate. This could assist with enabling/disabling/setting other properties.

**Comment by mahadevans87** [comment]
Has there been any development on this?

**Comment by incanus** [comment]
No. Closing this as an edge case / low priority feature. Developers can group their markers in arrays.
