### ISSUE TITLE
gh-pages generation.

### ISSUE THREAD

**Issue by tristen** [mapbox/DEPRECATED-mapbox-ios-sdk#117]
Marking as a @TODO for now. gh-pages branch does not appear to be updating itself with changes. My vague suspicion is that the api page does not validate very well at all: 

http://html5.validator.nu/?doc=http%3A%2F%2Fmapbox.com%2Fmapbox-ios-sdk%2Fapi&submit=Check

The script generating the markup needs a review.

**Comment by incanus** [comment]
Following this in an internal issue.
