### ISSUE TITLE
move resources to bundle

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#119]
Copying/referencing the image resources is still a pain for the source & framework install methods, so we should look into a `MapBox.bundle` approach. Then the dev can reference the bundle to get copied into the app and the code can source images out of the bundle -- one file vs. an ever-growing list.

**Comment by kiryl09** [comment]
source code in develop branch referenced to mapbox.bundle, but it doesn't exist. where I can get it?

**Comment by incanus** [comment]
@kirillkudin: It should be one of two build products by the SDK, along with `libMapBox.a`. Just drag it into your app's resources and it should get copied into your app bundle.
