### ISSUE TITLE
simplify bounding mask

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#12]
See https://github.com/Alpstein/route-me/issues/43#issuecomment-5054546 for the background. We should make this behave more like MapKit without the hassle.

**Comment by incanus** [comment]
As regards "without the hassle", the library should automatically figure out which is smaller, height or width, and adjust the `boundingMask` accordingly, including after `setFrame:` changes.

**Comment by russellquinn** [comment]
Yeah, this'd be great.
