### ISSUE TITLE
RMMapLayer should zoom with map

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#126]
Assigned to [MapBox iOS SDK #235](http://support.mapbox.com/discussions/mapbox-ios-sdk/235-should-an-rmmaplayer-be-scaled-when-the-map-zooms). As reported in Tender:

<blockquote><p>Hi,</p>
<p>On <a href="http://mapbox.com/mapbox-ios-sdk/#markers__shapes__and_subclasses">
this page</a> it says:</p>
<p><em>In addition, any RMMapLayer, as a CALayer subclass, can have
its contents property set to a CGImage and the layer will be panned
and zoomed with the map automatically. You may wish to use the map
viewís delegate callbacks to respond to map zooms, however,
in order to redraw the image according to zoom level in order to
preserve the best visual appearance.</em></p>
<p>When I tried this the image moves when I pan, but the size of
the image doesn't change when I zoom. Is that expected?</p>
<p>This is the code I'm using to add the annotation:</p>
<pre><code>RMAnnotation* annotation = 
    [[RMAnnotation alloc] 
        initWithMapView: mapView 
        coordinate: CLLocationCoordinate2DMake(-34.91907, 138.60407) 
        andTitle: @""];
[mapView addAnnotation: annotation];</code>
</pre>
<p>And then the following to create the RMMapLayer:</p>
<pre><code>- (RMMapLayer*)mapView: (RMMapView *)mapView layerForAnnotation: (RMAnnotation *)annotation
{
    UIImage* treeImage = [UIImage imageNamed: @"tree.png"];
        
    RMMapLayer* mapLayer = [[RMMapLayer alloc] init];
    mapLayer.anchorPoint = CGPointZero;
    mapLayer.bounds = CGRectMake(0, 0, treeImage.size.width, treeImage.size.height);
    mapLayer.position = CGPointZero;
    mapLayer.contents = (id)treeImage.CGImage;
    
    return mapLayer;
}</code>
</pre>
<p>I also tried changing <code>mapLayer.bounds</code> in
<code>afterMapZoom</code> to adjust the size of the image by the
current zoom level, but the image only resizes when I stop zooming,
not while I am zooming. Changing the scale from
<code>mapViewRegionDidChange</code> seems better, as the image
resizes while I am zooming not just at the end. However the size of
the image lags behind the zooming of the map, instead of being
perfectly synchronized with it.</p>
<p>Is there a way to get perfect synchronization of a layer with
the map?</p>
<p>Thanks,<br>
Saxon</p></blockquote>

**Comment by incanus** [comment]
@tracyharton is working on a version of this over in https://github.com/Alpstein/route-me/pull/116

**Comment by BLamy** [comment]
Is there any progress on this? 

This is the only thing keeping me off mapbox. :(

It looks like what Tracy was doing is dead in the water now.

**Comment by incanus** [comment]
I will try to get to this sometime soon, but it's not at the top of the list. It's going to be somewhat complex because it will probably need to provide for the ability for the delegate to provide varying imagery based on the scale so that things are crisp at all zooms and the overhead is reduced, rather than, say, continually working with a giant version scaled down when zoomed out.

**Comment by BLamy** [comment]
Thank you. Much appreciated.

**Comment by incanus** [comment]
Initial tests in `-[RMMapView correctPositionOfAllAnnotationsIncludingInvisibles:animated:]` with the following are yielding good results: 

```
if ([annotation.layer isMemberOfClass:[RMMapLayer class]])
    annotation.layer.transform = CATransform3DMakeScale(_mapScrollView.zoomScale, _mapScrollView.zoomScale, 1.0);
```

**Comment by incanus** [comment]
Related solution: #361

**Comment by incanus** [comment]
Closing in favor of #361.
