### ISSUE TITLE
performBatchOperations and setNeedsDisplay

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#130]
I am adding locations to a RMShape using performBatchOperations.

At the end of the block I would like to redraw the shape. I have tried...

```
[path performBatchOperations:^(RMShape *aPath){
  …
  dispatch_async(dispatch_get_main_queue(), ^{
     [aPath setNeedsDisplay];
     [aPath.annotation.layer setNeedsDisplay];
     [aPath.annotation.mapView setNeedsDisplay];
     [aPath.annotation.mapView.superview setNeedsDisplay];
  });
}];
```

But it does not work. As soon as I move the map it redraws the path. Anyone got any ideas?

**Comment by incanus** [comment]
Hmm, I would think at least one of these would work. I'll look into it.

**Comment by incanus** [comment]
I'm not seeing this behavior. I add a rectangular shape and then, two seconds later, add a new line segment to the shape. Either directly or with the block, I immediately see the shape update.

**Comment by incanus** [comment]
Could you paste some or all of your drawing update code? Are you sure you are using something like `addLineToCoordinate:` and not `moveToCoordinate:` (which does not draw)?

**Comment by incanus** [comment]
See https://github.com/mapbox/mapbox-ios-example/tree/130-batch-drawing for what I'm doing.

**Comment by onato** [comment]
I have gotten to the route of this problem. The path does not get drawn straight away if `[path addLineToCoordinate` is called on a background thread. 

Changing this to the following fixes this problem but causes another...

```
[path performBatchOperations:^(RMShape *aPath) {
  for (id location in locations) {
    dispatch_async(dispatch_get_main_queue(), ^{
        [aPath addLineToCoordinate:[location coordinate]];
    });
  }
}];
```

This causes the addLineToCoordinate to be called after `ignorePathUpdates` has been set back to `NO`, because adding the blocks to the main queue is completed before they are actually executed.

I can solve this by adding a setter for `RMShape.ignorePathUpdates` and doing the following...

```
[path setIgnorePathUpdates:YES];
for (id location in locations) {
  dispatch_async(dispatch_get_main_queue(), ^{
      [path addLineToCoordinate:[location coordinate]];
  });
}
dispatch_async(dispatch_get_main_queue(), ^{
  [path setIgnorePathUpdates:NO];
});
```

Can you please add the following to RMShape.m?

```
- (void)setIgnorePathUpdates:(BOOL)value
{
    ignorePathUpdates = value;
}
```

**Comment by incanus** [comment]
It appears to me that this is avoided then by not calling draw methods on `RMShape` from non-UI threads. I'd expect this to be the assumption for draw code in general per Cocoa guidelines.
