### ISSUE TITLE
UIView on RMMapview

### ISSUE THREAD

**Issue by jokeruzzo** [mapbox/DEPRECATED-mapbox-ios-sdk#132]
Hello.

I need to insert a UIView on RMMapview like an RMAnnotation.
there is a way for do this ?

thank's.

**Comment by incanus** [comment]
The basic way would be to return the `UIView`'s layer as an `RMAnnotation`'s layer. All annotations need to have a layer to be displayed -- the `RMAnnotation` is the data model.

**Comment by jokeruzzo** [comment]
thank's icanus.
