### ISSUE TITLE
Allow custom userLocation management

### ISSUE THREAD

**Issue by andreacremaschi** [mapbox/DEPRECATED-mapbox-ios-sdk#136]
Hi,

for the app I am working on I need to handle locationManager in such a way that keeps battery usage very low (i.e. checking user location every 10 minutes or so). I thought to subclass RMMapView, but I noticed that _locationManager is always used as an ivar and not as a property, so subclassing of that part of code require more work than I would wish to do (I should rewrite all the userLocation code and can't reuse your implementation of marker user position, map bearing etc.). Using locationManager as a property would let me override the accessor and take control of it. It could be useful also for other apps, i.e. videogames or app that playback the user's movements on a route.

What is your opinion about this? Let me know if you'd be interested in a pull request.

**Comment by incanus** [comment]
I'm not sure how subclassing `RMMapView` will fare in general. Why not just alter the source of it for your needs? I would think you could accomplish something like this via Core Location modifications to the way the `_locationManager` works now.

**Comment by andreacremaschi** [comment]
Yeah I can directly alter the source of course, I am proposing a pull request because I think that decoupling location management and map drawing could be useful not only for me but for other people with my needs. But I can understand it's not a priority for you. Maybe I'll let my code available on my fork.
