### ISSUE TITLE
Random annotation layer position

### ISSUE THREAD

**Issue by alexiscreuzot** [mapbox/DEPRECATED-mapbox-ios-sdk#137]
I'm trying to display a set of RMMarker on top of an RMShape, but it seems like the layer ordering is broken/behaving weirdly :

![weird behavior](http://i.imgur.com/yT32C.png)
(See how some markers are on top of the RMShape, and some under)

I think my issue can be related to [this one](https://github.com/mapbox/mapbox-ios-sdk/issues/31), but it did not help.
I also tried fiddling with `setZPosition:<#(CGFloat)#>`, but the problem is still occurring.

**Comment by incanus** [comment]
So the SDK is automatically adjusting `RMMarker` ordering via `zPosition` from `1` to `x` where `x` is the number of markers total. I would suggest using negative values for your shapes. We do this with the user location-related annotation layers; however these are very large negative numbers so they should stay out of your way.

**Comment by alexiscreuzot** [comment]
I already tried something like `[annotation.layer setZPosition:-999];`, but it's not working either...
Also when I log zPosition, it shows a zPosition of 0 for every annotations.

**Comment by tracyharton** [comment]
could be the quadTree code which overwrites zPosition

**Comment by incanus** [comment]
So @kirualex the `zPosition` isn't sticking then? I wonder, are you recreating your layers frequently, or continuing to use the same ones? The `zPosition` should not get reset to zero by anything.

**Comment by dive** [comment]
Can confirm problem with `zPosition`. I'm trying to show layer with `RMMarker` and `RMCircle` with `RMCircle` `zPosition` set to `-MAXFLOAT` (try with other values, no chance), but `RMCircle` randomly showing on top of `RMMarker`. iOS SDK 6.0.

**Comment by dive** [comment]
as I can see, at `RMMapView.m` line 2530 your wrote 

```
for (CGFloat i = 0; i < [sortedAnnotations count]; i++)
        ((RMAnnotation *)[sortedAnnotations objectAtIndex:i]).layer.zPosition = (CGFloat)i;
```

and before this you try to order array with `annotation.position` at line 2506. while ordering this code just ignore previous values of zPosition.

**Comment by dive** [comment]
so, if add some additional logic around zPosition assignment and store zPosition for layers with user defined values this issue gone

```
for (CGFloat i = 0; i < [sortedAnnotations count]; i++) {
        if (((RMAnnotation *)[sortedAnnotations objectAtIndex:i]).layer.zPosition == 0.0f) {
            ((RMAnnotation *)[sortedAnnotations objectAtIndex:i]).layer.zPosition = (CGFloat)i;
        }
    }
```

**Comment by incanus** [comment]
Ah, good catch. That might be a good patch, to manually-set `zPosition`. I'll have a look.

**Comment by incanus** [comment]
How is this behavior now? There is a reordering routine in there now that should be fixing this.

**Comment by alexiscreuzot** [comment]
Well I'm now able to set the zPosition by myself but weirdly enough it's not influencing the display (I still have markers displayed randomly over or under my RMShape.
I'll have a deeper look this week though, as I just had a quick glance after updating the code (I was using my own fork with the tapEnabled property on annotations which I need).

**Comment by incanus** [comment]
@dive how is your implementation looking? Do you still need to apply your own fix?

**Comment by alexiscreuzot** [comment]
Sorry, i'm totally hooked up on another project for now. Someone else
should join my team and have a look at it. I will point him to this thread
for any improvements on this matter !

Alexis

Le 20 nov. 2012 à 20:15, "Justin R. Miller" notifications@github.com a
écrit :

@dive https://github.com/dive how is your implementation looking? Do you
still need to apply your own fix?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mapbox/mapbox-ios-sdk/issues/137#issuecomment-10568502.

**Comment by weitzh** [comment]
In the cocoa pods version 0.5.0 I still have to apply Dive's line, just as info. Good work on the new version !

**Comment by incanus** [comment]
I think if you specify any custom `zPosition`, you will need to take this on yourself. I think this is probably best done with customizations to `RMMapView` directly in this fashion. The SDK is meant to manage this for you in `correctOrderingOfAllAnnotations`.
