### ISSUE TITLE
add removeable logo bug by default to map views

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#14]

**Comment by russellquinn** [comment]
How is this removable?

**Comment by incanus** [comment]
I need to add the switch still. Source right now ;-)

**Comment by incanus** [comment]
Sorry, I should reopen this. `BOOL` setting forthcoming. Unlike the web side of things, this will be simply configurable on iOS, defaulting to on.

**Comment by russellquinn** [comment]
Okay! Thanks.
