### ISSUE TITLE
takeSnapshot Gray Background

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#143]
I would like to zoom to a specific region and take a snapshot. If I zoom and then take the snapshot the background (i.e. map tiles) is gray. 

I assume this is because they have not been downloaded before the snapshot is created. 

How can I make sure the snapshot is created after the tiles have been downloaded?

**Comment by incanus** [comment]
There is a routine in the SDK for snapshots at `-[RMMapView takeSnapshot]`. You are right -- due to the complexities of asynchronous tile loading, this had to be handled in a custom routine.

**Comment by onato** [comment]
I am using takeSnapshot. With the following I get a gray background...

```
[self.mapView zoomWithLatitudeLongitudeBoundsSouthWest:[route getSouthWest]
                                             northEast:[route getNorthEast]
                                              animated:NO];
UIImage *snapShot = [self.mapView takeSnapshot];
```

If I use the following, even if I can see the map, the background of the generated image is still gray.

```
int64_t delayInSeconds = 2.0;
dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
    //UIImage *snapShot = [self.mapView takeSnapshotAndIncludeOverlay:YES];
    UIImage *snapShot = [self.mapView takeSnapshot];
    NSData *imgData = UIImageJPEGRepresentation(snapShot, 1);
    [imgData writeToFile:jpgPath atomically:YES];
});
```

**Comment by incanus** [comment]
Hmm, at first glance, you are using things right and this should work. I will check to make sure nothing broke here.

**Comment by incanus** [comment]
I'm not seeing this problem. I adjusted a demo app to use `dispatch_after()` two seconds post-launch and write to a file and it looks great, but with and without overlay. 

Can you share any code? If you like, we can take this to a `support.mapbox.com` private ticket.

**Comment by onato** [comment]
It only seems to happen when I choose a small enough region. Try the following with the same code...

```
[mapView zoomWithLatitudeLongitudeBoundsSouthWest:CLLocationCoordinate2DMake(37.337616, -122.033951)
                                             northEast:CLLocationCoordinate2DMake(37.337635, -122.033661)
                                              animated:NO];
```

I am not sure what you mean with the support.mapbox.com private ticket?

If you still can't reproduce it I will whip up an example project for you.

**Comment by incanus** [comment]
Ah, that helps. I will try small.

**Comment by incanus** [comment]
Regarding a private ticket, we have a support site at http://support.mapbox.com. You can open tickets there and choose public/private, so it's a nice way to have a private conversation if code needs to be included. But I think you've got a possible bug, so going here first is the right thing to do ;-)

**Comment by incanus** [comment]
Hmm, that small area works for me as well. Can you send along some code? 

![](https://dl.dropbox.com/u/575564/small.png)

**Comment by onato** [comment]
Whilst creating a demo for you I upgraded to the latest code in git. It is now working for me too.
