### ISSUE TITLE
Vector tiles

### ISSUE THREAD

**Issue by conpota** [mapbox/DEPRECATED-mapbox-ios-sdk#147]
I want to use the Vector tiles.

**Comment by incanus** [comment]
We don't support vector tiles at this time. You may want to check out this project: https://github.com/beelsebob/OpenStreetPad

**Comment by PSTDev** [comment]
Any progress (or roadmap at least) on MapBox iOS SDK + Vector tiles?

**Comment by incanus** [comment]
No hard roadmap yet, but we are getting there. We have Mapnik running on iOS, [our backend is all vector data](http://www.mapbox.com/blog/vector-tiles/), and I have been experimenting with vector drawing. Stay tuned.

**Comment by rgal75** [comment]
Dear Justin

I am very interested in the ongoing work of supporting vector tiles within the MapBox iOS SDK.

Is there a way I can follow the progress? E.g. a branch I can take a look at and/or sample code?

Thanks in advance!

**Comment by wenwuwang** [comment]
Hi, rgal75

Do you know any other SDK support vector tiles except MapBox?

**Comment by rgal75** [comment]
Hello

If you need offline maps then I am afraid, I don't. Otherwise, MapKit or
Google Maps API is at your service.

BR,
Richard.

PS.: There is Mapsforge (https://code.google.com/p/mapsforge/) for
Android, which can render vector tiles. Mapsforge-iOS
(https://github.com/medvedNick/Mapsforge_iOS) is a project that contains
a port of its vector tile rendering. However, the MapsForge Android
library itself fails to render waters correctly (or at least I failed to
make it render waters correctly:-( ).

**Comment by hpogosyan** [comment]
@incanus Anything on the roadmap for Vector tile support on iOS?

**Comment by incanus** [comment]
@hpogosyan yes, though it's still pretty fuzzy. We are working on a new renderer. I have been stating the developer preview date at about midyear. 

Another option is to use [Mapnik](http://mapnik.org) directly. As of `2.2.0` it supports iOS natively and I have had some success parsing and rendering vector tiles locally with it. Given that we are working on a new renderer though it hasn't made sense to release any code around that, but I am happy to help out with any efforts of code contribution.

**Comment by mohpor** [comment]
Hi Justin,
as I'm tirelessly trying to incorporate vector tiles in route-me or MapBox, I'm doing some developments using GDAL/OGR myself! I've been able to compile and integrate GDAL/OGR into my iOS app and read some vector data in it, but I need to render the read data! but if we were to have a good renderer on top of OGR, we will virtually have almost any vector or raster data type and that'll be an awesome addition to MapBox iOS SDK.
You've mentioned earlier that you are working on a new renderer, and I'm thinking, if it is based on OpenGL-ES, then incorporating it with OGR would be a piece of cake!
Let me know if you were interested!

**Comment by incanus** [comment]
@mohpor I'd be interested in collaborating, but most of my bandwidth right now is taken up with this new renderer. Yes, it is OpenGL ES. With Mapnik, you have now what we actually use in [TileMill](http://tilemill.org) and our server stack for rendering vector tiles into raster, and as I said, I've done this at pretty decent performance on iOS as well, albeit from local vector tiles in an MBTiles file. I don't think it would take much work to get that working now, and at such time as we're ready to start collaborating publicly on the new renderer, I am planning on providing a migration path from the current version of this SDK to whatever API we might have then, if it differs.

**Comment by mohpor** [comment]
Ah, I see, I already knew that, I meant using OGR to support many formats, not just as a intermediary tool for the renderer!
Anyway, I'm stuck at converting vectors to rasters in GDAL/OGR and it's more a dead end to me.
I need those vector to rasters, like right now. do you think Mapnik on iOS is the right path for the time being? I mean before the new renderer shows its mighty self in public!
I know you are crazy busy, but would love to hear some pointers on that OGR converting stuff if you had the time.

**Comment by incanus** [comment]
@mohpor I'm actually pretty inexperienced when it comes to the specifics of vector tiles and only minimally versed in GDAL/OGR, but my colleague @springmeyer might be able to help. I would say that if you are needing anything inside of the next six months, Mapnik is the way to go. 

I'm going to reopen this ticket, too, since I'm sure more people will want to know what the state of vector on iOS is and they can get the backstory here.

**Comment by mohpor** [comment]
Thanks Justin,
I have followed springmayer's tutorial on Mapnik on iOS but unfortunately it is unfinished.
Thanks again.

**Comment by springmeyer** [comment]
Yeah, I'm on other tasks right now, so I don't have the bandwidth to finish it right now.

**Comment by ericzoo** [comment]
Voting this up.

**Comment by l4u** [comment]
@ericzoo  you might be interested in [mapbox/mapbox-gl-cocoa](http://github.com/mapbox/mapbox-gl-cocoa)

**Comment by incanus** [comment]
Yes, I would recommend checking out Mapbox GL if you want to start playing with vector tiles. We'll be building up the Cocoa APIs to round out the features like annotations, rendering delegate callbacks, and the like in the coming months.

**Comment by ericzoo** [comment]
@l4u and @incanus - Thanks! Intriguing, is this production ready? Does it have an android equivalent?

**Comment by incanus** [comment]
No, this is not production ready. FAQ here: 

https://github.com/mapbox/mapbox-gl-cocoa/blob/master/FAQ.md

Android status here: 

https://github.com/mapbox/mapbox-gl-native/pull/334

**Comment by ericzoo** [comment]
@incanus Great, I will try hard to convince our dev team over at Lifebit to contribute to the iOS and Android lib. Specifically looking into offline vector maps.

**Comment by incanus** [comment]
Vector tile support won't be added directly to this SDK. You can either use Mapbox GL as mentioned above or at some point in the future Mapbox will likely have server-side rasters rendered from vector sources. We will not be integrating Mapnik here for on-device rasterization of vector tiles, though.
