### ISSUE TITLE
create offline map only

### ISSUE THREAD

**Issue by hirpatel** [mapbox/DEPRECATED-mapbox-ios-sdk#149]
hi,

I can't create totally offline based application.

Can it possible with mapbox ? how it can be done?

thanks.

**Comment by incanus** [comment]
Hi @hirpatel. This sort of question belongs more at support.mapbox.com, but I can point you to the proper references for this: 
- http://mapbox.com/mapbox-ios-sdk/#tile_caching__class
- http://mapbox.com/mapbox-ios-sdk/#tile_sources__protocol

**Comment by hirpatel** [comment]
thanks, I have done offline map load using tile map cashing and till mill.

can it be do offline route on it using map box?
I still not found routing online / offline using mapbox?

**Comment by incanus** [comment]
We don't currently have any functionality for map routing, either online or offline.
