### ISSUE TITLE
User location "Halo" doesn't reappear if you toggle location tracking

### ISSUE THREAD

**Issue by marcins** [mapbox/DEPRECATED-mapbox-ios-sdk#150]
I've got a toggle button for tracking user location, which sets/unsets `showsUserLocation`. If I set it to YES, then to NO and then to YES again later the halo doesn't reappear (but the location dot does).

Probably a simple fix but I haven't had a chance to investigate the code yet.

**Comment by marcins** [comment]
The issue is in [setShowUserLocation](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapView.m#L2684) - when it is set to `NO` the annotation for the halo is removed, but `_trackingHaloAnnotation` is not set to `nil`, so when location tracking is turned back on and the `didUpdateToLocation` method is called the `_trackingHaloAnnotation` is not re-created and re-added.

Not sure what the "correct" fix is - should the existing annotation just be put back, or when user location is disabled should the annotation be properly destroyed?

**Comment by incanus** [comment]
Thanks for the investigative work, @marcins. I will look into this. I think I just want to `nil` it out so that it gets recreated, since if `showsUserLocation = NO` I want to free up the associated memory.
