### ISSUE TITLE
consider delegate method for annotation sorting

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#160]
See #137 for backstory. It might be nice/feasible to query the `RMMapViewDelegate` when reordering annotation `zPosition` for custom behavior, with a  fallback to the existing `-[RMMapView correctOrderingOfAllAnnotations]`.

**Comment by noosxe** [comment]
Hi Incanus. Any news on this topic ?

**Comment by incanus** [comment]
No movement on this as of yet.

**Comment by incanus** [comment]
First cut of this (relatively untested) at https://github.com/mapbox/mapbox-ios-sdk/pull/491.
