### ISSUE TITLE
Method URLForTile:(RMTile)tile missing in RMOpenSeaMapSource.m

### ISSUE THREAD

**Issue by gravon** [mapbox/DEPRECATED-mapbox-ios-sdk#163]
Hello,

first of all - many thanks for the great work you're doing.

I've today updated to the last release version. I'm using RMOpenSeaMapSource in my project and I got an issue when running the app:

In RMMapTiledLayerView in the section for async tile retrieval there is the line:
@synchronized ([(RMAbstractWebMapSource *)_tileSource URLForTile:RMTileMake(x, y, zoom)])

Unfortunately, the method URLForTile:(RMTileI)tile  isn't overwritten in RMOpenSeaMapSource.m, thus the method above calls the URLForTile method in RMAbstractWebMapSource, which throws an exception.

I've overwritten that method in RMOpenSeaMapSource.m - now the app works fine.

Best regards,
Herwig

**Comment by incanus** [comment]
Thanks for the tip. Could you submit a patch for this, ideally to the upstream project alpstein/route-me?

**Comment by incanus** [comment]
Closing here to defer to #318.
