### ISSUE TITLE
add knob for user location above/below annotations

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#164]
Assigned to [MapBox iOS SDK #575](http://support.mapbox.com/discussions/mapbox-ios-sdk/575-user-location-blue-circle-below-path). Currently, user location is below all annotations per MapKit. This could be made configurable with a `BOOL`.

**Comment by lilhinx** [comment]
I'd like this too.

**Comment by t2wu** [comment]
Great, thanks. :)

**Comment by incanus** [comment]
We just defer this to https://github.com/mapbox/mapbox-ios-sdk/issues/160 instead of a specific `BOOL`.
