### ISSUE TITLE
Error with iPhone Simulator 5.1

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#165]
I am getting the following error...

```
Detected an attempt to call a symbol in system libraries that is not present on the iPhone:
__isnand called from function -[RMShape addCurveToProjectedPoint:controlPoint1:controlPoint2:withDrawing:] in image MyApp
```

Any idea how I can get around this?

**Comment by incanus** [comment]
There is a problem with this API on iOS 5. A fix is in the `develop` branch and will soon be patched in `release`.

**Comment by incanus** [comment]
This is over in `release` now in the `0.5.1` tag that went out this morning.

**Comment by onato** [comment]
Great!

Are you going to offer a binary version at https://github.com/mapbox/mapbox-ios-sdk/downloads?

**Comment by incanus** [comment]
That link is going to be deprecated along with [GitHub's uploads deprecation](https://github.com/blog/1302-goodbye-uploads), so I've started putting the binaries in a branch here: 

https://github.com/mapbox/mapbox-ios-sdk/tree/packaging/Downloads

There is one there for 0.5.1 now.
