### ISSUE TITLE
setting constraints (and spotted a small typo)

### ISSUE THREAD

**Issue by fredleefarr** [mapbox/DEPRECATED-mapbox-ios-sdk#17]
I've been trying to set boundary constraints using the following code inside the OnlineLayerViewController:

// Iceland constrains example
CLLocationCoordinate2D NEBound;
NEBound.latitude = 66.34;
NEBound.longitude = -23.7;
CLLocationCoordinate2D SWBound;
SWBound.latitude = 63.69;
SWBound.longitude = -14.7;

[mapView setConstraintsSouthWest:SWBound northEeast:NEBound]; // typo: northEeast 

For some reason the maps locks over an area in Austria, and doesn't allow scrolling. Any ideas?

I've noticed that RMMapView.m has been updated more recently in the mapbox-ios-sdk than the route-me version (which uses a different signature for constraints - setConstraintsSW), so I wasn't sure which one was more up-to-date.

**Comment by incanus** [comment]
Hi @fredleefarr. So our fork is based on the [Alpstein fork](https://github.com/Alpstein/route-me) of core Route-Me, which explains the signature difference. I rather like the way Alpstein has done it there. 

As for the bug, I'll check it out. I know there is an [upstream issue](https://github.com/Alpstein/route-me/issues/30) with constraints and I haven't looked into it yet as we typically do full-world maps.

**Comment by fredleefarr** [comment]
Thanks @incanus - makes sense. I'll take a look at the Alpstein fork.
