### ISSUE TITLE
Annotations position translation?

### ISSUE THREAD

**Issue by MattFoley** [mapbox/DEPRECATED-mapbox-ios-sdk#176]
Hi, I'm trying to mimic an instance of Google Maps with a quad tree tile provider I wrote for use with this library. The tiles are viewable correctly and zoom in and out correctly, but my annotations are not positioned correctly. 

My annotation lat/longs are identical to the Google Maps data/instance, and they seem to be in the correct positions relative to each other except they are super close, as if they're zoomed out incredibly far.

I believe this is because the Google Maps instance's lat/long is normalized between 0 and 1. Is this an issue with my projection then? Any ideas how I would go about fixing it? I could provide example code, but I'm not sure where to start.

**Comment by incanus** [comment]
Not sure I follow entirely, but it sounds like your provider's Google tiles don't line up with anyone else's in the SDK/Route-Me. I'd start by making sure you are following the [proper tile numbering conventions](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames).
