### ISSUE TITLE
MBTilesDemo: 'RMMBTilesTileSource.h' file not found

### ISSUE THREAD

**Issue by zachwill** [mapbox/DEPRECATED-mapbox-ios-sdk#18]
When trying to run the `MBTilesDemo` sample project, I come across failures for both of these imports:

```
#import "RMMBTilesTileSource.h"
#import "RMTileStreamSource.h"
```

I can't find either of the header files in the [Map project](https://github.com/mapbox/mapbox-ios-sdk/tree/release/MapView/Map). When running `git blame`, it looks like @Alpstein added these lines two months ago?

Any thoughts?

Thanks.

**Comment by zachwill** [comment]
Just looked and see that both are available in [Route-Me](https://github.com/Alpstein/route-me/tree/release/MapView/Map).

I'll try to rewrite the sample app to use [RMMBTilesSource](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMBTilesSource.h).

**Comment by incanus** [comment]
I haven't patched up that test project yet, but I am keeping this one updated: https://github.com/mapbox/mapbox-ios-example

**Comment by zachwill** [comment]
Nice, thanks for the heads up.

**Comment by incanus** [comment]
Looks like someone else is working on this, too: https://github.com/Alpstein/route-me/pull/51

**Comment by incanus** [comment]
This is fixed in Alpstein and I've merged it down to our `develop` branch, too.

**Comment by zachwill** [comment]
Sweet. Thanks @incanus.

**Comment by layik** [comment]
I am sorry I should be making sense of this but I think I am using develop and yet cannot see the issue gone?
