### ISSUE TITLE
Markers are not displaying on IPHONE

### ISSUE THREAD

**Issue by Dmitri07** [mapbox/DEPRECATED-mapbox-ios-sdk#183]
I created an application for iPhone. It works fine on XCODE IPHONE simulator.
But when I've uploaded my application on real device (IPHONE 4) there is no markers on my map, they are not displaying.
Why? 

I used this code:
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  RMMBTilesSource *offlineSource = [[RMMBTilesSource alloc] initWithTileSetURL:[NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"moscow" ofType:@"mbtiles"]]];
  
  RMMapView *mapView = [[RMMapView alloc] initWithFrame:self.view.bounds andTilesource:offlineSource];
  
  mapView.zoom = 1;
  
  mapView.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;
  
  mapView.adjustTilesForRetinaDisplay = YES;
  mapView.showsUserLocation = YES;
  
  mapView.delegate = self;
  
  TEAppDelegate *delegate=(TEAppDelegate *)[[UIApplication sharedApplication] delegate];
  NSMutableArray *Sights = delegate.Sights;
  
  int i=0;
  
  for(Sight *thisSight in Sights)
  {
      CLLocationCoordinate2D coord;
  
  ```
  coord.latitude = [[thisSight objectForKey:@"lat"] doubleValue];
  coord.longitude = [[thisSight objectForKey:@"lon"] doubleValue];
  
  
  RMAnnotation *myann = [[RMAnnotation alloc] initWithMapView:mapView coordinate:coord andTitle:[thisSight objectForKey:@"name"]];
  
  //myann.title = [thisSight objectForKey:@"name"];
  //myann.anchorPoint = CGPointMake(0.5, 1.0);
  NSIndexPath *path = [NSIndexPath indexPathForRow:i inSection:1];
  
  myann.userInfo = path;
  ++i;
  [mapView addAnnotation:myann];
  ```
  
  }
  [self.view addSubview:mapView];

}

**Comment by incanus** [comment]
Are you implementing the delegate method `-mapView:layerForAnnotation:`? See the docs here: http://mapbox.com/mapbox-ios-sdk/api/#//api/name/mapView:willHideLayerForAnnotation:

**Comment by Dmitri07** [comment]
Yes, I have implemented it.
I believe the problem is that my IPHONE isnt' connected to the internet, and MAC does connected.
So, does the icon from the method initWithMapBoxMarkerImage is downloaded from the internet ?
Could you please provide it, so I can download it.

**Comment by incanus** [comment]
Yes, the MapBox Marker images require an internet connection. If you look here, you can see how the URL that is retrieved is put together: 

https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMarker.m#L137-L141

These icons come from the [Maki project](http://mapbox.com/maki/) and you can find more about building the URLs here: 

http://mapbox.com/developers/api/#standalone_markers

You are free to download any marker images you need ahead of time to use them in our SDK.
