### ISSUE TITLE
add pin drop animation

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#185]
This doesn't have to be limited to `RMPointAnnotation` but could be limited to MapBox Markers since we know what they'll look like.

**Comment by incanus** [comment]
Let's punt on this. Using custom markers even with MapKit loses this animation, anyway.

**Comment by nderkach** [comment]
Any updates on this?

**Comment by incanus** [comment]
No, to clarify: "punt" here means this is out of scope for this particular project and we're not going to implement it. Happy to consider a pull request, though.

**Comment by nderkach** [comment]
Here is a [workaround](http://stackoverflow.com/a/23921147/1602923) using facebook pop library

**Comment by chrisballinger** [comment]
Thank you @nderkach!
