### ISSUE TITLE
Hiding of marker's bubble

### ISSUE THREAD

**Issue by ghost** [mapbox/DEPRECATED-mapbox-ios-sdk#189]
It seems that a marker's callout can't be hidden when this marker is selected from [RMMapView selectAnnotation] - (even if the property canShowCallout is set on 'NO'). I tried to hide it in different ways but nothing worked well. Is this the right behaviour or should it be hidden as i expected ? 
Thanks

(Sorry for my english)

**Comment by incanus** [comment]
You should not be seeing a callout at all if `canShowCallout = NO`. Is it definitely a black, MapKit-like callout or is it an `-[RMMarker.label]`? Also, `-selectAnnotation` is used in our SDK for showing callouts -- that's really it's only purpose currently.

**Comment by ghost** [comment]
The callout is a mapkit-like callout. 
I use selectAnnotation to focus on an annotation (put the annotation over the others) but without any callout. Is there another way to do it ?

**Comment by incanus** [comment]
Ah, hadn't thought of that use before. I will look into adding that capability to `develop` today -- should be easy.

**Comment by incanus** [comment]
Closed & implemented.

**Comment by ghost** [comment]
Thanks a lot.
Here is my last question :
How long does it take to have this feature available in the released version ?

**Comment by incanus** [comment]
@raphaelRaccourci, there is not a set release schedule, but this is working towards 1.0 of the SDK and should be ready very soon. You could also `git cherry-pick` this commit onto `develop` and use the CocoaPods or source install methods to get this now.
