### ISSUE TITLE
allow map rotation

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#19]
This will play into #5 user tracking since compass heading needs this.

**Comment by incanus** [comment]
This should just involve: 
- Abstracting the routines currently in `[RMMapView locationManager:didUpdateHeading:]` that help take care of scroll view & overlay rotation and annotation compensation rotation. 
- Calling those routines from both heading updates as well as a new `UIRotationGestureRecognizer`. 
- Setting user location tracking to `RMUserTrackingModeNone` in response to user-initiated rotations. 
- Possibly some sort of UI control to revert to north-up rotation.

**Comment by jmuchaxo** [comment]
Hi Justin, I wonder about the progress on this feature...
I am working with Mapbox iOS and custom rotation (since I have offline maps)
When using apps offline I guess the UserTrackingMode(s) are not an option , am I right?
by the way, it's nice API, the Mapbox ios.

**Comment by incanus** [comment]
Haven't been working on this of late. It should be addressed in the near future, though.

**Comment by minusplusminus** [comment]
I've done this in my openframeworks library. If you use the lib files and the headers used here: https://github.com/ikillbombs/ofxMapBox

Use :

```
[mapView updateRotation:degrees]
```

**Comment by incanus** [comment]
@ikillbombs, great stuff. I will check this out. I hadn't really hard of openFrameworks before, but I will check out how you did this under the hood. The main concerns I had were around rotating annotations layers and callouts when they were visible.

**Comment by supermoos** [comment]
Any updates on this? Is there a dev release somewhere we can try out? :-)

**Comment by incanus** [comment]
I've only taken some small stabs at this, but I have not yet cleaned it up enough even to push as a branch. Will take a shot at this soon.

**Comment by supermoos** [comment]
Any news on this?

**Comment by incanus** [comment]
No major work on this yet. Stay tuned for iOS 7-based stuff this week that might help here.

**Comment by ManuelRiegler** [comment]
whats the status on that? does the "Support for iOS 7 stuff" in the current develop branch include anything about map rotation?

**Comment by incanus** [comment]
No, there is nothing moving on free (i.e. without compass) rotation just yet.

**Comment by andyzaharia** [comment]
@incanus any updates on the map rotations stuff ? Thanks

**Comment by fotiDim** [comment]
This would be a very nice feature. Google maps iOS SDK has it already and it works with any tile source.

**Comment by fotiDim** [comment]
Any updates on this?

**Comment by incanus** [comment]
This (like other issues tagged with `v`) is going to be addressed by the new Mapbox GL renderer (http://github.com/mapbox/mapbox-gl-cocoa), which does this now. We are shooting for a clear upgrade path between the tools.

**Comment by fotiDim** [comment]
I am using the classic SDK with custom raster tiles right now implementing the RMTileSource protocol. Will I be able to do this with mapbox-gl-cocoa?

**Comment by incanus** [comment]
Once we have the underlying sources API in GL, I will be writing an `RMTileSource` translation layer for easy portability of raster sources.

**Comment by incanus** [comment]
This is not going to happen in this SDK due to the work involved vs. the effect achieved as opposed to it already being supported in Mapbox GL. Additionally, Mapbox GL supports text label auto-upright and this SDK will not as a raster renderer.
