### ISSUE TITLE
Setting a backgroundView causes EXC_BAD_ACCESS on _loadingTileView

### ISSUE THREAD

**Issue by sobri909** [mapbox/DEPRECATED-mapbox-ios-sdk#196]
`scrollViewDidScroll:` at `RMMapView.m:1323` expects `_loadingTileView` to be set. But setting a `backgroundView` sidesteps the creation of `_loadingTileView`.

**Comment by sobri909** [comment]
Okay, looks like this is what's happening:
1. My `RMMapView` is being setup through `initWithCoder:`, thus is given a nil `backgroundView`. That causes the creation of an autoreleased `_loadingTileView`, which is then assigned (and retained) to `_backgroundView`.
2. I then set `backgroundView` via the setter in my `viewDidLoad`. This retains the given view and releases the previous `_backgroundView`, which causes it to be dealloced, leaving `_loadingTileView` pointing into the aether.
3. Any attempt to use `_loadingTileView` now makes bad things happen.

#### The Fix

Option A: ARC
Option B: `_loadingTileView = nil;` in `setBackgroundView:`

**Comment by incanus** [comment]
ARC's coming -- see [here](https://github.com/mapbox/mapbox-ios-sdk/tree/arc). 

I'm going to close here and handle in your pull request #197.

**Comment by sobri909** [comment]
@incanus I'm using the `arc` branch for our app now. What's your preference for changes to `develop` and `arc` branches. If I find/fix bugs in my fork's `arc` branch, should I submit upstream to that branch, or `develop`?

**Comment by incanus** [comment]
Submit to develop, I guess, unless it's ARC-related.
