### ISSUE TITLE
add examples gallery

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#199]
It would be nice to have an examples gallery like the one [for MapBox.js](http://mapbox.com/mapbox.js/examples/). 

I've been working on this in the `gh-pages` branch locally and could use a review in the next day or two. @tristen, you have some spare cycles? 

I plan on including either a static image or an embedded video in place of the HTML map for the iOS examples, and I want to make sure it works right but I'm largely cannabalizing the MapBox.js template for it.

**Comment by incanus** [comment]
Actually working on this over in `gh-pages-draft` instead. 

@yhahn @samanpwbb @tristen Could I get one of you to take a peek and tidy up a bit? I've puzzled through most of the Jekyll/Liquid stuff using MapBox.js as a template to get this far. I've got a couple examples, screenshots, and navigation. 

Still to do: 
- [x] Tighten up appearance
- [x] Sort examples
- [x] Syntax highlighting for Objective-C (ideas?)
- [ ] Sharper screenshots

**Comment by yhahn** [comment]
@incanus y, i will try to take a look at this this weekend.

**Comment by incanus** [comment]
Thanks, @yhahn. Ideal timeline is with the milestone blog post scheduled for Monday.

**Comment by incanus** [comment]
Couple other things: 
- [x] Get search filter to work
- [x] Round out examples list

**Comment by incanus** [comment]
More: 
- [ ] What are the tags good for? Can those be searched? 
- [ ] It would be cool if the old example apps could be in their own left tab and the default landing page for examples

**Comment by incanus** [comment]
Ok, I've got syntax highlighting working via Pygments built into Jekyll. We appear to already have some defaults for that, but that just might be Jekyll's default. I need to override and/or make the colors better for Objective-C.

**Comment by yhahn** [comment]
@incanus is there supposed to be code with the screenshots in the examples gallery? Or if the code is over on github, how do I get to it?

**Comment by incanus** [comment]
Yes, it's under each screenshot, so it's inline in the gh-pages-draft branch. 

## 

Justin R. Miller
justin@mapbox.com
@incanus77

**Comment by yhahn** [comment]
o it looks like i am missing obj-c highlighting in my pygments install. will investigate.

**Comment by yhahn** [comment]
I pushed some adjustments.

It's worth noting that my pygments install does not have the `objective-c` highlighting so those whole blocks of text failed to render (I switched to just `c` to preview locally). If you haven't tested `objective-c` highlighting in a dummy `gh-pages` repo or so that may be a good idea just to confirm that the pygments version GH is running supports it.

**Comment by incanus** [comment]
Good call, will check it out. Could always ship without, then lobby GitHub for it. 

## 

Justin R. Miller
justin@mapbox.com
@incanus77

**Comment by incanus** [comment]
GitHub Pygments includes Objective-C.

**Comment by incanus** [comment]
Any thoughts @yhahn navigation-wise on getting the example apps back in here?

**Comment by yhahn** [comment]
Hrm, not sure if there are any good quick solutions. Something we can look into refactoring for post-launch?

**Comment by incanus** [comment]
Sure, I think we can do that within a week or two. I was thinking either another tab on the top (blech) or somehow integrating it into the example tabs down the left. 

On Mar 4, 2013, at 3:08 PM, Young Hahn notifications@github.com wrote:

> Hrm, not sure if there are any good quick solutions. Something we can look into refactoring for post-launch?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Justin R. Miller
justin@mapbox.com
@incanus77

**Comment by incanus** [comment]
FWIW they are all mentioned in the SDK README so we haven't entirely dead-ended them. 

On Mar 4, 2013, at 3:08 PM, Young Hahn notifications@github.com wrote:

> Hrm, not sure if there are any good quick solutions. Something we can look into refactoring for post-launch?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Justin R. Miller
justin@mapbox.com
@incanus77

**Comment by yhahn** [comment]
ok, yeah in general I think integrating them with the rest of the examples would be great. Maybe we have a way to layout the page to fill that space without a code snippet if it's a full repo type of example.
