### ISSUE TITLE
RMMapViewDelegate - afterMapZoom: byUser: not working

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#202]
Assigned to [MapBox iOS SDK #794](http://support.mapbox.com/discussions/mapbox-ios-sdk/794-rmmapviewdelegate-aftermapzoom-byuser). Before/after move/zoom delegate methods don't seem to be working anymore. Could be ARC-related.

**Comment by incanus** [comment]
Turns out this was not ARC-related but rather about a month-old bug. Fixed.

**Comment by macawm** [comment]
I'm not getting beforeMapZoom or afterMapZoom calls with the double tap gesture. Only the pinch gesture is triggering these methods. It seems the _zoomDelegateQueue is not being emptied in a timely fashion. Any thoughts?

Correction: I do get the callbacks occasionally. I can't determine why it is not consistent.

**Comment by incanus** [comment]
Hmm, I'll reopen and investigate.

**Comment by incanus** [comment]
Not seeing this at all. Are you still?
