### ISSUE TITLE
find way to not block initWithCoder:

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#203]
See #105 later comments for backstory. This is because we default to a MapBox map, which needs to request remote TileJSON to initialize.

**Comment by incanus** [comment]
This can also crash at times. See http://support.mapbox.com/discussions/mapbox-ios-sdk/797-arc-release-and-storyboards

**Comment by ccarse** [comment]
This doesn't seem to fix the issue with crashing in storyboards discussed here: http://support.mapbox.com/discussions/mapbox-ios-sdk/797-arc-release-and-storyboards
Is there a way to use RMMapView in a storyboard?
