### ISSUE TITLE
Adding Style to RMMapLayer

### ISSUE THREAD

**Issue by tetriscode** [mapbox/DEPRECATED-mapbox-ios-sdk#205]
RMPolygonAnnotation *polygonAnnotation;
polygonAnnotation = [[RMPolygonAnnotation alloc] init];
polygonAnnotation.userInfo = poly.pointsAsCLLocationArray; //Add Data
polygonAnnotation.layer = [self mapView:rmMapView layerForAnnotation:polygonAnnotation];

In the layerForAnnotation, I set the layer property like so:

RMShape *shape = [[RMShape alloc] initWithView:mapView];
shape.lineColor = [UIColor orangeColor];
shape.fillColor = [UIColor orangeColor];
shape.lineWidth = 5.0;

for (CLLocation *location in (NSArray *)annotation.userInfo)
    [shape addLineToCoordinate:location.coordinate];
return shape;

I can't set the polygon to orange fill. Actually, I can't set it to anything but a black outline. Not sure why, but when debuggin annotation.layer is not alloc'ed. 

Is there any docs for adding styles since the layerForAnnotation delegate is gone?

Thanks

**Comment by tetriscode** [comment]
I should add, -(void)mapViewRegionDidChange:(RMMapView *)mapView is getting called on pan. But layer for annotation is not. Even though _delegateHasLayerForAnnotation = YES

**Comment by incanus** [comment]
Note the [docs](http://mapbox.com/mapbox-ios-sdk/api/#RMPolygonAnnotation-class) for `RMPolygonAnnotation` and kin. 

> If you wish to customize the appearance, you should instead create an RMAnnotation and configure its layer directly. Providing a layer manually for instances of RMPolygonAnnotation will not have any effect.
