### ISSUE TITLE
Street Names are not visible in ios but are in the online map definition.

### ISSUE THREAD

**Issue by kaytie** [mapbox/DEPRECATED-mapbox-ios-sdk#207]
For example: Feldeggstrasse Dachsen Switzerland.

**Comment by incanus** [comment]
Are you using a retina compatible map? See http://mapbox.com/mapbox-ios-sdk/#retina_support

**Comment by incanus** [comment]
And here's a code sample: http://mapbox.com/mapbox-ios-sdk/examples/retina-support/

**Comment by kaytie** [comment]
Thanks.
