### ISSUE TITLE
clustered annotations rotation not corrected

### ISSUE THREAD

**Issue by macawm** [mapbox/DEPRECATED-mapbox-ios-sdk#215]
When leaving user tracking with heading mode clustered annotation marker layers are not rotated back to their correct position as the non-clustered ones have been.
![bad rotation](https://f.cloud.github.com/assets/3151321/282105/18b5dc66-9188-11e2-845f-f36482e30eac.png)

**Comment by incanus** [comment]
Ok, I'll take a look at this.

**Comment by incanus** [comment]
I'm not seeing this as the case currently.
