### ISSUE TITLE
crash when no network (branch release)

### ISSUE THREAD

**Issue by cga-F4** [mapbox/DEPRECATED-mapbox-ios-sdk#217]
Hi,
I work now with the 1.0.1 release. I init the RMMapView in a .xib file. So it calls the :initWithCoder method. When there is no network on the device (airplane mode for example), this crashes in the + (id)brandedStringWithContentsOfURL:(NSURL _)url encoding:(NSStringEncoding)enc error:(NSError *_)error method.

if ( ! returnData)
    {
        *error = internalError;  <---- EXC_BAD_ACCESS

It is because we call this method with error = nil in the - (id)initWithReferenceURL:(NSURL *)referenceURL enablingDataOnMapView:(RMMapView *)mapView of RMMapBoxSource file.

**Comment by incanus** [comment]
This is fixed in the `develop` branch. I'll be rolling a point release this week -- sorry.

**Comment by Duckbadger** [comment]
@incanus Which commit fixed this issue? Currently getting the issue and I'm on the `develop` branch.

**Comment by incanus** [comment]
This should have fixed it: https://github.com/mapbox/mapbox-ios-sdk/commit/4f31647e1daa5072e878e0a9806a757ae2f62960
