### ISSUE TITLE
set specific user-agent for SDK requests

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#22]

**Comment by incanus** [comment]
Thought here @willwhite -- in general, apps that care about this can and will set their own user-agent app-wise. We should probably still make an SDK-specific default as well as provide an easy hook for the dev to set this, as it hits a couple places in code (tile requests, TileJSON, grids, etc.)

**Comment by willwhite** [comment]
Default sounds good. Not sure about going out of our way to make it configurable. I guess it should be possible, but I don't know what the main use case would be for changing it on a app-by-app basis.

**Comment by incanus** [comment]
Well, here's a good example: our iPad app tries to change this everywhere. It would be great (dev me speaking here) if I could do that with a simple hook rather than having to hack/fork the SDK and do it in a number of places.
