### ISSUE TITLE
MapBox 1.0.1 does not build in project after installing with CocoaPods

### ISSUE THREAD

**Issue by firemuzzy** [mapbox/DEPRECATED-mapbox-ios-sdk#223]
These are the two errors I get

/Users/firemuzzy/Documents/myApp/Pods/MapBox/MapView/Map/RMMapView.m:1746:29: Property 'background' not found on object of type 'SMCalloutView *'

/Users/firemuzzy/Documents/myApp/Pods/MapBox/MapView/Map/RMMapView.m:1746:43: Use of undeclared identifier 'SMCalloutViewBackground'

From looking at the code the issue is in line 1746 is wrong in RMMapView. It looks like CocoPods is pulling in some old code from 1.0.1, how would one update the pod speck file to get newer code?

**Comment by incanus** [comment]
Hmm, if you are installing from CocoaPods, the dependences should get worked out as well, including SMCalloutView. Could you maybe try trashing your `Pods` folder and re-running `pod install`?
