### ISSUE TITLE
The post install hook of MapBox (1.0.2) is not compatible with this version of CocoaPods

### ISSUE THREAD

**Issue by sam899** [mapbox/DEPRECATED-mapbox-ios-sdk#224]
I'm having trouble installing MapBox using the latest version of CocoaPods

error:

```
[!] The post install hook of MapBox (1.0.2) is not compatible with this version of CocoaPods.
No such file or directory - */Users/Sam/Development/UniSApp/Pods/*Users/Sam/Development/UniSApp/Pods/Pods-resources.sh
```

Note the part of the path in bold which is why the file cant be found.
Can anyone confirm is this is a problem with my install or an issue that needs to be resolved by mapbox?

**Comment by incanus** [comment]
@sam899, I will take a look at this. The podspec lints just fine on my end, but perhaps there was an update to CocoaPods that I'm missing. 

What version of CocoaPods are you running? (`pod --version`)

**Comment by sam899** [comment]
Great thanks, I'm running 0.17.1

I had mapbox 1.0.1 installed with the previous version of cocoapods (not sure of the exact version but probably 0.16.4).

I updated cocoapods followed by mapbox which failed.

I've tried uninstalling both mapbox and cocoapods and trying again but still broken

**Comment by incanus** [comment]
Assigned to [Tender discussion #878](http://support.mapbox.com/discussions/mapbox-ios-sdk/878-the-post-install-hook-of-mapbox-102-is-not-compatible-with-this-version-of-cocoapods).

**Comment by incanus** [comment]
Ah, that explains it. I hadn't realized 0.17 went stable release yet and I know the format has changed slightly. In the meantime you can downgrade CocoaPods to 0.16 or wait -- I will try to have this resolved soon.

**Comment by sam899** [comment]
Great, thanks!

**Comment by incanus** [comment]
Resolved this in the specs repo for all versions with the post-install hook.
