### ISSUE TITLE
The file is to big.

### ISSUE THREAD

**Issue by hugocarlmartin** [mapbox/DEPRECATED-mapbox-ios-sdk#226]
The 1.0.2 is to big? Can I find it somewhere else?

**Comment by incanus** [comment]
Sorry about that. We have had some troubles with large files on GitHub. 

In the meantime, you can try this: 

```
git clone git://github.com/mapbox/mapbox-ios-sdk.git
git checkout -b packaging
ls Downloads
```

**Comment by hugocarlmartin** [comment]
We solved it with the source. Thank you!
