### ISSUE TITLE
allow for offline markers

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#229]
Currently we only allow `RMMarker` to fetch markers from online for the MapBox style versions (though you can provide any local image of your own if you desire). We should improve this to have a base pin image, then use locally-cached [Maki](http://mapbox.com/maki) icons plus [blend mode techniques](http://robots.thoughtbot.com/post/46668544473/designing-for-ios-blending-modes) to color them client-side without needing to fetch anything.

**Comment by incanus** [comment]
- `tintColor`

**Comment by incanus** [comment]
Going to close this until such time as someone actually requests it.

**Comment by farfromrefug** [comment]
I am about to implement that feature. But i am wondering about the best approach.
Should i tint a bitmap  or should i draw the marker using path?
The first could allow some mechanism to actually change the default marker without an SDK update (by a network call).
The latter would allow sharp drawing without the need of keeping images for all resolutions. BTW this is a problem when getting the image from the network. Especially on android as there might be a LOT of different versions.
I would vote for the shape solution but i want your opinion

**Comment by incanus** [comment]
I was thinking of doing this via the first approach; tinting a bitmap similar to what's done here with blend mode: https://github.com/incanus/MapBoxHatchDemo/blob/master/Hatch%20Demo/HDViewController.m#L59-L76

**Comment by farfromrefug** [comment]
Ok seems fine but how will you handle density (or retina on ios)?

**Comment by incanus** [comment]
Six grayscale template images (retina/non-retina of each of the three marker sizes) shipped locally and tinted on the fly. As I said, though, I didn't look into this at all and that may not be practical / create the best imagery but it seemed simplest to me.
