### ISSUE TITLE
Crash occurs if to create RMMapBoxSource instance using mapId when offline.

### ISSUE THREAD

**Issue by ilmarion** [mapbox/DEPRECATED-mapbox-ios-sdk#233]
Hello.
I'm using MapBox ver 1.0.2.  I have the following line in viewDidLoad of my UIViewController:

RMMapBoxSource *tileSource = [[RMMapBoxSource alloc] initWithMapID:@"my map id goes here"]

and it crashes here if network is unavailable.  Place and reason are the same as in Issue 217: https://github.com/mapbox/mapbox-ios-sdk/issues/217.

**Comment by breiko83** [comment]
I have the same problem.

**Comment by incanus** [comment]
I will take a look at this. In the meantime, recommended behavior is to do your own reachability test. If offline, reference a local URL to a local JSON file to describe the map. You could save this the first time it's fetched for later use. But this should not crash, so I will address it.

**Comment by breiko83** [comment]
Thanks incanus, I did as you suggested.

```
//RMMapBoxSource *onlineSource = [[RMMapBoxSource alloc] initWithMapID:MAPBOXMAPID];

NSString *fullPath = [[NSBundle mainBundle] pathForResource:@"mapbox" ofType:@"json"];
RMMapBoxSource *onlineSource = [[RMMapBoxSource alloc] initWithTileJSON:[NSString stringWithContentsOfFile:fullPath encoding:NSUTF8StringEncoding error:nil]];
```

To get the JSON file I browsed:
http://a.tiles.mapbox.com/v3/[MAP-ID].json
then I added the file to my project bundle.

This way I don't need to test reachability, I just don't get the tiles loaded if I'm offline and the crash is not happening.
