### ISSUE TITLE
Multi-Coloured Annotation Path Performance

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#235]
I would like to colour code a route that I am displaying as one annotation. For example, the flat bits green, the steep bits red and the steeper bits even more red. I assume that the only way to do this is to break the route into lots of annotations.

I am displaying routes that can contain well over 5000 points. The performance is not very good on a iPhone4 with one annotation. Breaking it up into 5000 annotations produces unusably slow performance.

I am using the layerForAnnotation delegate method to create my layers. 

Any tips on how to do this or how to improve performance in general for large routes would be greatly appreciated.

**Comment by incanus** [comment]
Hmm, adding multiple colors if the 5,000 point path already behaves slowly definitely won't help things…

Have you tried profiling the code to see what exactly is slow? I haven't optimized specifically in this area but there might be some low-hanging fruit. 

As for the colors, you'll probably have to subclass `RMShape` and do the Core Graphics drawing yourself of the shape layer.
