### ISSUE TITLE
tile load completion delegate

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#236]
Assigned to [MapBox iOS SDK #925](http://support.mapbox.com/help/discussions/mapbox-ios-sdk/925-tile-load-complete-delegate-or-sth). As reported in Tender:

<blockquote><p>Hi, I developing map app, so, the question is</p>
<p>How do I know tile is loaded complete in screen.<br>
for example, In screen have 6 tiles, mapview will start request
that 6 tiles and how do i know that 6 tiles are loaded
complete?</p>
<p>Thanks you.</p></blockquote>

**Comment by stoprocent** [comment]
Any update on this? PLS

**Comment by incanus** [comment]
No, there hasn't been any movement on this. The tracking capability is there, as there are `NSNotification` objects fired on tile download start & end, there just needs to be a tracking array to indicate when all tiles started have completed.

**Comment by stoprocent** [comment]
Cool, notification center is enough. I also saw RMStaticMapView and there is completionhandler and it does what I need :fuelpump:

**Comment by incanus** [comment]
Yes! That is designed in a much newer way, whereas I'm still adapting parts of the original RMMapView for stuff like this.

**Comment by roundrobin** [comment]
Hi guys,I need to solve the same problem, for which NSNotification (name of it) are you listening when to observe (Tile Download End)? I couldn't figure that out.

@stoprocent : What completionhandler are you talking about?

**Comment by incanus** [comment]
There are some older notifications in the system from the Alpstein upstream days, but they aren't used consistently. Fully building out this functionality would likely best use `NSNotification` with observers acting on the main thread to notify the delegate when all was said & done.

**Comment by nderkach** [comment]
Any updates on this?
I believe, the tile current loading animation deteriorates UX and there should be a way to skip it, i.e. wait until tiles are fully loaded, and then display the map.

**Comment by incanus** [comment]
One option here is use of `RMStaticMapView`, which has a completion callback, and/or swapping with a real `RMMapView` when that's done.

**Comment by incanus** [comment]
And stay tuned for news soon about new rendering tech that will make things like the original request here a lot more straightforward.

**Comment by nderkach** [comment]
Justin, could you help me out with making the swap mentioned above work smoothly?

Here is what I got so far:

```
self.mapSource = [[RMMapboxSource alloc] initWithMapID:mapId];
self.tileCache = [[RMTileCache alloc] initWithExpiryPeriod:NSIntegerMax];

self.mapView = [[RMStaticMapView alloc] initWithFrame:self.view.bounds mapID:mapId completionHandler:^(UIImage * image) {
    NSLog(@"Load completeted");

    [UIView animateWithDuration:2
                     animations:^() {
                         self.navigationController.view.alpha = 1.0f;

                     }
                     completion:^(BOOL finished) {
                        [self.mapView removeFromSuperview];
                        self.mapView = [[RMMapView alloc] initWithFrame:self.view.bounds andTilesource:self.mapSource];
                        self.mapView.hideAttribution = YES;
                        self.mapView.userTrackingMode = RMUserTrackingModeFollow;
                        self.mapView.showLogoBug = NO;
                        self.mapView.showsUserLocation = NO;
                        self.mapView.zoom = 15.0;
                        self.mapView.tileCache = self.tileCache;
                        [self.mapView setDelegate:self];
                        [self.view addSubview:self.mapView];
    }];
}];
self.mapView.hideAttribution = YES;
self.mapView.userTrackingMode = RMUserTrackingModeFollow;
self.mapView.showLogoBug = NO;
self.mapView.showsUserLocation = NO;
self.mapView.zoom = 15.0;
RMSphericalTrapezium rect = [self.mapView latitudeLongitudeBoundingBox];

[self.tileCache beginBackgroundCacheForTileSource:self.mapView.tileSource
                                                southWest:rect.southWest
                                                northEast:rect.northEast
                                                  minZoom:15.0
                                                  maxZoom:15.0];
self.mapView.tileCache = self.tileCache;
[self.mapView setDelegate:self];
[self.view addSubview:self.mapView];
```

The idea is that I create a static mapview and cache tiles, I wait until the view is loaded and present it with an animation.

Then I substitute it with a dynamic RMMapVIew. The problem is that the new map view doesn't seem to make use of the cache, as the tiles are loaded anew. Also it initiates the view with the wrong zoom.

Is there a way to swap those views, so that user won't notice it?

**Comment by incanus** [comment]
This is a lot of work for little gain when using an uncontrollable `CATiledLayer`-based renderer. This is already better handled by Mapbox GL over in https://github.com/mapbox/mapbox-gl-cocoa/issues/1.
