### ISSUE TITLE
How to get offline Point of Interest (POI) of OpenStreetMap?

### ISSUE THREAD

**Issue by wenwuwang** [mapbox/DEPRECATED-mapbox-ios-sdk#237]
How to get offline Point of Interest (POI) of OpenStreetMap?

**Comment by incanus** [comment]
Could you be more specific? Unless you have OSM data with you offline, you won't be able to get anything.

**Comment by wenwuwang** [comment]
I use TileMill export a "*.osm.pbf" file to MBtiles file for offline use, can i search POI on this offline map? for example, search a road or a bank?

**Comment by incanus** [comment]
There are no API in the SDK for working with `.pbf` files or data. You will need some other parser in combination with our SDK.
