### ISSUE TITLE
RMPolygonAnnotation wrong interiorPolygons rendering

### ISSUE THREAD

**Issue by zulkis** [mapbox/DEPRECATED-mapbox-ios-sdk#239]
Hello. I have found an issue with this.
Line 84 in current Release sources:

``` objc
[aShape closePath];
```

need to be changed to something like this:

``` objc
[aShape addLineToCoordinate:interiorPolygon.coordinate];
```

Because -closePath method will add line to the 1st point of the "parent" polygon, but not to the interior polygon, that is drawing at this moment. So this code will not create closed polygon for the interiorPolygon, and we'll see wrong result.

**Comment by incanus** [comment]
@zulkis thanks for this, makes sense.

**Comment by mgraesser** [comment]
The suggested fix behaves correctly for me. I included a before fix png and after fix png.

![interior poly before fix](https://f.cloud.github.com/assets/3788572/1126657/8dc1c550-1b27-11e3-92f4-6bfa91a1d2c1.png)
![interior poly after fix](https://f.cloud.github.com/assets/3788572/1126659/8dd1e6ce-1b27-11e3-97cd-3d9f04617ff4.png)
