### ISSUE TITLE
consider static library build

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#24]
We could maybe distribute a static library pre-compiled to simplify the [installation steps](http://mapbox.com/mobile/docs/sdk/) a bit for people who don't need/want to build it themselves.

**Comment by AlfonsoUceda** [comment]
I'm agree with this issue, would help to the installation

**Comment by incanus** [comment]
Several guides around for this: 

http://www.cocoanetics.com/2010/04/making-your-own-iphone-frameworks/
http://www.cocoanetics.com/2010/05/making-your-own-iphone-frameworks-in-xcode/
http://dev.byteclub.com/blog/1-iphone-sdk/48-how-to-almost-create-your-own-iphone-os-framework
http://db-in.com/blog/2011/05/creating-universal-framework-to-iphone-ios/

Seems like it still doesn't solve the resources problem (in our case, currently, the user location services images). It would also be nice to just have to `#import <MapBox/MapBox.h>` and be done with it as opposed to always importing `RMWhatever.h` all over.

**Comment by incanus** [comment]
Re-closing.
