### ISSUE TITLE
RMMapView delegate is incorrectly being retained

### ISSUE THREAD

**Issue by farhadn** [mapbox/DEPRECATED-mapbox-ios-sdk#241]
RMMapView delegate is incorrectly being retained which is causing memory issues (retain cycles). 

The header file (RMMapView.h) correctly defines a weak property for the delegate

@property (nonatomic, weak) IBOutlet id <RMMapViewDelegate>delegate;

But the implementation (RMMapView.m) is redefining the variable (which it doesn't need to do in the first place), but leaves out the __weak qualifier. So the delegate is being retained

```
id <RMMapViewDelegate> _delegate;
```

**Comment by jrmatchett** [comment]
i recently ran into this bug also. is the fix just making sure the RMMapViewDelegate property is not redefined in the implementation file?

**Comment by incanus** [comment]
This is no longer happening.
