### ISSUE TITLE
UserLocation : changing DotTrackingHalo

### ISSUE THREAD

**Issue by gaeld** [mapbox/DEPRECATED-mapbox-ios-sdk#243]
Hi, 

I've try to change the user tracking halo, by replacing the picture in the ressources. It works really well for the TrackingDot.png, but it doesn't work at all for the TrackingDotHalo, the halo is still the blue one.

Any idée ? I'm using the packaged framework, and not the original sources. 
Thanks,

**Comment by incanus** [comment]
Hmm, odd. Replacing any of these images should work fine. Are you sure you're not doing something like only replacing the `1x` version but using it on a retina device, which needs the `2x`?
