### ISSUE TITLE
Zoom level beyond 22

### ISSUE THREAD

**Issue by macteo** [mapbox/DEPRECATED-mapbox-ios-sdk#246]
I'm trying to develop an application for indoor navigation using a combination of TileMill and MapBox iOS SDK. 
I've successfully modified TileMill to generate a MBTile database with tiles levels to zoom level 28.

I thought that the worst part was done, but with big surprise the MapBox iOS SDK is not able to render tiles beyond zoom level 22.

What I noticed is that the `RMMapTiledLayerView`'s `drawLayer:inContext:` method is not called at all when the zoom level is more than 22.

I thought that there could be some explanations:
- The [`CATiledLayer`'s `levelsOfDetail`](https://developer.apple.com/library/mac/#documentation/GraphicsImaging/Reference/CATiledLayer_class/Introduction/Introduction.html) is clamped: Apple's documentation

> Defaults to 1. Each level of detail is half the resolution of the previous level. If too many levels are specified for the current size of the layer, then the number of levels is clamped to the maximum value (the bottom most level of detail must contain at least a single pixel in each dimension.)
- There is some limit in the MapBox iOS SDK that i don't find (I've replaced every occurrence of **22**)
- The float value limit for the frame is reached.

Note that the MapView actually zooms at the desired level, but the (automatic?) method on its `RMMapTiledLayerView` is not called so the tiles are not rendered.

Do you know why there's an actual 22 limit for the maps?

Thanks in advance to any suggestion...

**Comment by incanus** [comment]
I'm guessing this is due to floating point precision limits and is related to https://github.com/mapbox/mapbox-ios-sdk/issues/72. Stay tuned as we are doing some work in this area soon.

**Comment by macteo** [comment]
Thanks for the feedback.
I've a deadline for the end of may. Could you tell me if you are working on the floating point issue or something related to indoor maps? I have to make a decision as soon as possible and want to use best available solutions.

**Comment by incanus** [comment]
Hey @macteo, I don't think end of May is a realistic timeline for this from us based on other things being worked on. Sorry :-(

**Comment by macteo** [comment]
Good to know! Thanks.
We have some ideas to achieve a workaround.

**Comment by jcouture** [comment]
Hi @macteo , would you be willing to share the workaround you ended up using?

**Comment by macteo** [comment]
Unfortunately we ended up using a non georeferenced map and perform some coordinate conversions, nothing special...

**Comment by incanus** [comment]
Since this is z22-specific and we don't have any plans of supporting that server-side for now, I'm going to close. However, this will be solved indirectly by a solution to #72.
