### ISSUE TITLE
Need instructions for `Add marker to map`

### ISSUE THREAD

**Issue by rknLA** [mapbox/DEPRECATED-mapbox-ios-sdk#25]
I've had a pretty solid look at `RMMarker.h`, `RMAnnotation.h`, and `RMOverlayView.h` and still cannot figure out how to simply add a marker to a mapview.

I've also been poking around in Xcode with trial and error with no success.

A few lines of code as an example would go a _long_ way here.

**Comment by incanus** [comment]
Following up, but I've been working with @rknLA on IRC about this. But I'll leave this ticket here as this does need better docs.

**Comment by incanus** [comment]
Closing in favor of code example at https://github.com/mapbox/weekend-picks-template-ios but also general doc improvement at #4.
