### ISSUE TITLE
Scaling Map - Difference from 1.01 > 1.02

### ISSUE THREAD

**Issue by morgz** [mapbox/DEPRECATED-mapbox-ios-sdk#250]
Just try this:

```
[UIView animateWithDuration:5 delay:1.0
                        options:nil animations:^{

                           map.height = map.height + 200;

                        } completion:^(BOOL finished) {


                        }];
```

In 1.01 - The map scaled nicely and annotations stayed in place. 
In 1.02 - The map doesn't scale well. It moves the annotations independently of the map.

**Comment by morgz** [comment]
This commit is giving me the undesired behaviour:

https://github.com/mapbox/mapbox-ios-sdk/pull/220

**Comment by incanus** [comment]
Does this work ok for you in 1.0.3?
