### ISSUE TITLE
crash on user tracking change

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#251]
Assigned to [MapBox iOS SDK #1022](http://support.mapbox.com/discussions/mapbox-ios-sdk/1022-user-location). As reported in Tender:

<blockquote><p>When setting showsUserLocation to false, my App is crashing with this error</p>

<p>Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSSetM addObject:]: object cannot be nil</p>

<p>Any ideas?</p></blockquote>

**Comment by spromicky** [comment]
Fix this issue in https://github.com/mapbox/mapbox-ios-sdk/pull/264

**Comment by incanus** [comment]
Deferring to #264.
