### ISSUE TITLE
crash when trying to download offline

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#252]
Assigned to [MapBox iOS SDK #1027](http://support.mapbox.com/discussions/mapbox-ios-sdk/1027-background-tile-download). As reported in Tender:

<blockquote><p>Hello all (and Justin in particular),</p>

<p>I've played with the background tile downloader : it's a great tool to cache all the required tiles for offline access.</p>

<p>My question is about launching my MapView with network connection and making use of the downloaded tiles.</p>

<p>The call :
<br>RMMapBoxSource *tileSource = [[RMMapBoxSource alloc] initWithMapID:mapID];
<br>crashes if no network is available.</p>

<p>So how can I go further when the user want to display a map with cached tiles when no network is available ?</p>

<p>Thanks</p>

<p>Lionel</p></blockquote>

**Comment by davididntt** [comment]
I created a pull request to fix this issue:
https://github.com/mapbox/mapbox-ios-sdk/pull/255

Cheers,

David.

**Comment by incanus** [comment]
Deferring to #255.
