### ISSUE TITLE
map rotation issue

### ISSUE THREAD

**Issue by Macbiont** [mapbox/DEPRECATED-mapbox-ios-sdk#257]
I'm testing a MapBox based App on 30 iOS devices. On two of them the map does not rotate. That's a bit weird actually. There is also a visual compass on the map which works usually. 

I also tested Apple Maps without any problems on those devices. Location-Services are enabled (iOS 6.1.3, iPhone 4S). 

Any ideas?

**Comment by incanus** [comment]
Hmm, do you still see this issue? Does not seem to be code-based when it works on 28 out of 30 devices.
