### ISSUE TITLE
RMPath flickers when scrolling

### ISSUE THREAD

**Issue by rnapier** [mapbox/DEPRECATED-mapbox-ios-sdk#26]
I created a very simple map of the US with the following layers:

10mlakesnorthamerica
10mroads
10madmin1statesprovi
countries

I then used RMPath to draw a couple of lines like this:

```
CLLocationCoordinate2D KRDU = { 35.8776389, -78.7874722 };
CLLocationCoordinate2D KSFO = { 37.6190, -122.3749};

CLLocationCoordinate2D start = KRDU;
CLLocationCoordinate2D end = KSFO;

RMPath *path = [[RMPath alloc] initWithView:mapView];
[path setDrawingMode:kCGPathStroke];
[path moveToCoordinate:start];
[path addLineToCoordinate:GetHaversineMidpoint(start, end)];
[path addLineToCoordinate:end];
```

When I scroll (and apparently specifically when new tiles are shown), the line jumps around quite a bit. It's most noticeable when scrolling left and right. I've seen this in the simulator; I haven't tried on device yet.

**Comment by ivgalic** [comment]
I'm experiencing the same issue. For me it flickers in various directions though, depending on the shape of the path. I may be wrong, but it kind of seems like it gets drawn at a different zoom level at certain points while I'm scrolling.

**Comment by rnapier** [comment]
Further experiments agree with ivgalic. It is flicking in different directions based on scroll direction.

**Comment by incanus** [comment]
Ok, I'll try to take a look at this soon.

**Comment by incanus** [comment]
Related to this is the upstream https://github.com/Alpstein/route-me/issues/29

**Comment by rhigueraa** [comment]
I was having this same problem, but it got fixed (apparently).
i was loading layers and annotations when i should have just loaded annotations, when i removed the add layer to annotation part so it just remained in the delegate the flickering stopped...

**Comment by incanus** [comment]
Yes, you will get better performance if you only create the layers on demand in the delegate callback.

**Comment by incanus** [comment]
@rnapier, can you have a look at the `develop-refactor` branch, which integrates some upstream changes? Basically `RMPath` is now deprecated in favor of `RMShape`, which is `CAShapeLayer`-backed and should have better performance here. I haven't tested it yet myself, though.

**Comment by incanus** [comment]
Closing this out -- `RMShape` is now in `develop` and you should use it instead of `RMPath`.
