### ISSUE TITLE
RMMarker: init with UIColor doesn't convert tintColor to hex correctly

### ISSUE THREAD

**Issue by jou** [mapbox/DEPRECATED-mapbox-ios-sdk#261]
In `initWithMapBoxMarkerImage:tintColor:size:`, `UIColor` gets converted into hex representation with this:

``` objc
    if (color)
    {
        CGFloat red, green, blue, alpha;

        if ([color getRed:&red green:&green blue:&blue alpha:&alpha])
            colorHex = [NSString stringWithFormat:@"%02x%02x%02x", ((NSUInteger)red * 255), ((NSUInteger)green * 255), ((NSUInteger)blue * 255)];
    }
```

The problem is that the multiplicator instead of the result of the multiplication gets rounded down which results in `0` for each components that doesn't have `1.0` as value.

**Comment by incanus** [comment]
This was fixed in 3f484a16fef2cc702534228d482ba9f4bfa978fb.
