### ISSUE TITLE
toggling mapView.showsUserLocation

### ISSUE THREAD

**Issue by dsa** [mapbox/DEPRECATED-mapbox-ios-sdk#266]
The map is initialized with: 
mapView.showsUserLocation = YES

I have a button that simply toggles this property off/on.

However, after setting mapView.showsUserLocation = NO, setting it back to YES never actually redisplays the user's location.

Any ideas?

**Comment by incanus** [comment]
Sorry about the delay here; for more timely support I'd recommend [support.mapbox.com](http://support.mapbox.com) in the future. 

Is this still an issue? I don't see this happen. Are you setting the `BOOL` from the main UI thread?
