### ISSUE TITLE
bug in - (void)setContentSize:(CGSize)contentSize on iOS 6.1

### ISSUE THREAD

**Issue by andreacremaschi** [mapbox/DEPRECATED-mapbox-ios-sdk#272]
Hi 
there seems to be a bug affecting mapbox iOS SDK on iOS 6.1 only (this appears to be fixed with 6.1.3).

In RMMapScrollView.m this code:

``` objective-c
- (void)setContentSize:(CGSize)contentSize
{
    CGFloat factor = 1.0;

    if (self.mapScrollViewDelegate)
    {
        CGSize previousContentSize = contentSize;

        [self.mapScrollViewDelegate scrollView:self correctedContentSize:&contentSize];

        factor = contentSize.width / previousContentSize.width;
    }

    [super setContentSize:contentSize];

    if (factor != 1.0)
        self.zoomScale *= factor;
}
```

causes a circular loop because this line:
        `self.zoomScale *= factor;`

triggers a call to `setContentSize:` and `factor` never gets == 1.0 
The bug goes away with iOS 6.1.3

**Comment by derekmpeterson** [comment]
Could this be related to #270?

**Comment by incanus** [comment]
Hmm, not sure what to do if this affects < 6.1.3.
