### ISSUE TITLE
iOS 7 compatibility

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#275]
**Note that iOS 7 is currently under NDA. Do not refer to any details of technology under NDA here.**

I've began working privately on iOS 7-compatible code, both in terms of larger API changes as well as UI fit, in an offline branch. I'd love to get some eyes on this from folks who are also under NDA (@alpstein @cocoahero @zhm etc.) Anyone interested in conferring in a private forum?

**Comment by cocoahero** [comment]
:+1:

**Comment by ccarse** [comment]
:+1:

**Comment by incanus** [comment]
Cool, got a private repo for iOS 7 dev going now for this. Feel free to post here if you are likewise under Apple's NDA and would like to collaborate.

**Comment by incanus** [comment]
I should also add that the work on Mapnik iOS is in another repo still, but I can give anyone who's interested access. It is also based currently on iOS 7 and so is also under NDA.

**Comment by ccarse** [comment]
So, I should have some time soon to look at this, maybe knock out some issues. I'd love to see the Mapnik stuff too. :)

**Comment by cga-F4** [comment]
Hi,
Do you know what will happen next for iOS7 and Mapbox ios sdk ? When will you update (I think mostly of the callout style) ?

**Comment by incanus** [comment]
This work has been going on behind the scenes. It will be ready for the iOS release next week.

**Comment by cga-F4** [comment]
I see there is an iOS7 branch for the project. Can we use it ? Will it be merged into release branch ?

**Comment by incanus** [comment]
This is being handled in #315 now.
