### ISSUE TITLE
Disappearing RMShape

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#278]
When my map is in RMUserTrackingModeFollowWithHeading my RMShape is disappearing and then reappearing a lot. This problem is similar to what is described here...

http://support.mapbox.com/discussions/mapbox-ios-sdk/551-rmshapes-disappearing-when-partially-on-screen

I have tracked the problem down to the zPosition reordering in `[RMMapView correctOrderingOfAllAnnotations]`.

```
for (CGFloat i = 0; i < [sortedAnnotations count]; i++) {
    ((RMAnnotation *)[sortedAnnotations objectAtIndex:i]).layer.zPosition = (CGFloat)i;
}
```

If I change "i" to 1 instead of 0 then the problem goes away. Also if I set orderMarkersByYPosition, which means that correctOrderingOfAllAnnotations is not run, then the problem goes away too.

I am using MapBox 1.0.3.

**Comment by incanus** [comment]
@onato, any way you could contribute a code fix to this? I will try to get a chance to dig into it, but it's not clear to me offhand why this might be happening.

**Comment by incanus** [comment]
@onato do you still see this in 1.1.0?
