### ISSUE TITLE
The map tries to load different tiles on device and on the simulator

### ISSUE THREAD

**Issue by zebtin** [mapbox/DEPRECATED-mapbox-ios-sdk#28]
I am printing the requested tile, and I can clearly see that the map is asking for different tiles when run on the device and the simulator:

The pattern is: zoomLevel_x_y

Simulator:

2012-05-17 20:07:51.189 Metro[1078:1b703] Image: 13_5120_831
2012-05-17 20:07:51.189 Metro[1078:1a503] Image: 13_1840_4546
2012-05-17 20:07:51.212 Metro[1078:1b703] Image: 13_1840_4546
2012-05-17 20:07:51.247 Metro[1078:1a503] Image: 13_1839_4546
2012-05-17 20:07:51.299 Metro[1078:1b703] Image: 13_1840_4547
2012-05-17 20:07:51.316 Metro[1078:1a503] Image: 13_1840_4547
2012-05-17 20:07:51.351 Metro[1078:1b703] Image: 13_1839_4547
2012-05-17 20:07:51.386 Metro[1078:1a503] Image: 13_1839_4547

Device:

2012-05-17 20:08:44.751 Metro[5652:3703] Image: 13_5120_831
2012-05-17 20:08:44.752 Metro[5652:1903] Image: 13_5119_831
2012-05-17 20:08:44.851 Metro[5652:1903] Image: 13_5120_831
2012-05-17 20:08:44.852 Metro[5652:3703] Image: 13_5120_832
2012-05-17 20:08:44.865 Metro[5652:1903] Image: 13_5120_832
2012-05-17 20:08:44.869 Metro[5652:3703] Image: 13_5119_832

This is a really big problem because the tiles needed on the dive do not exist on the database, so it appears as an empty gray map.

What do you guys think the problem is?

**Comment by zebtin** [comment]
I have verified this happens only with databases generated using TileMill. When I try it with the ones provided by the sample it works perfectly.

**Comment by incanus** [comment]
Hmm, this is odd. Can you maybe provide a sample MBTiles for me to try?

**Comment by zebtin** [comment]
I have done some additional testing and found something very odd.

I did all the testing using the Sample App to take code errors out of the equation.

So, using the provided mbtiles (control room) everything works as expected.

When using a mbtiles database generated using TilleMill not even the sample app works.

Here is an example mbtiles where this happens: https://www.dropbox.com/s/3h0vqcr1b8enrxc/metro%5B1.0%5D.mbtiles

When analyzing the structure of both databases you can clearly see they are completely different:

![Test](http://dl.dropbox.com/u/11470523/DataCompare.png)

So I went and manually changed the structure of the databse to match the Control Room database and it is all working now.

So I am absolutely sure the problem is that the databases being exported from TilleMill dont have the same format as the ones used on the example app.

Please tell me if I can do anything else to help, I could also send you the python script I used to fix the database structure.

**Comment by incanus** [comment]
I'll check out this file you've linked, but the schema differences are ok. See [the spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md). The grid stuff is all optional and is related to interactivity. All you really need is `metadata` and `tiles`, which can be either a true table or a view as done in the left example following de-duplication optimizations.

**Comment by zebtin** [comment]
I was fighting with it in my head forever too, as it SHOULD work the same with tiles as a view instead of a table, but for some strange reason it doesn't load on my app and it doesn't load on the sample app either.

Hopefully you can figure out what is going on, what I did to make it work was create a new database with just two tables and copied the info from the tiles view on the original to an actual table on a new database.

**Comment by incanus** [comment]
So I just grabbed your MBTiles and after renaming it to `metro.mbtiles` (to avoid the square brackets) it works fine on both sim and device. I'm doing this: 

```
mapView.zoom = 13;

CLLocationCoordinate2D centerCoordinate = {
    .latitude  =  19.4326, 
    .longitude = -99.1331
};

[mapView setCenterCoordinate:centerCoordinate animated:NO];
```

After instantiating the map view in `OfflineLayerViewController`.
