### ISSUE TITLE
Background caching should move to RMDatabaseCache

### ISSUE THREAD

**Issue by RubioV** [mapbox/DEPRECATED-mapbox-ios-sdk#281]
Per http://support.mapbox.com/discussions/mapbox-ios-sdk/1324-offline-caching-improvements

Background caching is more appropriate to be handled by `RMDatabaseCache` than `RMTileCache`. I will work on moving the code to `RMDatabaseCache` and will submit a pull request.

**Comment by incanus** [comment]
One more. Any movement @RubioV?

**Comment by RubioV** [comment]
@incanus, as seen above, I did open a pull request against this issue: https://github.com/mapbox/mapbox-ios-sdk/pull/292.
