### ISSUE TITLE
RMTileCache initialization is not very flexible

### ISSUE THREAD

**Issue by RubioV** [mapbox/DEPRECATED-mapbox-ios-sdk#282]
Per http://support.mapbox.com/discussions/mapbox-ios-sdk/1324-offline-caching-improvements

When `RMTileCache` initializes, it uses the cache configuration from the route-me property list by default. If that doesn't exist, it creates a memory cache and database cache with default parameters. This behaviour is hard coded and can't be altered from code, only through the property list. It would be useful if `RMTileCache` could be initialised with a custom array of `id<RMTileCache>` objects. That way the developer has full control over caching. I will work on this and will submit a pull request.

**Comment by incanus** [comment]
Same here — any movement @RubioV?

**Comment by RubioV** [comment]
@incanus, as seen above, I did open a pull request against this issue: https://github.com/mapbox/mapbox-ios-sdk/pull/292.
