### ISSUE TITLE
Tile caches can not be removed from RMTileCache

### ISSUE THREAD

**Issue by RubioV** [mapbox/DEPRECATED-mapbox-ios-sdk#283]
Per http://support.mapbox.com/discussions/mapbox-ios-sdk/1324-offline-caching-improvements

`RMTileCache` allows tile caches to be added to the `_tileCaches` array through the `addCache` and `insertCache` methods. However, caches can't be removed from this array. This would be useful in order to swap offline database caches in and out of a map view's cache. I will work on this and will submit a pull request.

**Comment by incanus** [comment]
@RubioV Any luck on a PR?

**Comment by RubioV** [comment]
@incanus, as seen above, I did open a pull request against this issue: https://github.com/mapbox/mapbox-ios-sdk/pull/292.
