### ISSUE TITLE
New tile images are added to RMDatabaseCaches which are meant for read-only usage

### ISSUE THREAD

**Issue by RubioV** [mapbox/DEPRECATED-mapbox-ios-sdk#284]
Per http://support.mapbox.com/discussions/mapbox-ios-sdk/1324-offline-caching-improvements

RMDatabaseCaches are often used to store offline tiles. These databases should be used read-only. However, when they are added to a MapView's tile cache, new, on-demand fetched tile images are also added to the database, leading to data-duplication and a waste of disk space. There should be a way to use RMDatabaseCache as read-only. I will work on this and will submit a pull request.

**Comment by incanus** [comment]
Any luck here @RubioV? This is not the actual intent of `RMDatabaseCache` — it's meant to be both a performance and offline cache due to the SDK's (and upstream project's) design.

**Comment by RubioV** [comment]
@incanus, as seen above, I did open a pull request against this issue: https://github.com/mapbox/mapbox-ios-sdk/pull/292. If you don't want to adopt this philosophy in the project feel free to reject that part of the pull request.
