### ISSUE TITLE
look into Alcatraz template

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#294]
Don't totally understand this yet, but I saw @mattt present on this for AFNetworking recently and it could be useful for SDK templates as well. 

http://mneorr.github.io/Alcatraz/

**Comment by mattt** [comment]
I think this is a great idea. Please rip off as much of my [AFNetworking Xcode Project Template](https://github.com/AFNetworking/Xcode-Project-Templates) as would be useful. Happy to answer any questions about the dark arts of Xcode templating.

**Comment by incanus** [comment]
iOS 8 and dynamic frameworks that work just like Apple's, plus CocoaPods, pretty much make this obsolete IMHO.
