### ISSUE TITLE
Error in delegates PressOnMap when you use heading

### ISSUE THREAD

**Issue by Nicolastriplec** [mapbox/DEPRECATED-mapbox-ios-sdk#299]
I used this event to insert an annotation in the mapview by touch, while the map was in heading mode, but the annotation apeared in another side non rotated, I fixed it just with a little hack in RMMapView.m, for example I changed

 [_delegate longPressOnMap:self at:[recognizer locationInView:self]];

by

 [_delegate longPressOnMap:self at:[recognizer locationInView:_overlayView]];

Maybe it is not polite but it works good now :)
I hope that helps :)

**Comment by incanus** [comment]
Is this still effective or an issue with 1.1.0? That release changed long-press behavior related to annotation drag and drop.
