### ISSUE TITLE
Correct retina display tile size parameters

### ISSUE THREAD

**Issue by fotiDim** [mapbox/DEPRECATED-mapbox-ios-sdk#310]
I want to learn the correct parameters for retina (and of course non-retina display support).

I have not set the adjustTilesForRetinaDisplay so I believe it is false.
I am feeding tiles dynamically generated during runtime. In the non-retina case I am feeding 256px tiles and setting tileSideLength to 256. In the retina case I am feeding 512px tiles and setting tileSideLength to 512. Am I correct?

Do I also need to set the autoresizingMask to anything?

**Comment by incanus** [comment]
The `autoresizingmMask` just has to do with normal `UIView` superview/subview sizing, not anything specific to retina. 

If you have control over the tile styling, then yes, leave `adjustTilesForRetinaDisplay` to the default of `NO`. 

In the retina case, feed 512px tiles, but set the `tileSideLength` to 256px to "squash" them down. That way, the features will appear the same size as non-retina 256px tiles on a non-retina device.
