### ISSUE TITLE
map zooming/movement disabled when gesture starts on RMMarker

### ISSUE THREAD

**Issue by izakpavel** [mapbox/DEPRECATED-mapbox-ios-sdk#32]
I have maps with several markers created like this

marker = [[RMMarker alloc] initWithUIImage:[UIImage imageNamed:@"icon.png"] anchorPoint:annotation.anchorPoint];

markers somehow consumes the touch gestures, so i cannot move or zoom the map when starting the gesture at marker location.

**Comment by incanus** [comment]
Yeah, this is being tracked upstream: https://github.com/Alpstein/route-me/issues/48

I will keep an eye on it, and when I get a chance, take a look myself.

**Comment by boxed** [comment]
Funny, I have the opposite problem: swipe gestures starting on a marker sometimes doesn't call shouldDragAnnotation: at all but pans the map instead. Say I want to move a marker straight south, if I start the gesture on the marker and swipe down sometimes the map is panned. I have more success if I start the gesture just slightly north of the marker. It seems to me like the first few points of the swipe are skipped over when calculating the gesture...

**Comment by incanus** [comment]
I'm wondering if a better approach here might be requiring/recognizing a long press gesture first. Once the long press is recognized, it could query the delegate for clearance, then go into a drag gesture recognition, somewhat more like MapKit does with the dropped purple pins. 

Thoughts @izakpavel @boxed @trasch?

**Comment by incanus** [comment]
The core issue is solved upstream and the broader dragging issue is now captured in #181. Closing.
