### ISSUE TITLE
Unable to compile Proj4 with RubyMotion with all 1.* versions

### ISSUE THREAD

**Issue by vespakoen** [mapbox/DEPRECATED-mapbox-ios-sdk#321]
Starting at version 1.0.0, RubyMotion is unable to compile Proj4, I have tried a lot of things to no avail.

It starts complaining about PODS_ROOT not being set, after setting it, other problems occur.

The only solution for me is to set the version to 0.5.2, compile it, then back to the latest version and it will work.

I have talked to the RubyMotion guys about this issue, they first thought the PODS_ROOT was causing the trouble, and advised me to use the "vendored_libraries" option (http://docs.cocoapods.org/specification.html#vendored_libraries).
Changing the Podspec by integrating the the vendored_libraries option didn't help.

Unfortunately the errors have been changing a lot so I cannot tell exactly where it's coming from.

If there is anything I can do to help out, please let me know.

**Comment by incanus** [comment]
I'm not really familiar with RubyMotion, but the normal pod builds fine. Unfortunately I think this is better suited for the RubyMotion and/or CocoaPods folks. I'm happy to help out with specific error messages, though.
