### ISSUE TITLE
polish callouts for iOS 7

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#326]
Carryover from #315. This is tracking upstream in https://github.com/nfarina/calloutview/pull/52. Main things needed for our uses are: 
- Callouts can occasionally appear under the navigation bar. 
- Callout appearance animation needs tweaks (shouldn't pop).

**Comment by Wirsing84** [comment]
Will this account for nice iOS 7 style callouts? (_but there is hope_)

**Comment by incanus** [comment]
Check out the develop branch for the latest iOS 7. It's quite close to release and looks good. Very slight tweaks needed, mostly behavioral.

**Comment by Wirsing84** [comment]
Thanks, that's great news, will check out develop asap. any rough inofficial timeline of when it will be released? 2 weeks or 2 months?
Cheers
Chris

**Comment by incanus** [comment]
I'd say on the order of weeks, with the holidays. Mostly waiting on the callouts but you can see the milestone here: https://github.com/mapbox/mapbox-ios-sdk/issues?milestone=6&state=open

**Comment by incanus** [comment]
This is all fixed up as of a320a649566ee90290fa628e21e84da976a54740.

**Comment by frowing** [comment]
I see this is fixed in the develop branch, any idea when this will be released?

**Comment by incanus** [comment]
It hasn't been on the radar with other work on MBX and GL, but I'll try to roll one in the next week.

**Comment by frowing** [comment]
Thanks!

**Comment by incanus** [comment]
Just released `1.2.0` with the latest `develop`.

**Comment by frowing** [comment]
Thank you! Do you know how long it will take until the pod is updated to 1.2.0?
