### ISSUE TITLE
64-bit review

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#327]
This is mostly string format specifiers.

**Comment by js** [comment]
And the statically linked libProj4.a needs to be rebuilt

**Comment by incanus** [comment]
That's all good to go in the `develop` branch. See e.g. https://github.com/mapbox/mapbox-ios-sdk/commit/ed4992c1e6eaf9c5bb3037481d5f1cd51cdf3c9b https://github.com/mapbox/mapbox-ios-sdk/commit/f0840458c4b595e60a5ea9ec1340155655b212e8 https://github.com/mapbox/mapbox-ios-sdk/commit/7db0f01625a5413c88c004b5e1f226173abbdd83 https://github.com/mapbox/mapbox-ios-sdk/commit/6adfc4135acb9d459284f87b2f084636e8772d6a
