### ISSUE TITLE
Water / Land detection

### ISSUE THREAD

**Issue by thomasbrueggemann** [mapbox/DEPRECATED-mapbox-ios-sdk#333]
Is there any possible way to query the MapView by a coordinate and get back the terrain-type (water, land) as a result?

BTW: http://stackoverflow.com/questions/19775585/mapbox-water-land-detection

**Comment by incanus** [comment]
There isn't currently, as you'd have to have the map tile imagery backed up with some sort of API for that, and MapBox does not have that. However, you could make use of Apple's `CLGeocoder` and the `CLPlacemark`'s `ocean` and `inlandWater` properties. If they were both `nil`, you'd be on land. That would get you pretty far.

**Comment by thomasbrueggemann** [comment]
Thanks for the infos!
