### ISSUE TITLE
Clustering bug - Closer annotations are ignored and farther annotations are clustered

### ISSUE THREAD

**Issue by mahadevans87** [mapbox/DEPRECATED-mapbox-ios-sdk#334]
Sometimes, while clustering, an annotation does not cluster with the nearer annotation. Rather it goes and forms a cluster with another one that's relatively far away. I suspect this occurs the method. 

I suspect this occurs because some of the annotations get added to the wrong quadtree ( northeast, northwest, southeast, southwest )

**Comment by incanus** [comment]
Assigned to [Tender discussion #1714](http://support.mapbox.com/discussions/mapbox-ios-sdk/1714-bug-in-clustering).

**Comment by incanus** [comment]
_(Carrying over Tender discussion info for this commit in case anyone wants to try it.)_

>  I haven't heavily performance tested it yet, but it fixes the bug that you discovered:
> 1. Each annotation is iterated through.
> 2. It is compared with every other annotation.
> 3. If one is close enough, the first annotation is considered clustered and removed from a list.
> 4. Go back to Step 1.
> 5. Step 2 skips any annotations removed from the list, so comparisons aren't accurate because not all neighbors are considered.

**Comment by mahadevans87** [comment]
Works reasonably well now. Thanks
