### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by tmcw** [mapbox/DEPRECATED-mapbox-ios-sdk#335]
https://www.mapbox.com/mapbox-ios-sdk/#api_overview links to https://www.mapbox.com/mapbox-ios-sdk/api/#RMShape and similar while it should link to https://www.mapbox.com/mapbox-ios-sdk/api/#RMShape-class

**Comment by incanus** [comment]
Thanks for the catch -- looks like it's been that way just over a year since f18afc164e2ddf8dd78621123ca36912aa9191fe. Fixed in cca9407e1e5622981eaa741b7a18b0091ddb8459.
