### ISSUE TITLE
RMDatabaseCache.removeAllCachedImagesForCacheKey does not shrink DB file

### ISSUE THREAD

**Issue by jamesdhutton** [mapbox/DEPRECATED-mapbox-ios-sdk#337]
The removeAllCachedImagesForCacheKey method on RMDatabaseCache does not shrink the database file.

I would have expected it to do so, especially considering that the related methods removeAllCachedImages and purgeTiles do shrink the file.

There is a one-line fix, which is to call the VACUUM query from within the method.

**Comment by incanus** [comment]
I was going to say -- sounds like a lack of `VACUUM`. I'll look into this.

**Comment by jamesdhutton** [comment]
Also, I've just noticed that the VACUUM calls in removeAllCachedImages and purgeTiles don't actually work, so these methods also fail to shrink the file.

The fix is to use executeUpdate rather than executeQuery when calling VACUUM.

**Comment by incanus** [comment]
Any chance you could submit a pull request? It seems simple enough but I won't get to it right away.

**Comment by jamesdhutton** [comment]
Done. See pull request #338

**Comment by incanus** [comment]
Awesome! I'll check it out. I know it's a small delta but it helps.

**Comment by eibenm** [comment]
I'm having this exact problem right now.  It seems that in the removeAllCachedImages method in the RMDatabaseCache.m file.

if you replace:

[[db executeQuery:@"VACUUM"] close];

with:

[db executeUpdate:@"VACUUM"];

the file is appropriately reduced in size to reflect the method executing.

**Comment by incanus** [comment]
Defering to #338, which appears to fix this, but I want to make sure we're calling `close` properly if need be in the new methods.
