### ISSUE TITLE
Accessibility Support - VoiceOver

### ISSUE THREAD

**Issue by barnaclebarnes** [mapbox/DEPRECATED-mapbox-ios-sdk#339]
We've been working with a client on an app that uses the MapBox iOS SDK. There are 2 accessibility issues that we have run into.
## No VoiceOver support for info windows

There does not seem to be a way to easily support VoiceOver when a user clicks a marker and gets an info window. When the user clicks a marker VoiceOver should read out the label for this marker.
## Clicking the 'i' button does not give any information

When you click the 'i' button in the bottom left of the screen it folds up the page but there is no accessibility description of how to close this screen (it is basically 'stuck').

These are the two most important issues but there is a lot more that can be done to make the maps more accessible. What is the best way to scope out what would be best practice and is there any desire within the community to provide these features?
- Apple Accessibility info here: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/iPhoneAccessibility/Accessibility_on_iPhone/Accessibility_on_iPhone.html

**Comment by incanus** [comment]
Cool, thanks for the feedback here. 
1. For the info windows (callouts), the upstream project is actually https://github.com/nfarina/calloutview. However I have an interest in upping our accessibility game in general. It seems that regardless of callout presentation, though, tapping a marker should read its title? i.e. this is an `-[RMAnnotation title]` issue and independent of whether the implementation by the app author actually shows a callout? 
2. For the attribution button, this is changing in iOS 7 (currently the `develop` branch) anyway to be a slide-up modal as opposed to a more skeuomorphic page curl, though this will remain in the pre-7 versions. If it helps any, tapping anywhere besides the actual links shown under the page curl will dismiss, much like Apple's Maps.app used to work with its page curl. How would you recommend fixing this up? An invisible button with a label that is read? 

In both of these issues (as well as the others you allude to), I'm totally open to your expertise here. I for one would like to know more about how to make this better as well as what conventions are for various behaviors. We can scope it right here in this ticket if you like.
