### ISSUE TITLE
Multiple linker errors installing with CocoaPods

### ISSUE THREAD

**Issue by betzerra** [mapbox/DEPRECATED-mapbox-ios-sdk#341]
Hi guys, do you have an idea what I'm missing? The CocaPods instructions are pretty straight forward and I'm getting lots of linker errors.

![screen shot 2013-11-21 at 3 32 06 pm](https://f.cloud.github.com/assets/681600/1595556/4915f532-52ec-11e3-8497-b409e701b62b.png)

**Comment by betzerra** [comment]
Also got this after "pod install"

[!] [MapBox (1.0.3)] The pre install hook of the specification DSL has been deprecated, use the `resource_bundles` or the `prepare_command` attributes.
[!] [MapBox (1.0.3)] The `documentation` DSL directive of the podspec format has been deprecated.
[!] [FMDB (2.0)] `preferred_dependency` has been renamed to `default_subspec`.
[!] [FMDB (2.0)] `preferred_dependency` has been renamed to `default_subspec`.
[!] [FMDB (2.0)] `preferred_dependency` has been renamed to `default_subspec`.

**Comment by incanus** [comment]
Yeah, the deprecations will be taken care of soon. CocoaPods moves a little fast for my liking and I find myself having to make several inter-release updates to our podspec just to keep up. Those are just warnings for now. 

On the install front, it looks like Proj4 (bundling with) and SQLite (Apple's) aren't being linked right. 

Which branch are you using? Just straight out of CocoaPods or pointing at a hosted podspec or local version? Are you using any other pods? Mind posting your `Podfile`?

**Comment by betzerra** [comment]
@incanus thank you so much for the fast reply! Sure, here's my Podfile

```
# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "PatientApp" do
platform :ios, '6.0'

pod 'AFNetworking', '~> 1.3.3'
pod 'MapBox'
pod 'MBProgressHUD'
pod 'PaymentKit', :git => 'https://github.com/stripe/PaymentKit.git'
pod 'TwilioSDK'
pod 'GPUImage', '~> 0.1.1'
end

target "PatientAppTests" do

end
```

I'm using XCode 5.0.2 BTW

**Comment by incanus** [comment]
Wow, strange. So you're using a stock MapBox, above iOS 5.0. Though I haven't seen this `target` syntax or the `end` lines before. Can you try without them? The latest podspec lints just fine, albeit with deprecation warnings.

**Comment by betzerra** [comment]
@incanus same error without the last block. 

I tried the binary approach and I succeed, except that now I'm having this other issue https://github.com/mapbox/mapbox-ios-sdk/issues/342 (I'm not having good luck with MapBox today LOL)

**Comment by incanus** [comment]
Are you still having this issue @betzerra? With release 1.1.0 installed as per #377?
