### ISSUE TITLE
Bad Access when loading RMMapBoxSource without internet connection

### ISSUE THREAD

**Issue by ewoudwijma** [mapbox/DEPRECATED-mapbox-ios-sdk#343]
Hi all,

I have the following Bug Report:

If you call RMMapBoxSource.initWithReferenceURL without an internet connection, the sub call to brandedStringWithContentsOfURL wants to store an error value but initWithReferenceURL is called with a nil error variable. This causes a Bad Access error. I think this should be replaced by:
    NSError *error;
    if ([[referenceURL pathExtension] isEqualToString:@"json"] && (dataObject = [NSString brandedStringWithContentsOfURL:referenceURL encoding:NSUTF8StringEncoding error:&error]) && dataObject).
I assume must also be done in initWithTileJSON as brandedStringWithContentsOfURL is also called there with error: nil.

Second, no internet connection causes a return nil in initWithReferenceURL, after that the dealloc is called which tries to release _dataQueue which has not been initialized, which also causes a Bad Access error. This can be avoided by adding 
    _dataQueue = dispatch_queue_create(nil, DISPATCH_QUEUE_SERIAL);
as the first line in initWithReferenceURL.

Regards,
Ewoud Wijma
GPS++ (www.gpsplusplus.com)

**Comment by incanus** [comment]
These are both fixed in `develop`. See also https://github.com/mapbox/mapbox-ios-sdk/pull/290 and https://github.com/mapbox/mapbox-ios-sdk/commit/f2954afb9f44fb5a5bbe9b8ef5571995576607aa
