### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by tristen** [mapbox/DEPRECATED-mapbox-ios-sdk#346]
It would be nice to access the changelog from the repository and link to it from the site - replacing the page created for it on the site.  For consistency sake sticking to the same format as https://github.com/mapbox/mapbox.js/blob/master/CHANGELOG.md is preferred.

Would also want to see this over on https://github.com/mapbox/mbxmapkit

**Comment by incanus** [comment]
We did this starting in 011eaba3c163be535a37fb488a96c44187dfbd26.
