### ISSUE TITLE
Allow map insets

### ISSUE THREAD

**Issue by jklimke** [mapbox/DEPRECATED-mapbox-ios-sdk#348]
It would be very nice to be able to define the spatial extent of a map layer. This would be useful to integrate map layers to applications that have, i.e., only be gerenerated for a specfiic city.

Currently, as far as i know, there tiles are always requested from a server. It would be nice, if there would be a possibility to check if the map layer provides tiles for the specific tile number. currently this is not possible.

**Comment by incanus** [comment]
If I'm understanding you right, we do this with MapBox sources now: https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapBoxSource.m#L282 And this is in the `RMTileSource` protocol for all tile sources to do.

**Comment by jklimke** [comment]
Thank you for your hint. i looked at the usages of the latitudeLongitudeBoundingBox and i could not find a point in the framework where the availability of a remote or database tile is determined using these bounds. It looks like this is only used to calculate a total map bounding box. 

What i wanted to achieve is a check before a tile is fetched. This seems currently not to be integrated into the tile fetching process.

**Comment by jklimke** [comment]
I debug this down a little. the asynchronous tile loading caused a tile to be tried to load repeatedly.

i would propose to check earlier the tile availability and abort the loading process. In RMMapTiledLayerView.m i replaced the check in case of a non snapshot renderer from:

if (zoom >= _tileSource.minZoom && zoom <= _tileSource.maxZoom)

to 

if (zoom >= _tileSource.minZoom && zoom <= _tileSource.maxZoom && [_tileSource tileSourceHasTile: RMTileMake(x, y, zoom)])

It feels a lot faster right now, probably because of some less DB requests and tile loads. Do you think this could be useful for the overall framework ? I could create a pull request for that.

**Comment by incanus** [comment]
@jklimke Sorry for the delay in replying here. If you're still willing, I'd love to have a look at a pull request if you are still seeing a performance increase.
