### ISSUE TITLE
zoom constraint are not working

### ISSUE THREAD

**Issue by andreacremaschi** [mapbox/DEPRECATED-mapbox-ios-sdk#35]
Hi
I am facing an issue while trying to set up a max/min zoom constraint in a RMMapView instance for a .mbtiles file with limited bounds and zoom range 10-19. When I zoom out with a pinch gesture, the scrollview doesn't block the zoom and the map completely disappear, when I zoom in the NSAssert in RMMBTilesSource - imageForTile:inCache: method is thrown.

The map is setup following the sample code:

```
    RMMapView *lMapView = [[RMMapView alloc] initWithFrame: self.view.bounds                                
                                             andTilesource: tilesSource
                                          centerCoordinate: startCoordinates
                                                 zoomLevel: (tilesSource.maxZoom+tilesSource.minZoom) / 2.0
                                              maxZoomLevel: tilesSource.maxZoom
                                              minZoomLevel: tilesSource.minZoom
                                           backgroundImage: nil];
```

**Comment by andreacremaschi** [comment]
rif: https://github.com/Alpstein/route-me/issues/30

**Comment by andreacremaschi** [comment]
rif2: https://github.com/Alpstein/route-me/issues/43

Sorry, this is an already known issue of route-me framework, not mapbox..
incanus' bugfix is not working for me though!

**Comment by incanus** [comment]
Yeah, this isn't completely tackled yet. I think it's completely captured in #12 and https://github.com/Alpstein/route-me/issues/43, so closing here.
