### ISSUE TITLE
RMMarker rotation

### ISSUE THREAD

**Issue by RubioV** [mapbox/DEPRECATED-mapbox-ios-sdk#351]
@incanus, for my own needs, I have made some modifications to the SDK to allow for RMMarker rotations. Geographic rotations are possible, relative to north, or alternatively, rotations relative to the screen. In the process, I also had to fix the way the callouts were displayed. In the current SDK, the callout display rotates together with the map view in case of `RMUserTrackingModeFollowWithHeading`. I thought it would be better if the callouts stay upright, relative to the devices screen, so I've included a fix for that.

This might also help you with issue https://github.com/mapbox/mapbox-ios-sdk/issues/19 (allow map rotation).

My changes seem to work OK but they need a bit more testing and I need to finalize it in a pull request. From your posts recently, it seems like you're getting ready for another release soon. Would you like me to submit this pull request for before that release? In that case I'll try to make it a priority and submit soon. If not, it'll be a bit later.

Regards
Rubio

**Comment by ManuelRiegler** [comment]
did you also add public methods for map rotation itself, like in issue #19 (allow map rotation) mentioned?

**Comment by RubioV** [comment]
I didn't implement the map rotation itself, as I have no need for it. I think it should be fairly easy to implement since rotation is already working for `RMUserTrackingModeFollowWithHeading`. What my code does is it fixes the callouts so that they are always pointing up, relative to the screen, instead of rotating with the map.

**Comment by incanus** [comment]
No hurry; I'd prefer to not have it in this release. Please just submit the PR against `develop` since that's where I merge to. Cool addition!

**Comment by RubioV** [comment]
Sure, I'll submit against develop as usual. It'll be a few weeks before I submit.

**Comment by incanus** [comment]
Closing this in favor of the future pull request as it's not actionable here.

**Comment by hpogosyan** [comment]
@incanus Will this feature allow us to get a birds eye view of the map via rotation (angle) ?

**Comment by incanus** [comment]
This is just talking about rotation about the z-axis, i.e., how compass tracking works in 2D mode. In future we will also want rotation about the x-axis, i.e., perspective tilting, but that's not on the radar yet.
