### ISSUE TITLE
consider setting no-backup key on tile cache

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#354]
Assigned to [MapBox iOS SDK #1951](http://support.mapbox.com/discussions/mapbox-ios-sdk/1951-app-rejected-due-to-223-apps-must-follow-the-ios-data-storage-guidelines-or-they-will-be-rejected). We should consider setting the `NSURLIsExcludedFromBackupKey` key if we keep the tile cache in the Documents folder

**Comment by incanus** [comment]
Status quo is ok.

**Comment by mhaleem** [comment]
Hello may i know what is the solution of that problem currently as my App was rejected due to that problem, should i fix it manually in Mapbox code till we have a fix?

**Comment by incanus** [comment]
You can fix this with the following documented API @mhaleem: 

https://github.com/mapbox/mapbox-ios-sdk/blob/509fa7df46ebd654d130ab2f530a8e380bf2bd59/MapView/Map/RMDatabaseCache.h#L53

**Comment by trdavidson** [comment]
Hi Incanus, in the offline example app using swift, the RMDatabaseCache is still living in the Documents folder. When I try to add an additional cache initialized using the 'useCacheDirectory' all that happens is that a second cache now appears - removing the Documents based one seems not possible. If I may ask - what is the rational for initialzing this cache in Documents in the first place if by now it is a well documented fact that this will lead to rejection in the App Store?
