### ISSUE TITLE
Unable to use RMBingSource support in MapBox

### ISSUE THREAD

**Issue by Sumanpreet2323** [mapbox/DEPRECATED-mapbox-ios-sdk#357]
Hey,
I am developing an application using MapBox and have used the binary method for its installation.I have gone through the examples and they work fine.But when I try to use RMBingSource class for the use of bing maps I am not able to access it.The problem arises only in this particular class if I want to use any other class and its functions I have not issues.For example if I use RMCircle or RMConfiguration classes I can access their functionality but I cannot access RMBingSource functions and it is present in the sdk headers along with all the others.

Please help me out with this issue as my application is based on bing maps only.
Thanks in Advance.

**Comment by incanus** [comment]
Handled via support in http://support.mapbox.com/discussions/mapbox-ios-sdk/2505-unable-to-use-rmbingsource-support-in-mapbox
