### ISSUE TITLE
RMMapView: (429) App crashing after changing bundle name

### ISSUE THREAD

**Issue by bleft** [mapbox/DEPRECATED-mapbox-ios-sdk#358]
App is crashing on line 429: 
    NSAssert([[NSBundle mainBundle] pathForResource:@"Mapbox" ofType:@"bundle"], @"Resource bundle not found in application.");

but works well without changing bundle name: 
    NSAssert([[NSBundle mainBundle] pathForResource:@"MapBox" ofType:@"bundle"], @"Resource bundle not found in application.");

**Comment by incanus** [comment]
Are you doing a clean build? Device or simulator? Existing version of the app installed?

**Comment by bleft** [comment]
Yes I did a clean build. It happens on device and simulator (32 and 64 bit). First try with existing, but also with the app removed.

**Comment by MrZoidberg** [comment]
Remove the app from device/simulator and do a clean build. Works then.

**Comment by incanus** [comment]
Yeah, figured that might be the case. Has to do with a case-insensitive filesystem. I will look into this a bit more and make sure it's not a problem for upgrade paths for folks updating the SDK in their app.

**Comment by incanus** [comment]
This is tricky to test on a real, shipping app. Did you happen to try that, @MrZoidberg?

**Comment by incanus** [comment]
Not seeing this in testing.

**Comment by MrZoidberg** [comment]
Sorry, I was on holidays. I didn't see it in a real AppStore app, but after Mapbox update my app crashed on start on several devices.

**Comment by namannik** [comment]
I just saw this today on the simulator after upgrading to SDK 1.1.0.  The solution was to reset the simulator contents and settings.  (iOS Simulator -> Reset Contents and Settings…)
