### ISSUE TITLE
longPressOnMap called twice by handleLongPress in RMMapView.m

### ISSUE THREAD

**Issue by johnmccombs** [mapbox/DEPRECATED-mapbox-ios-sdk#362]
In develop longPressOnMap is called twice by handleLongPress in RMMapView.m.

In earlier versions longPressOnMap and longPressOnAnnotation were only called once, when recognizer.state == UIGestureRecognizerStateBegan

**Comment by MrZoidberg** [comment]
Also confirm this issue, did a workaround with checking bool variable for now.

**Comment by incanus** [comment]
Hmm, will research, thanks. Related to the new annotation dragging, I'm sure.

**Comment by johnmccombs** [comment]
Previously there was a" if (recognizer.state != UIGestureRecognizerStateBegan) return;" at the start of RMMapView handleLongPress that ensured the code in that method executed for UIGestureRecognizerStateBegan

**Comment by incanus** [comment]
Can you confirm that this still happens & reopen if necessary? `1.2.0` in June made some fixes to the long press gesture.
