### ISSUE TITLE
RMMapLayerDragStateEnding and RMMapLayerDragStateCanceling are not used

### ISSUE THREAD

**Issue by MrZoidberg** [mapbox/DEPRECATED-mapbox-ios-sdk#363]
Hi,

I was trying to track when a user end dragging an annotation with 

```
- (void)mapView:(RMMapView *)mapView annotation:(RMAnnotation *)annotation didChangeDragState:(RMMapLayerDragState)newState fromOldState:(RMMapLayerDragState)oldState
```

but the values I receive for newState value doesn't seem to be obvious for me. I got deeper in the code of mapbox sdk and found out that states RMMapLayerDragStateEnding and RMMapLayerDragStateCanceling are not used and overridden with RMMapLayerDragStateNone.

Anyway I'm still able to track the end of the annotation dragging, but what was the reason for doing so? It seems much better to send the real states.

Thanks,
Mikhail.

**Comment by incanus** [comment]
This operates like the MapKit API, which is to allow a custom annotation to listen to `...Ending` and `...Canceling` status and change itself once any possible animations are complete. This is probably best explained in the new docs for `-[RMMapLayer dragState]`: 

https://github.com/mapbox/mapbox-ios-sdk/blob/63a2b9913c763a905ff2f07a101b21cce3275cc0/MapView/Map/RMMapLayer.h#L58-L68

**Comment by MrZoidberg** [comment]
Thanks for explanation.
