### ISSUE TITLE
RMQuadTree: minPixelDistanceForLeafClustering property and clustering at max zoom

### ISSUE THREAD

**Issue by artysx** [mapbox/DEPRECATED-mapbox-ios-sdk#366]
I'd like to address 2 things:
1. I'd like for kMinPixelDistanceForLeafClustering to be a property, so it will be possible to control the clustering appearance. 
2. I noticed an issue for close located markers, same related to kMinPixelDistanceForLeafClustering, that while the map is already in max zoom, the distance between marker is not enough to uncluster them, while it's maybe possible to show them with minor overlapping.
   So, I propose to add some property to address this issue like minPixelDistanceForLeafClusteringForMaxZoom or unclusterMakersAtMaxZoom, etc.

**Comment by incanus** [comment]
Thanks for the notes, @artysx. We accept pull requests for feature additions like this, though in this case it's probably better suited for the [upstream project](http://github.com/alpstein/route-me). Either way, open a pull and we can evaluate it there.
