### ISSUE TITLE
RMMapView.m updatePoints in -tintColorDidChange might not be initialised

### ISSUE THREAD

**Issue by johnmccombs** [mapbox/DEPRECATED-mapbox-ios-sdk#367]
updatePoints is not necessarily initialised before use in tintColorDidChange

**Comment by incanus** [comment]
You're right; this is probably ok but a little sloppy. I thought I remembered reading someplace that ARC initializes all variables, but I can only find reference to objects being set to `nil`, so I fixed this.

**Comment by johnmccombs** [comment]
My understanding with ARC Is that object pointers, and instance and static variables are initialized to 0/nil, locals are not initialized.

**Comment by incanus** [comment]
Ah, that could have helped my misremembering, too. Thanks!
