### ISSUE TITLE
All annotations MIA after panning map significant distance

### ISSUE THREAD

**Issue by lightandshadow68** [mapbox/DEPRECATED-mapbox-ios-sdk#368]
I've run into an issue where panning a map view a significant distance from it's previous location causes all annotations to disappear from the map. 

Specifically, I populate the map with roughly 15 annotations, some of which are initially offscreen and not visible. As a user iterates over the locations in the app, I pan the map to ensure annotations are shown to the user. When the map pans to annotations that are a significant distance a way (which, in our current dataset, is more than two screens on an iPhone 5) the annotations are not visible on arrival. In addition, when panning back to the original location, the original annotations are missing as well. 

If I re-populate annotations right before panning the map, distant pans are still missing annotations, but they are visible after panning back to the original location. 

I'm using auto layout on both the map itself and several subviews.

**Comment by incanus** [comment]
Autolayout shouldn't matter, just FYI. 

Can you maybe include a bit of code around how you are panning during iteration? Is it animated? etc.

**Comment by lightandshadow68** [comment]
I've tried it both animated and non-animated. Navigation occurs by traversing rows in each section. The user either clicks on a previous / next button or scrolls though a UICollection view.

```
- (void)emphasiseMarkerAtIndexPath:(NSIndexPath*)indexPath
{
    RMAnnotation *mapAnnotation = nil;

    for (RMAnnotation *annotation in self.mapView.annotations) {

        NSIndexPath *markerIndexPath = (NSIndexPath*) annotation.userInfo;

        if (markerIndexPath.section == indexPath.section && markerIndexPath.row == indexPath.row) {
            annotation.layer.opacity = 1.0;
            mapAnnotation = annotation;
        } else {
            annotation.layer.opacity = 0.75;
        }
    }   
    CGRect mapFrame = [self.view convertRect:self.mapView.bounds fromView:self.mapView];
    CGRect insetMapFrame = CGRectMake(mapFrame.origin.x, mapFrame.origin.y, mapFrame.size.width-15, mapFrame.size.height- heightInset);

    if (![mapAnnotation isAnnotationWithinBounds:insetMapFrame]) {

        NSLog(@"MapView outside bounds");
        [self.mapView setCenterCoordinate:mapAnnotation.coordinate animated:YES];

    }
    [self updateViewButton];
}
```

**Comment by incanus** [comment]
Can you package this in a very discrete sample code package? I've not seen this replicated in past experience -- yours is the only report.

**Comment by rosiematt** [comment]
Hi, I have experienced the same issue.  When I pan away from my custom image RMPointAnnotations and pan back they revert to the standard blue RMPointAnnotation. The RMAnnotations disappear altogether.

See attached images,
![screen shot 2014-05-15 at 10 35 28 pm](https://cloud.githubusercontent.com/assets/220400/2984005/8cb8004e-dc2d-11e3-9854-5d1649b1cd5d.png)
![screen shot 2014-05-15 at 10 35 43 pm](https://cloud.githubusercontent.com/assets/220400/2984006/8f3466c8-dc2d-11e3-880a-7d0842a9c6ab.png)

**Comment by mohpor** [comment]
@rosiematt , My guess is you're gonna have to take a look a your implementation of `RMMapViewDelegate`'s method: 
`-(RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation`
if you have one I mean, my guess is your annotations are weakly linked to markers, but it's just a mere speculation.
Let me know if I could be of any help.
Cheers

**Comment by rosiematt** [comment]
Yep you were spot on. Thanks

**Comment by mohpor** [comment]
Glad to help
