### ISSUE TITLE
Add support for simplestyle markers

### ISSUE THREAD

**Issue by willwhite** [mapbox/DEPRECATED-mapbox-ios-sdk#37]
Just putting a line in the sand that we want to support simplestyle markers as native points on the iPad.

This means:
1. Adding support for reading the URL from the new `data` key from the TileJSON and fetching the GeoJSON.
2. Parsing the GeoJSON and drawing icons according to the [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/blob/master/1.0.0/README.md)

**Comment by incanus** [comment]
This is going on over on https://github.com/mapbox/weekend-picks-template-ios now, closing here. Basic support in `develop` branch.
