### ISSUE TITLE
RMCircle radius drawn double in size

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#371]
Assigned to [MapBox iOS SDK #1808](http://support.mapbox.com/discussions/mapbox-ios-sdk/1808-rmcircle-radius-seems-to-drawn-twice-in-size). As reported in Tender:

<blockquote><p>Hi</p>
<p>I have a couple of areas shown as RMCircle which the user set
the Radius in. I allocate the RMCircle using RadiusInMeters
API.<br>
But having some measurements on Google Earth between two points and
creating a circle between these two points the radius becomes
double the value. Maybe that's better to look into images:</p></blockquote>

**Comment by artysx** [comment]
I'd like to point out something stupid:)

The distance between 2 points is actually an expected diameter of the circle, where the radius is half of it. For some reason I've also expected for RMCircle to accept diameter, without "reading" that it uses radius. 

If you look at second screenshot, radius =  the distance between 2 points with centerCoordinate in the first point.
(pixelRadius \* 4) only makes the visual circle 2x bigger, with the same centerCoordinate, so it kind looks good. 

Proper way to show circle:
1. Find center coordinate between 2 points.
2. Set radius as half of a distance between points.

Am I right?

**Comment by incanus** [comment]
Yes, this sounds right. So this was a misreading and not a bug, it sounds like.
