### ISSUE TITLE
Map not visible after upgrading to 1.1.0

### ISSUE THREAD

**Issue by msealy** [mapbox/DEPRECATED-mapbox-ios-sdk#374]
Just upgraded an existing project from 1.0.3 and the map no longer appears. My center coordinate now reports (0, 0). This all worked correctly in 1.0.3. All that appears is the new attribution.

Since there is no pod available as yet I pointed to the source

pod 'Mapbox', :git => 'https://github.com/mapbox/mapbox-ios-sdk.git'

My map is built via initWithTileJSON but the same occurs if I switch to initWithMapId. 

This all occurs on a fresh install on the simulator and the device.

 Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

**Comment by incanus** [comment]
How are you creating your map view and getting it into the view hierarchy?

**Comment by msealy** [comment]
I use a xib with a subview whose class is defined as a RMMapView. This is the approach that has worked up to 1.0.3.

**Comment by incanus** [comment]
Hmm, ok, this shouldn't have changed. I'm guessing it's something to do with Xcode caching and the MapBox -> Mapbox lowercasing, possibly in the Mapbox.h master header file. Does that shed any light? Maybe try blowing away DerivedData for the project?

**Comment by msealy** [comment]
I blew the derived data away a couple times, clean the solution and restarted Xcode. I also removed the app from the simulator and my device. However, I keep getting the error where the map center is no longer set. Here is a snippet of my tile loading procedure: 

```
NSError* error = nil;
NSString *fullPath = [[NSBundle mainBundle] pathForResource:@"mapbox" ofType:@"json"];
NSString* tileJSON = [NSString stringWithContentsOfFile:fullPath encoding:NSASCIIStringEncoding error:&error];
RMMapBoxSource *tileSource = [[RMMapBoxSource alloc] initWithTileJSON:tileJSON];

DDLogVerbose(@"titlesource: minzoom: %f, maxzoom: %f, centerzoom: %f, cacheable: %d, url: %@, center coordiante long: %f, lat: %f",tileSource.minZoom, tileSource.maxZoom, tileSource.centerZoom, tileSource.cacheable, tileSource.tileJSONURL.absoluteString, tileSource.centerCoordinate.longitude, tileSource.centerCoordinate.latitude);

[tileSource setCacheable:YES];    
[_mapView setTileSource:tileSource];
[_mapView setCenterCoordinate:tileSource.centerCoordinate];    
_mapView.zoom = tileSource.minZoom;
_mapView.minZoom = tileSource.minZoom;
_mapView.maxZoom = tileSource.maxZoom;
_mapView.decelerationMode = RMMapDecelerationFast;
_mapView.adjustTilesForRetinaDisplay = [[UIScreen mainScreen] scale] > 1.0;
[_mapView setShowsUserLocation:YES];

DDLogVerbose(@"map latlong: (%f, %f)", _mapView.centerCoordinate.longitude, _mapView.centerCoordinate.latitude);
CGPoint center = [_mapView coordinateToPixel:_mapView.centerCoordinate];
DDLogVerbose(@"screen center: (%f, %f)", center.x, center.y);
```

   [_mapView setClusteringEnabled:NO];

```
// register delegate
[_mapView setDelegate:handler];
```

**Comment by msealy** [comment]
Still not able to resolve this issue. Here is the crash

2014-01-11 21:05:28.105 Bimoo-Debug[57433:70b] **\* Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [nan nan; nan nan]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x03b045e4 **exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x038838b6 objc_exception_throw + 44
    2   CoreFoundation                      0x03b043bb +[NSException raise:format:] + 139
    3   QuartzCore                          0x020f28cb _ZN2CA5Layer10set_boundsERKNS_4RectEb + 267
    4   QuartzCore                          0x020f2b96 -[CALayer setBounds:] + 135
    5   Bimoo-Debug                         0x0029e19a -[RMCircle updateCirclePathAnimated:] + 1002
    6   Bimoo-Debug                         0x0029dcc7 -[RMCircle initWithView:radiusInMeters:] + 583
    7   Bimoo-Debug                         0x002dd261 -[RMMapView locationManager:didUpdateToLocation:fromLocation:] + 3937
    8   CoreLocation                        0x01349ade CLLocationCoordinate2DGetDistanceFrom + 18534
    9   CoreLocation                        0x0134907e CLLocationCoordinate2DGetDistanceFrom + 15878
    10  CoreLocation                        0x013463ec CLLocationCoordinate2DGetDistanceFrom + 4468
    11  CoreLocation                        0x0133fb90 CLClientInvalidate + 996
    12  CoreFoundation                      0x03ac31c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK** + 16
    13  CoreFoundation                      0x03a8c3f9 __CFRunLoopDoBlocks + 361
    14  CoreFoundation                      0x03aaa843 __CFRunLoopRun + 2355
    15  CoreFoundation                      0x03aa9ac3 CFRunLoopRunSpecific + 467
    16  CoreFoundation                      0x03aa98db CFRunLoopRunInMode + 123
    17  GraphicsServices                    0x0482c9e2 GSEventRunModal + 192
    18  GraphicsServices                    0x0482c809 GSEventRun + 104
    19  UIKit                               0x02335d3b UIApplicationMain + 1225
    20  Bimoo-Debug                         0x00002d4d main + 141
    21  libdyld.dylib                       0x0404570d start + 1
    22  ???                                 0x00000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by msealy** [comment]
Issue resolved. I had to remove the MapView from the xib and initialize it in code.
