### ISSUE TITLE
fix Podspec for 1.1.0

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#377]
See background: 

https://github.com/CocoaPods/Specs/commit/333dac2d52ff9c5dc5171e33d5f0c31deb75e471
https://github.com/CocoaPods/Specs/commit/baeed90c8944148f3d07d7d0b4c766ccd3952961
https://github.com/CocoaPods/Specs/commit/d8a0a05656ef06beab5421d07367f0a52a83339d
https://github.com/CocoaPods/Specs/commit/2af957320fc7d6991fb6ad1f87e0cd80d335a606

See also https://github.com/mapbox/mapbox-ios-sdk/commit/b364fb7c4eb09c309860f8d34e72349ae76b7007#commitcomment-4996858

**Comment by incanus** [comment]
Until such time as this is fixed, you can use this in your `Podfile`: 

```
pod 'Mapbox', :git => 'https://github.com/mapbox/mapbox-ios-sdk', :tag => '1.1.0'
```

Similarly you could use `:branch => 'develop'` etc. in place of `:tag...`.

**Comment by incanus** [comment]
http://support.mapbox.com/discussions/mapbox-ios-sdk/3046-unable-to-find-a-specification-for-mapbox

**Comment by incanus** [comment]
https://groups.google.com/forum/#!topic/cocoapods/bKz4oIK7VJg

**Comment by ghost** [comment]
hi, i still geting this error

Undefined symbols for architecture i386:
  "_pj_free", referenced from:
      -[RMProjection dealloc] in libPods.a(RMProjection.o)
  "_pj_fwd", referenced from:
      -[RMProjection coordinateToProjectedPoint:] in libPods.a(RMProjection.o)
  "_pj_init_plus", referenced from:
      -[RMProjection initWithString:inBounds:] in libPods.a(RMProjection.o)
  "_pj_inv", referenced from:
      -[RMProjection projectedPointToCoordinate:] in libPods.a(RMProjection.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

after adding Lib4 project manually to workspace it works fine, but it's shouldn't be like that.

**Comment by incanus** [comment]
@cwir8 you should not be seeing this with `1.1.0`. Could you paste the output of `file Pods/MapBox/Proj4/libProj4.a`?

**Comment by gacover** [comment]
@incanus I am getting the same error. (42 compile errors)

```
Undefined symbols for architecture armv7s:
  "_pj_inv", referenced from:
      -[RMProjection projectedPointToCoordinate:] in libPods.a(RMProjection.o)
  "_inflate", referenced from:
      -[NSData(RMInteractiveSource) gzipInflate] in libPods.a(RMInteractiveSource.o)
  "_inflateEnd", referenced from:
      -[NSData(RMInteractiveSource) gzipInflate] in libPods.a(RMInteractiveSource.o)
  "_pj_free", referenced from:
      -[RMProjection dealloc] in libPods.a(RMProjection.o)
  "_sqlite3_column_type", referenced from:
      -[FMResultSet stringForColumnIndex:] in libPods.a(FMResultSet.o)
      -[FMResultSet dateForColumnIndex:] in libPods.a(FMResultSet.o)
      -[FMResultSet dataForColumnIndex:] in libPods.a(FMResultSet.o)
      -[FMResultSet dataNoCopyForColumnIndex:] in libPods.a(FMResultSet.o)
      -[FMResultSet columnIndexIsNull:] in libPods.a(FMResultSet.o)
      -[FMResultSet UTF8StringForColumnIndex:] in libPods.a(FMResultSet.o)
      -[FMResultSet objectForColumnIndex:] in libPods.a(FMResultSet.o)

```

This is what my Podfile looks like

```
platform :ios, 6.0
pod 'RestKit', '~> 0.20.0'
pod 'RestKit/Testing', '~> 0.20.0rc'
pod 'MWPhotoBrowser', '~> 1.0.1'
pod 'WSAssetPickerController'
pod 'TSMessages'
pod 'MapBox'
```

It installs 1.1.0 

Installing MapBox (1.1.0)

Here is the result of "file" command -

```
file Pods/MapBox/Proj4/libProj4.a
Pods/MapBox/Proj4/libProj4.a: Mach-O universal binary with 5 architectures
Pods/MapBox/Proj4/libProj4.a (for architecture armv7):  current ar archive random library
Pods/MapBox/Proj4/libProj4.a (for architecture armv7s): current ar archive random library
Pods/MapBox/Proj4/libProj4.a (for architecture i386):   current ar archive random library
Pods/MapBox/Proj4/libProj4.a (for architecture x86_64): current ar archive random library
Pods/MapBox/Proj4/libProj4.a (for architecture cputype (16777228) cpusubtype (0)):  current ar archive random library
```

Appreciate your response

**Comment by ghost** [comment]
Hi, 
I just created new project and install it again and that worked for me.

## 

Przemek Skowronek
Sent with Airmail
On 26 marca 2014 at 23:14:53, gacover (notifications@github.com) wrote:
@incanus I am getting the same error with this Podfile.
platform :ios, 6.0
pod 'RestKit', '~> 0.20.0'
pod 'RestKit/Testing', '~> 0.20.0rc'
pod 'MWPhotoBrowser', '~> 1.0.1'
pod 'WSAssetPickerController'
pod 'TSMessages'
pod 'MapBox'
Here is the result of "file" command -
```file Pods/MapBox/Proj4/libProj4.a Pods/MapBox/Proj4/libProj4.a: Mach-O universal binary with 5 architectures Pods/MapBox/Proj4/libProj4.a (for architecture armv7): current ar archive random library Pods/MapBox/Proj4/libProj4.a (for architecture armv7s): current ar archive random library Pods/MapBox/Proj4/libProj4.a (for architecture i386): current ar archive random library Pods/MapBox/Proj4/libProj4.a (for architecture x86_64): current ar archive random library Pods/MapBox/Proj4/libProj4.a (for architecture cputype (16777228) cpusubtype (0)): current ar archive random library
Appreciate your response
— Reply to this email directly or view it on GitHub.￼

**Comment by gacover** [comment]
hey @cwir8 i cant discard my existing project.. plus it should work .. cocoapods works like a charm for all other apis i have

**Comment by ghost** [comment]
I forget to tell you that.
I just downloaded that library and imported it to my main project as another project. Not so elegant, but it worked too.

I downloaded it from here, but i dont remember for sure -  https://github.com/bdon/popos-iOS/tree/master/MapBox-iOS-SDK/Proj4

## 

Przemek Skowronek
Sent with Airmail
On 27 marca 2014 at 00:01:05, gacover (notifications@github.com) wrote:
hey @cwir8 i cant discard my existing project.. plus it should work .. cocoapods works like a charm for all other apis i have
— Reply to this email directly or view it on GitHub.￼

**Comment by gacover** [comment]
I already have that library in my pods folder (Pods/MapBox/Proj4) - 

It does link if i add this lib manually.. thanks for the tip.. i also had to add 3 other ios libraries in the project settings.

Thx for the tip @cwir8 !!

**Comment by sachin1212** [comment]
Hi Justin.
I am just getting the same errors like  while using cocoa pods to add the mapbox sdk into my project:

"_pj_inv", referenced from:
      -[RMProjection projectedPointToCoordinate:] in libPods.a(RMProjection.o)
  "_inflate", referenced from:
      -[NSData(RMInteractiveSource) gzipInflate] in libPods.a(RMInteractiveSource.o)
  "_inflateEnd", referenced from:
      -[NSData(RMInteractiveSource) gzipInflate] in libPods.a(RMInteractiveSource.o)
  "_pj_free", referenced from:
      -[RMProjection dealloc] in libPods.a(RMProjection.o) "

I am using my podfile with the code as below:

{
platform :ios, '5.0'
pod 'Mapbox', :git => 'https://github.com/mapbox/mapbox-ios-sdk', :tag => '1.1.0'

}

I  have tried the solutions as told by "cwir8 " but still unable to remove the above errors which come up when  i compile the code in the project.
i read above that these errors should not come up while using the 1.1.0 version but still they come up.
What steps to perform now to remove these errors.

**Comment by rgallagher27** [comment]
SI there any new info/progress on this, I'm trying to add MapBox to a current project but getting the errors described above when using cocoapods

**Comment by incanus** [comment]
Supplanted by pod `Mapbox-iOS-SDK` for `1.2.0` and beyond.

**Comment by rsenerol** [comment]
Hi,

I'm trying to install Mapbox by pod: 

pod 'Mapbox-iOS-SDK', :git => 'https://github.com/mapbox/mapbox-ios-sdk'

Everything seems to work great when I exec pod install command:

Analyzing dependencies
Pre-downloading: `Mapbox-iOS-SDK` from `https://github.com/mapbox/mapbox-ios-sdk`
Downloading dependencies
Using CSStickyHeaderFlowLayout (0.2.1)
Installing FMDB (2.3)
Installing GRMustache (6.8.3)
Installing JRSwizzle (1.0)
Installing Mapbox-iOS-SDK (1.3.0)
Installing SMCalloutView (2.0)
Generating Pods project
Integrating client project

However, I still get the same errors described above:

Undefined symbols for architecture armv7:
  "_pj_inv", referenced from:
      -[RMProjection projectedPointToCoordinate:] in libPods.a(RMProjection.o)
  "_pj_free", referenced from:
      -[RMProjection dealloc] in libPods.a(RMProjection.o)
  "_pj_fwd", referenced from:
      -[RMProjection coordinateToProjectedPoint:] in libPods.a(RMProjection.o)
  "_pj_init_plus", referenced from:
      -[RMProjection initWithString:inBounds:] in libPods.a(RMProjection.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm not sure what to do no.... :(

**Comment by incanus** [comment]
@rsenerol Are you sure you're on the latest version of CocoaPods? I have `0.33.1` and I just tested things out both with the stable CocoaPods as well as the repository directly across iOS 6 and 7 without issue.

**Comment by rsenerol** [comment]
@incanus, 

I just executed the command 'pod --version' and I have the latest version too (0.33.1). I also tried to delete the Pod directory, install again everything but I still get the errors. 

Do all the libs linked with MapBox (FMDB, GRMustache, etc.) support x64? Do I have to setup something specific in my project settings? 

FYI, I had a version of MapBox (dev branch) working before, using "MapBox" pod. Then I wanted to update the library using pod 'Mapbox-iOS-SDK'. But unfortunately, I'm not able to compile anymore.

**Comment by incanus** [comment]
Are you deploying down to iOS 5 by chance? 

The three libs (FMDB, GRMustache, and SMCalloutView) all support 64-bit. When Mapbox is built, it uses the already-compiled `libProj4` just like our non-CocoaPods install methods do: 

https://github.com/mapbox/mapbox-ios-sdk/blob/release/Proj4/libProj4.a

But that is provided as a fat binary already: 

``` bash
lipo -info libProj4.a
Architectures in the fat file: ./Pods/Mapbox-iOS-SDK/Proj4/libProj4.a are: armv7 armv7s i386 x86_64 arm64 
```

When I built for 32-bit simulator, I can check the `libPods.a` product: 

``` bash
lipo -info .../Build/Products/Debug-iphonesimulator/libPods.a
input file .../Build/Products/Debug-iphonesimulator/libPods.a is not a fat file
Non-fat file: .../Build/Products/Debug-iphonesimulator/libPods.a is architecture: i386
```

But same for 64-bit: 

``` bash
lipo -info .../Build/Products/Debug-iphonesimulator/libPods.a
input file .../Build/Products/Debug-iphonesimulator/libPods.a is not a fat file
Non-fat file: .../Build/Products/Debug-iphonesimulator/libPods.a is architecture: x86_64
```

So I'm just not seeing architecture problems here. Can you maybe zip up a project and send it in to support@mapbox.com?

**Comment by rsenerol** [comment]
I tried with a new project and I was able to build it without any problems so there is something wrong with my project's settings and not with MapBox pod. I'm gonna compare the two projects settings and see if I can find something. 

Since it's a problem on my side, I guess there is no need to reopen the issue. I'll post the answer anyway in case if someone has the same problem.

**Comment by ansinyutin** [comment]
I had the same error, fixed by installing proj4 pod

**Comment by MapaX** [comment]
I encountered same problem. The problem was that the old project has copied proj4.a to build directory. Cleaning project does not remove the files in the build directory so there was older version of proj4.a library which was then used when app was compiled.
I removed old files from directory and now everything works just fine :)
