### ISSUE TITLE
Animating adding and removing of Point Annotation

### ISSUE THREAD

**Issue by samjarman** [mapbox/DEPRECATED-mapbox-ios-sdk#379]
Is there, or will there be a way to animate like with a pulse, bounce, zoom, drop etc in of Point annotations? 

I would expect something like `[self.myMapView addAnnotation:pointAnno animated:YES];`

Cheers :)

**Comment by incanus** [comment]
@samjarman There aren't hard plans to add this right now. You could do this yourself by: 
1. Adding your `RMAnnotation` objects. 
2. Having the delegate return `nil` for their layers. 
3. Animating in the images in question in a layer/view above the map. 
4. Upon completion, removing the added layer/view and beginning to return non-`nil` for the actual annotation layers. 

For now, this is out of scope since you'd have to manually animated non-pins with MapKit, too, so it's not a generally-provided feature.

**Comment by abhay-agarwal** [comment]
Hi @incanus,

I'm confused by the solution you presented here. There's already a default animation for RMMarkers, so wouldn't step 4 result in that same default animation happening (after the custom one I created)? I think what would help me is an outline of where in the mapbox code the 'swoop in' animation of markers is actually coded, and my team can make changes in our fork to support our preferred animation.

**Comment by haashem** [comment]
would you clarify more for the solution?
when I add layer `- (RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation` I can animate the layer. but for removing RMAnnotation, `- (void)mapView:(RMMapView *)mapView willHideLayerForAnnotation:(RMAnnotation *)annotation` annotation layer suddenly be nil and I can not animate it.

**Comment by incanus** [comment]
@hashemp206 I would recommend maybe creating a new view/layer whose `contents` are copied from the annotation layer's before you remove it, and then animating that copy.

**Comment by haashem** [comment]
ok I did that I add that layer to mapView.layer but strange is here when I add this new layer, the new layer is just added to the view, I mean layer won't scroll with map it just pasted on the screen! do you have time to make a try?

now the solution for me was modifying the SDK and comment the  line number 3020 RMMapView and move it to the delegate method!

I don't like this solution but thats the only thing I can do right now!

**Comment by haashem** [comment]
I want animate cluster annotation layer when they created and disappeared. (an small spring animation)
but the problem I encounter here is with every drag of mapView my custom cluster marker gets created  `- (RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation`
I check in above method use this criteria `if(annotation.isClusterAnnotation && !annotation.isAnnotationVisibleOnScreen)` I see with every drag `cluster annotation layer` gets nil.

why with every pan and drag on map, cluster layer gets nil? (clustering is enabled)

**Comment by haashem** [comment]
I want to create spreadIn and spreadOut annotations when user zoom in or zoom out on the map. I need to keep a reference of annotation parent in the RMAnnotation (I just added a new property named parent cluster to the annotation class). where the annotations which reside in one cluster have same parent.

I want to do something like this: 
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/

where should I add parent reference to the annotation?
how can I achieve animation above? I need to move annotation from parent location to its original location.
