### ISSUE TITLE
refactor tile compositing

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#38]
Now that `RMComposite` source is stable, we should think about refactoring it along the lines of the [upstream issue](https://github.com/Alpstein/route-me/issues/47), layering tiled layers instead of actually compositing tile images into one layer. 

See also https://github.com/incanus/TileTest

**Comment by incanus** [comment]
`RMCompositeSource` was never submitted to upstream in anticipation of this, upstream performed this refactor, and `RMCompositeSource` is now gone in `develop-refactor`, which will soon be moved to `develop`. Closing here.

**Comment by chh51** [comment]
Makes sense, looking forward to the refactored version.
