### ISSUE TITLE
MKGeodesicPolyline equivalent for MapBox

### ISSUE THREAD

**Issue by jeffbailey** [mapbox/DEPRECATED-mapbox-ios-sdk#385]
A great feature enhancement would be to support an equivalent to the MKGeodesicPolyline for MapBox.  My use case would be to support a more realistic flight path between two airports.  Has anyone created a custom annotation for this?

**Comment by incanus** [comment]
Check out this branch: https://github.com/mapbox/mapbox-ios-sdk/tree/great-circles and `RMGreatCircleAnnotation`.

**Comment by incanus** [comment]
Dupe of https://github.com/mapbox/mapbox-ios-sdk/pull/303 which will eventually get merged.

**Comment by jeffbailey** [comment]
Works great!  Thanks for the help.
