### ISSUE TITLE
There is no way to setup a RMMapView created with a storyboard in 1.1.0

### ISSUE THREAD

**Issue by sumerman** [mapbox/DEPRECATED-mapbox-ios-sdk#386]
`RMMapView` placement with a storyboard works well, but currently there is no way to set a tile source. RMMapView created with a storyboard is mostly uninitialized during the `viewDidLoad`, therefore the `tileSource`, the `tileSources` and other related container fields are nil.
I presume this late initialisation issue could be fixed by adding `mapViewIsReady` method to the delegate protocol which is supposed to be called by a `RMMapView` instance after all the setup is done.

**Comment by jkd359** [comment]
If i'm reading this comment right, have you tried setTileSource? mapView is just a UIView (RMMapView).

```
RMMapBoxSource *tilesource = [[RMMapBoxSource alloc] initWithMapID:kMapID];

[mapView setTileSource:tilesource];
```

**Comment by sumerman** [comment]
@jkd359 of course I've tried, but it ends up reassigned to the default values. If you somehow manage to call this custom initialization code after the `RMMapView` is done with it's own preparations, the code will do the job, but currently there is no way to do so (besides binding the call to a buttton or a timer, both are inappropriate in a real app).

**Comment by incanus** [comment]
This relates to possible re-architecting as described in #286. 

But you're right that at present, you can't do this. Unfortunately you can't extend much in the way of outlets beyond `delegate` and IB plugins are a sad road to tread. 

Will see about hitting this with #286.

**Comment by RyanCopley** [comment]
#387 

This is exactly what I was talking about, you need to apply my patch (or rewrite it to your liking) to fix this.

@sumerman - I forked and fixed this issue. You can find it in the issue I wrote above.

**Comment by incanus** [comment]
I think short of a large reorganization, there is not a good pathway to do this now. It's just difficult to set arbitrary properties for anything in XIB aside from delegates and things advertised as outlets.

**Comment by sumerman** [comment]
@incanus but it's very handy to layout views via XIB, so please, do not ignore this possibility.

**Comment by paulthorsteinson** [comment]
@incanus its nice to do this so you can do all your autolayout in the storyboard or xib.  From an API perspective it doesn't make sense to have a tilesource property that is read/write but that fails based on how it was instantiated.  You set the property to X and the property value after setting is nil.....

**Comment by incanus** [comment]
Give the above branch a try and let me know if it works better for you? Finally thought of a way to fix this.

**Comment by incanus** [comment]
I've merged `early-tilesource-init` into `develop`; gonna close this out.

**Comment by paulthorsteinson** [comment]
Thanks @incanus
