### ISSUE TITLE
Exception raises when mbtiles file is not in the main bundle

### ISSUE THREAD

**Issue by andreacremaschi** [mapbox/DEPRECATED-mapbox-ios-sdk#39]
RMMBTilesSource: there is an issue when .mbtiles file is not in the app's main bundle: FMDatabaseQueue will throw an exception: "Could not create database queue for path map.mbtiles".

I fixed this just modifying RMMBTilesSource.m:

```
queue = [[FMDatabaseQueue databaseQueueWithPath:[tileSetURL relativePath]] retain];
```

with:

```
queue = [[FMDatabaseQueue databaseQueueWithPath:[tileSetURL path]] retain];
```

**Comment by incanus** [comment]
Closed in favor of #43.
