### ISSUE TITLE
layerForAnnotation not being called. Other delegate methods gets called.

### ISSUE THREAD

**Issue by maqen** [mapbox/DEPRECATED-mapbox-ios-sdk#394]
`layerForAnnotation` not being called.

Other delegate methods are being called like `- (void)tapOnAnnotation:(RMAnnotation *)annotation onMap:(RMMapView *)map` and `- (void)beforeMapMove:(RMMapView *)map byUser:(BOOL)wasUserAction``

```
_mapView = [[RMMapView alloc] initWithFrame:self.view.bounds andTilesource:tileSource];
[_mapView removeAllCachedImages];
_mapView.delegate = self;
_mapView.zoom = 13;
_mapView.centerCoordinate = CLLocationCoordinate2DMake(59.305, 18.102);

[self.view insertSubview:_mapView atIndex:0];

RMPointAnnotation *annotation = [[RMPointAnnotation alloc] initWithMapView:_mapView coordinate:_mapView.centerCoordinate andTitle:nil];
[_mapView addAnnotation:annotation];
```

But calls to `- (RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation` don't go through and I get a standard (blue) icon on my map.

Any tips on solving this?
- cocoapods 1.1.0
- Xcode 5.0.2
- Targeting iOS 7.0

**Comment by maqen** [comment]
Sorry my bad see I'm using `RMPointAnnotation` switching to `RMAnnotation` solved my issues.

**Comment by gabrielafonsogoncalves** [comment]
good
