### ISSUE TITLE
Removing tile caches from within the same tile source

### ISSUE THREAD

**Issue by eibenm** [mapbox/DEPRECATED-mapbox-ios-sdk#399]
I have a question about the caching methods available in RMDatabaseCache.  I'm currently using the RMTileCacheBackgroundDelegate methods with `- (void)removeAllCachedImagesForCacheKey:(NSString *)cacheKey` to selectively remove and add caches from different tile sources outside of the actual map page.  This method seems to work great assuming the tiles you want to delete are in different sources since the ID seems to be used for the cacheKey.

Example:

``` Objective-C
NSString *strFileURL = [[NSBundle mainBundle] pathForResource:@"overviewMap" ofType:@"json"];
NSError *error;
NSString *jSONTileStr = [NSString stringWithContentsOfFile:strFileURL encoding:NSUTF8StringEncoding error:&error];
overviewMapSource = [[RMMapboxSource alloc] initWithTileJSON:jSONTileStr];

overviewMapCache = [[RMTileCache alloc] initWithExpiryPeriod:0];
[overviewMapCache setBackgroundCacheDelegate:self];

CLLocationCoordinate2D theSouthWest = CLLocationCoordinate2DMake(44.677746, -112.180931);
CLLocationCoordinate2D theNorthEast = CLLocationCoordinate2DMake(46.423813, -109.924179);
[overviewMapCache beginBackgroundCacheForTileSource:overviewMapSource southWest:theSouthWest northEast:theNorthEast minZoom:8.5 maxZoom:10];
NSLog(@"caching = %d", overviewMapCache.isBackgroundCaching);

/* --- to be used once the caching has finished and the user wants to remove this cache --- */
[overviewMapCache removeAllCachedImagesForCacheKey:@"Mapbox-accountName.mapID"];
```

My question is this:
Is there currently a method or way to selectively add and, more importantly, remove different bounded tile caches from within the same tile source?  If I use the above method, the cacheKey would remove ALL cached bounding boxes within that tile source.  I'm hoping to have the user elect to cache or remove caches within a single tile source at will.  Any help would be appreciated!

Thanks for all the great existing caching methods!  They're way ahead of anything else I've seen.  :)

Matt

**Comment by incanus** [comment]
> Is there currently a method or way to selectively add and, more importantly, remove different bounded tile caches from within the same tile source? If

No, currently this is tile source-wide. We are open to patches, though -- just a matter of good API and the right SQLite queries on the backend. 

> Thanks for all the great existing caching methods! They're way ahead of anything else I've seen. :)

Thanks for the kind words :smile:
