### ISSUE TITLE
Issue with the new tracking feature in release branch

### ISSUE THREAD

**Issue by andreacremaschi** [mapbox/DEPRECATED-mapbox-ios-sdk#40]
Location tracking (with userTrackingMode set to RMUserTrackingModeFollowWithHeading) is acting weird with my configuration.
Tracking is wrong by 90°, and annotation layer don't rotate following compass heding. Furthermore, sometime gps accuracy circle is not centered with gps user position (actually, it slides away to another location of the map).

Are they known issues?

**Comment by incanus** [comment]
HI @andreacremaschi. Covering each: 
- Haven't seen the 90 degree issue before. Can you reliably replicate it? 
- Annotations now rotate per #50. 
- I have very rarely seen the accuracy circle centering issue. Any advice for reliably reproducing it?

**Comment by andreacremaschi** [comment]
Hi @incanus,

I updated my working copy and tried to activate again the location feature. 
- the 90 degrees issue seems fixed now.
- annotations rotates correctly (cool!).
- the accuracy circle centering issue is still there. Apparently it is due to RMMapView being embedded in a UINavigationController. To reproduce it, open SimpleMap and replace applicationDidFinishLaunching with this:

``` Objective-C
- (void)applicationDidFinishLaunching:(UIApplication *)application
{
    // Override point for customization after app launch
    UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:viewController];
    [window addSubview: navController.view];
    [window makeKeyAndVisible];
}
```

ciao
a.

**Comment by incanus** [comment]
See also #55.

**Comment by incanus** [comment]
Please check `develop` and let me know if you still see this. I'm not sure it was related to a `UINavigationController`, but I definitely just fixed an issue related to device rotation.

**Comment by andreacremaschi** [comment]
Fixed for me!
