### ISSUE TITLE
Exclude RMDatabaseCache file from iCloud backup

### ISSUE THREAD

**Issue by namannik** [mapbox/DEPRECATED-mapbox-ios-sdk#402]
My app was rejected by Apple because the RMDatabaseCache file was being automatically backed up to iCloud.  This file needs to be excluded from iCloud backup.  My solution was to add this line just before the end of `- (id)initWithDatabase:(NSString *)path`:

```
[[NSURL.alloc initFileURLWithPath:path] setResourceValue:@(YES) forKey:NSURLIsExcludedFromBackupKey error:nil];
```

**Comment by mhaleem** [comment]
May i know why we closed this issue and the problem not solved yet? my App was rejected also today because of that.

**Comment by namannik** [comment]
This issue has been discussed here:

https://github.com/mapbox/mapbox-ios-sdk/pull/410

That issue is still open, but it doesn't look like there's been any movement in a while.
