### ISSUE TITLE
The version of GRMustache is highly out of date

### ISSUE THREAD

**Issue by RyanCopley** [mapbox/DEPRECATED-mapbox-ios-sdk#407]
The version of GRMustache used is 5.4.3, which is a year old. v6.9.1 is available and it fixes some warnings and potential crashes.

I took a quick peak and I noticed the only real usage of GRMustache is in RMInteractiveSource.m at around line 270, with 3 references to it. Would it be possible to have it updated to the latest version? v5 isn't maintained anymore and it causes nasty warnings to be thrown.

**Comment by incanus** [comment]
Are you using our `1.1.0`? This was updated in order to get 64-bit compatibility once that came out. https://github.com/mapbox/mapbox-ios-sdk/commit/6adfc4135acb9d459284f87b2f084636e8772d6a

**Comment by RyanCopley** [comment]
> pod install
> Downloading dependencies
> Installing AFNetworking (2.1.0)
> Installing CocoaLumberjack (1.8.0)
> Installing FMDB (2.0)
> Installing GRMustache (5.4.3)
> Installing JRSwizzle (1.0)
> Installing MBProgressHUD (0.8)
> Installing MapBox (1.1.0)
> Installing NYXImagesKit (2.3)
> Installing RCActiveRecord (1.0.0)
> Installing SAMCategories (0.4.0)
> Installing SMCalloutView (1.1)
> Installing SSKeychain (1.2.1)
> Installing SWTableViewCell (0.2.3)
> Installing XMLReader-Arc (1.1)

MapBox is 1.1.0 and GRMustache is 5.4.3. 

https://github.com/mapbox/mapbox-ios-sdk/blob/release/Mapbox.podspec#L82
Indicates that it should install GRMustache 5.4.3. You updated the submodule but not the podspec.

Also, if you don't mind, please don't close issues after you ask a question...

**Comment by incanus** [comment]
Sorry, you are right. I remembered a major version jump, but it must have been from 4 to 5. I will check this out. I don't recall why I wouldn't have gone with 6 if it was available then, but it seems odd to me that 5 would be deprecated already. 

Re: closing, I had assumed it was answered, and wrongly. Sorry about that.

**Comment by RyanCopley** [comment]
I went ahead and changed it and sent a pull request

**Comment by incanus** [comment]
Ah, I see, I did go from 5 to 6, but not in the podspec. Thanks for your PR; merged at https://github.com/mapbox/mapbox-ios-sdk/pull/408 into both `release` and `develop`.

**Comment by bleft** [comment]
Please have a look at this again. Current version of  GRMustache is 7.3.0 and will fix some warnings.

**Comment by imrmaximus** [comment]
Hi,
Please, can you update the GRMustache dependency with the last version of GRMustache ?
There is a fix in the 7.3.1 which i need in the swift framework installation.
Thank's a lot :)

**Comment by friedbunny** [comment]
@imrmaximus This SDK has been deprecated in favor of [our vector SDK](https://www.mapbox.com/ios-sdk/) and won’t be receiving any official updates. As with any open source project, feel free to fork this repo (or use someone else’s fork) and do as you please.

**Comment by imrmaximus** [comment]
Thank you so much @friedbunny to reply so quickly.
I have an little issue now.
So, i fork it, i try to make a private cocoa pods repo but, and, when i push the podspec, i have this error:
ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

I have no other error.
Maybe it is not linked, but i have this note too (which is like an error):
[iOS] xcodebuild:  error: Resource "/Users/maximeavon/Library/Developer/Xcode/DerivedData/App-bcyzbxvqpcaffmfvcrktcjrumlgn/Build/Products/Release-iphonesimulator/Mapbox.bundle" not found. Run 'pod install' to update the copy resources script.

Have you any how to solve it?
