### ISSUE TITLE
RMMarker Shake on zoom level 18+

### ISSUE THREAD

**Issue by afnanahmad** [mapbox/DEPRECATED-mapbox-ios-sdk#409]
I'm having a very unpleasant behaviour while viewing map on zoom level 18+. Is there any way I can fix this issue?

Any help would be appreciated.

P.S. I've attached gif for that screen.

![map](https://f.cloud.github.com/assets/2064669/2279747/e946f0d8-9f77-11e3-95fa-e3ccf65d1fa1.gif)

**Comment by incanus** [comment]
This is a dupe of #72. There are some tips that might work for you there, but otherwise this is a result of float precision in Apple's underlying technology. We're working on a new renderer to address this.
