### ISSUE TITLE
Higher res screenshots of SDK examples

### ISSUE THREAD

**Issue by tristen** [mapbox/DEPRECATED-mapbox-ios-sdk#411]
I'd like to use a few sweet looking screenshots for a splash page. It would be great to get a few higher res images of examples with the more recent iOS7 UI in the images directory of my [working branch](https://github.com/mapbox/mapbox-ios-sdk/tree/docq).

cc/ @incanus

**Comment by incanus** [comment]
Handling these in #413 pull request.
