### ISSUE TITLE
RMStaticMapView is always returning images from example map

### ISSUE THREAD

**Issue by ciudadlas** [mapbox/DEPRECATED-mapbox-ios-sdk#412]
I viewed the source code and "(void)performInitializationWithMapID:(NSString *)mapID centerCoordinate:(CLLocationCoordinate2D)centerCoordinate zoomLevel:(CGFloat)zoomLevel completionHandler:(void (^)(UIImage *))handler" always uses the default example map ID and not the passed mapID

**Comment by incanus** [comment]
This was fixed in `develop` as of https://github.com/mapbox/mapbox-ios-sdk/commit/1a46f0f92a606853072c20c230cf7629b0626201 and should be in a release soon.
