### ISSUE TITLE
RMProjectedRect - Bounding box of a polygon

### ISSUE THREAD

**Issue by mahadevans87** [mapbox/DEPRECATED-mapbox-ios-sdk#415]
Is it possible to pass in an array of CLLocationCoordinate2D and get a bounding box of the polygon formed as a RMProjectedRect?

**Comment by incanus** [comment]
There isn't currently, but you could adapt this: https://github.com/mapbox/mapbox-ios-sdk/blob/3223e01e0092ada7c32bf1df8f091b4b6e5f3972/MapView/Map/RMAnnotation.m#L210-L234
