### ISSUE TITLE
Api to find if 2 points cross the mercator border

### ISSUE THREAD

**Issue by mahadevans87** [mapbox/DEPRECATED-mapbox-ios-sdk#417]
Consider the imaginary country of Boxtopia, which has a southwest corner at (170, 40) and a northeast corner at (-170, 50). The width of this box is 20 degrees. In a spatial database, Boxtopia would be represented by two rectangles, one which has a southwest corner at (170, 40) and a northeast corner at (180, 50) and a second that has a southwest corner at (-180, 40) and a northeast corner at (-170, 50). This split is required because the longitude must be between -180 and 180 degrees.

Since the bounding box is a single feature that extends from the minimum to the maximum longitude and latitude values, the bounding box for Boxtopia has a southwest corner at (-180,40) and a northeast corner (180,50). This bounding box has a width of 360 degrees, rather than 20 degrees, exaggerating by eighteen times the width of the Boxtopia.

How can we use Route-Me to create the bounds for the country to handle the above problem?

Is there anyway to find out 2 points cross the mercator border? (-180,0) (180,0) point.

**Comment by incanus** [comment]
There isn't an API for this in the SDK, and it's not specific to this project, but you might dig into https://github.com/mapbox/mapbox-ios-sdk/blob/great-circles/MapView/Map/RMGreatCircleAnnotation.m for some ideas for this.
