### ISSUE TITLE
takeSnapshot when compile for arm64

### ISSUE THREAD

**Issue by mohpor** [mapbox/DEPRECATED-mapbox-ios-sdk#418]
When using `takeSnapshot` in **arm64** strange things happen:
1- I'll get constant assertions that my zoom level is less than minZoom: Checked the method urlForTile and the tile parameter has zoom value of -1 and x,y pair seems to be an overflown values (max values for their variable containers)
2- I have followed the code down to `RMMapTiledLayerView` and found out that in `drawLayer:inContext:` `self.useSnapshotRenderer` is true in takeSnapshot mode and it uses floor method and `x1,x2,y1,y2` get overflown in that method. any idea how to mitigate this problem now?
I'm out of luck using the snapshot in arm64!
P.S.: I'm using takeSnapshot as part of my custom static map view

**Comment by incanus** [comment]
I am not able to reproduce this on either 64-bit simulator or an iPhone 5s using the `develop` branch. Are you still seeing this?

**Comment by mohpor** [comment]
I have changed my project's setting to exclude arm64 arch from being compiled, so, I'm going to have to check on that.

**Comment by mohpor** [comment]
As I've mentioned before I'm trying to implement a new subclass for my own static map view. current static map view uses MapBox as tile source however, I want a static map from my own TMS server. and it leads to error on takeSnapshot method in arm64 arch.

**Comment by mohpor** [comment]
I have checked again. It seems that the problem shifted from what I was experiencing to a long delay and no results. so to sum it up, yep, still got problems but in another form.

**Comment by incanus** [comment]
Ok, to make sure I'm understanding: you have subclassed `RMStaticMapView` and are seeing the problem with that? Could you share your code? (private is ok; let me know and we can set something up off of GitHub).

**Comment by mohpor** [comment]
Well, noI'm not subclassing RMStaticMapView, bur RMAbstractWeb...

I'll share my code tomorrow. It's not that private for me.
—
