### ISSUE TITLE
API placeholder page

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#420]
Related to #413, we should get a page back up at `/api` that says that the docs are in Xcode (where they've always been). We've gotten quite a few complaints about it, including support. In retrospect, we probably shouldn't have just yanked the HTML-based page. I will add a page that tells people the canonical source for the docs. 

/cc @tristen @yhahn

**Comment by tristen** [comment]
Currently https://www.mapbox.com/mapbox-ios-sdk/api redirects to https://www.mapbox.com/mapbox-ios-sdk/#api_overview I think the copy could be a bit clearer and highlighted?

**Comment by incanus** [comment]
Ok, this can stay as is. I changed the wording slightly, but the current redirect is enough.
