### ISSUE TITLE
Zoom and Pan is terrible when SMCallout is showing on map

### ISSUE THREAD

**Issue by mohpor** [mapbox/DEPRECATED-mapbox-ios-sdk#421]
With the latest update on develop branch I'm experiencing very bad lags on map zooming and panning when an annotation's callout is visible, and I mean horrible lags not something minor.

**Comment by incanus** [comment]
Hmm, got a sense of what commit it might be? I'll check this out, too.

**Comment by mohpor** [comment]
Can you reproduce the issue too? I think the new SMCalloutView's the culprit. I had no time for checking it further. Let me know of you needed a hand.—

**Comment by mohpor** [comment]
OK, sorry, pan has no problem but zoom is laggy. To be more clear, when i try to zoom using pinch gesture, it lags but zooming to absolute zoom values via my zoom slider appears to have no trouble at all. So, to sum it up, zooming in and out via gestures have problem, other methods have no problem.

**Comment by incanus** [comment]
Yep, seeing this and it's probably related to the SMCalloutView bump. Will investigate.

**Comment by incanus** [comment]
I made a small fix above that was a bug which caused this lag for all annotations, when it should only be happening for non-points. So at least points are better. Still working through solving the underlying lag, though.

**Comment by incanus** [comment]
Callouts on non-markers (i.e. shapes) isn't something we want to dive into to fix anymore, so I removed that functionality. We're all set here.
