### ISSUE TITLE
Navigation controller + MapView -> crash on iOS6/7 (release & develop branches)

### ISSUE THREAD

**Issue by mkutgt72** [mapbox/DEPRECATED-mapbox-ios-sdk#432]
Example project:  https://github.com/mkutgt72/MapBugTest.git

develop - https://github.com/mapbox/mapbox-ios-sdk/commit/cda3185d693e3652864f8fbf80f1c4bf4686a386

iOS6 release: crash
iOS7 release: crash

iOS6 develop: crash
iOS7 develop: OK

Steps to reproduce:
1) click back button

looks like: https://github.com/mapbox/mapbox-ios-sdk/issues/425

**Comment by incanus** [comment]
If this looks like #425 let's just defer to that one.
