### ISSUE TITLE
Tile sources seem to block eachother

### ISSUE THREAD

**Issue by datwelk** [mapbox/DEPRECATED-mapbox-ios-sdk#433]
I am trying to use an `RMMapView` instance with two different tile sources. In order to achieve this, before the `RMMapView` instance is added to the view hierarchy, I set its `tileSources` property to an array containing the two tile sources. 

Both tile sources derive from `RMAbstractWebMapSource`. One of the sources requires a VPN to be setup. If this VPN is not set up, the tiles corresponding to this source will of course not reach the app.

The thing is that it seems as if this VPN-dependent tile source, if the VPN is not set up, is preventing the `RMMapView` instance from loading tiles from the other source. Only after a certain period of time has passed (presumably a timeout period), the map will display tiles from the other source which is reachable at all times. Why are the tiles from the source that _is_ reachable not displayed almost immediately?

I have integrated the MapBox SDK into my project using Cocoapods. The MapBox version I am using is 1.1.0.

**Comment by mohpor** [comment]
I’m facing this problem too.  
In my case I have three different layers of base map, wen trying to change the tile source, it kindda gets blocked occasionally when a tile in the previous layer is still loading and the tile source won’t give up the control until those tiles are loaded...

## 

Mohammad Porooshani (https://www.facebook.com/mohpor)
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by datwelk** [comment]
@incanus any thoughts?

**Comment by incanus** [comment]
I believe this has to do with stacking order. You might look into `RMCompositeSource` as a way to combine them which fetches "top-down" in the source stacking order, quitting early as soon as opaqueness for a given tile screen space is reached. 

Another thing to check out is `-[RMAbstractWebMapSource requestTimeoutSeconds]` for managing this timeout, which defaults to something like a minute or two based on `CFNetwork` defaults.

**Comment by farfromrefug** [comment]
@incanus modifying the timeout is not a solution. We need to find the source of the problem!
I actually stumbled upon this facing this problem with a web source and a mbtiles source. I could not understand why my mbtiles was not loading instantly when the network connection was poor.
The reason is actually pretty simple, the requests are sync!!!!!!!
Just look [here](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMAbstractWebMapSource.m#L164)
I am fixing this right now in my branch and it is already working.
Will create a PR.
BTW i have other PRs pending ...

**Comment by farfromrefug** [comment]
PR pending https://github.com/mapbox/mapbox-ios-sdk/pull/448

**Comment by incanus** [comment]
Going to close in favor of the code in #448. Can't promise a speedy look at this as it's pretty involved  and the whole mechanism is a bit dated and will be better in Mapbox GL, but I will leave the pull request open to review.
