### ISSUE TITLE
Adding SMCalloutView's contentView

### ISSUE THREAD

**Issue by RyanCopley** [mapbox/DEPRECATED-mapbox-ios-sdk#437]
Howdy!

(Piece of code I'm referring too: https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapView.m#L1916-L1930)

How do you feel about also supporting the contentView of SMCalloutView as an option? Just as a test, I modified that piece of code to this:

```
        if (anAnnotation.layer.leftCalloutAccessoryView)
        {
            if ([anAnnotation.layer.leftCalloutAccessoryView isKindOfClass:[UIControl class]])
                [anAnnotation.layer.leftCalloutAccessoryView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapOnCalloutAccessoryWithGestureRecognizer:)]];

            _currentCallout.contentView = anAnnotation.layer.leftCalloutAccessoryView;
        }
```

and everything works fine (Although-- again, just to see if it would work or not, this isn't a good implementation), and allows me to set any arbitrary UIView as a callout and it resizes around it nicely.

If you think this is something you're interested in, I could add it in (Mostly via just copying and pasting that current block and changing it to contentView)

Thoughts?

**Comment by incanus** [comment]
Going to close as this is rolled into https://github.com/mapbox/mapbox-ios-sdk/issues/462.
