### ISSUE TITLE
userTrackingMode

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#44]
Setting the userTrackingMode without a data connection crashes the app.

**Comment by incanus** [comment]
You sure this isn't related to something else? I'm seeing crashes when trying to use an online layer via `RMMapBoxSource` (which I'm fixing now).

**Comment by incanus** [comment]
See also alpstein/route-me#88

**Comment by incanus** [comment]
Let me know if you still see this in develop, but I can't replicate.

**Comment by russellquinn** [comment]
This seems fixed now too.
