### ISSUE TITLE
tapOnLabelForAnnotation doesn't work on iOS7

### ISSUE THREAD

**Issue by kopacabana** [mapbox/DEPRECATED-mapbox-ios-sdk#440]
I implement MapBox on iOS6 and iOS7. That's work ! On iOS6 when I tap on label annotation, the methods tapOnLabelForAnnotation:onMap work perfectly but on iOS7, this methods doesn't work ?!?

**Comment by shanus** [comment]
I am having the exact same issue with version 1.2.0

**Comment by mohpor** [comment]
iOS 6 and iOS 7 use different types of SMCallouts for annotations, I'm guessing the SMCallout's the one to blame. try updating your SMCallout submodule, see if it helps.
Cheers

**Comment by mohpor** [comment]
@kopacabana , @shanus , @incanus 
I have investigated some more and I was right about my previous assessment!
the SDK uses `SMClassicCalloutView` for iOS 6 to show the annotation's callout and `SMCalloutView` for iOS 7.
These two views implement different types of touch handling.

`RMMapView` doesn't implement the `SMCalloutView`'s delegate method: `calloutViewClicked:`, therefore on iOS 7 the touch handling is lost.

Quick fix: handle the said delegate method in RMMapView and call `tapOnLabelForAnnotation` from that.
i.e.:

``` Objective-C
-(void)calloutViewClicked:(SMCalloutView *)calloutView
{
    if(_delegateHasTapOnLabelForAnnotation)
    {
        [self.delegate tapOnLabelForAnnotation:_currentAnnotation onMap:self];
    }
}

```

**Comment by incanus** [comment]
Thanks for digging into this @mohpor. I'll take a look.

**Comment by incanus** [comment]
This would be specific to `1.2.0`, as iOS 7 compatibility existed before, but the implementation was changed when SMCalloutView was updated for `1.2.0`.

**Comment by mohpor** [comment]
No Problem @incanus.
That's right. It's more a backward incompatibility on SMCallout's part.
Cheers to them for their great effort anyways.

**Comment by shanus** [comment]
@mohpor Thanks, that work around does the trick.

**Comment by incanus** [comment]
Sorry, I misread this last night. The `-[RMMapViewDelegate tapOnLabelForAnnotation:onMap:]` method is a carryover from the upstream project, which predates SMCalloutView and is meant for the `-[RMMarker label]` API, not callouts. Marker labels are custom views shown when markers are interacted with, but this behavior doesn't have an analog in MapKit. SMCalloutView was added to make things more MapKit-like. 

So my expected behavior here would be for neither the iOS 6 nor 7 version of SMCalloutView callouts to perform this callback. Any occurrence of this happening would be unexpected and/or undefined behavior.

**Comment by mohpor** [comment]
@incanus,
I can seem to remember what you said above, but nonetheless, current implementation is more useful than the dedicated purpose. But I still can see your point.
I guess the correct way to do this is to have two separate delegates:
- One for `tapOnLabelForAnnotation:onMap` 
- Another one for `tapOnTitleForAnnotation:onMap:`

This way we will have both covered. The missing delegate for tap on the title in SMCallout is very useful in my case.

**Comment by maciekish** [comment]
Any idea when this is going to get fixed in a release please?

**Comment by incanus** [comment]
This is relatively low priority for our core, so I'd take a pull request for this, but I don't think we will get to it anytime soon.

**Comment by maciekish** [comment]
PR added

**Comment by aozisik** [comment]
Please consider adding a delegate method that fires when the title is tapped. It is hard for users to tap tiny accessory views. Most users tend to think that tapping the label should do the same and It is frustrating and unintuitive when that does not work.

**Comment by trdavidson** [comment]
I agree with aozisik
