### ISSUE TITLE
MapBox iOS SDK 1.0.1 Error when touching a map pin

### ISSUE THREAD

**Issue by wasatchtechnology** [mapbox/DEPRECATED-mapbox-ios-sdk#442]
I'm getting the following error when I click on a map pin. This is occurring in the simulators and a real devices iOS 7 and iOS 7 64 bit.  The code does not throw an exception.

I have a map with a series of pins in it. Since updating to 10.0.1 in an attempt to support 64 bit iPhones I get the following error:
: CGContextPathContainsPoint: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

I've seen questions about this but they seem to involve TextBoxes and this has no TextBoxes.

Here is the code:
- (void)tapOnAnnotation:(RMAnnotation *)annotation onMap:(RMMapView *)map
  {
  if(annotation != nil)
  {
      NSDictionary *dict = [annotation userInfo];
      if([annotation.title isEqualToString:@"trailhead"])
      {
          @try
          {
              NSString *desc = [dict objectForKey:@"desc"];
              NSString *name = [dict objectForKey:@"name"];
  
  ```
          if(name == nil)
              name = @"Trail Head";
  
          if(desc == nil)
              desc = @"";
  
          UIAlertView *alert = [[UIAlertView alloc] initWithTitle:name
                                                          message:desc
                                                         delegate:nil
                                                cancelButtonTitle:@"OK"
                                                otherButtonTitles:nil];
          [alert show];
      }
      @catch (NSException *exception)
      {
          //  Never gets here
          NSString *string = exception.description;
      }
      @finally
      {   
      }
  }
  ```

**Comment by incanus** [comment]
What is the error exactly? And is `mapView.selectedAnnotation` changing at all?

**Comment by wasatchtechnology** [comment]
Here is the error text:
 CGContextPathContainsPoint: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

When the pin/annotation gets touched I get two of these errors in the trace window.  The errors appear before the tapOnAnnotation event gets hit.  The code acts properly and the alert shows just like it should.  The only indication that something is amiss are the errors in the trace window.  No exceptions.  This code is unchanged for quite awhile and these errors only showed up when compiling for 64 bit with version 10.  The 32 bit version shows no errors.

When the tapOnAnnotation code is called the (RMAnnotation *)annotation is what it should be.  I assume that is what you meant by is the mapView.selectedAnnotaion changing?  The mapView.selectedAnnotation pointer is the same as the one passed into the onTapAnnotation method.

Jon

**Comment by wasatchtechnology** [comment]
Jason,
No information on this?

Thanks,
Jon Clayton

**Comment by wasatchtechnology** [comment]
An update.
In targeting iOS  8 SDK I get the same errors.  I'm using 1.0.1. I think in the original posting I said 10.0.1, sorry.  On the CGContextAddPath and CGContextPathContainsPoint.  As stated in the original posting this happens touching a map pin.  This same code has been trouble free for sometime.  

CGContextAddPath: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
CGContextPathContainsPoint: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

I don't know how long Apple will let us dodge 64 bit.

**Comment by wasatchtechnology** [comment]
Another Update: I get these warnings in 1.2.0 as well as 1.0.1.  It does occur in the 32 bit version.  I get these when using the iOS 7 SDK XCode 5 and the iOS 8 Beta 3 release.  I will get the warnings by clicking anywhere on the map, not just the map pins, and clicking on some areas of the map cause the warning and some don't.  I set a exceptions breakpoint and I never get a exception.  It does seem to happen on a larger map.

**Comment by wasatchtechnology** [comment]
This map had a zero length track that was getting added.  That is, a track with no points.  If I don't add a track clicking on the map does not produce this error, but there seems to be a side effect of hosing up my other marker annotations.

**Comment by incanus** [comment]
Ok, I think I follow: you were getting the `CGContext` warnings because essentially a `nil`-sized context was trying to be created for your empty track?

**Comment by wasatchtechnology** [comment]
I'll buy that.  The hosed up markers were my bug.  Looks like having an empty track may have caused this somehow.  When the map has track a RMAnnotation \* and a track everything was fine.  When I load a map with an empty track, that is with no points in it the trouble and errors show up.  If there are no points I don't add the annotation and I no longer get the errors.

**Comment by wasatchtechnology** [comment]
Very well could be.  I answered the issue in GitHub and closed it.  I hope
that was OK.  When no empty track no issue.

Thank You,
Jon

Jon Clayton
jclayton@WasatchTech.com
WasatchTechnology@gmail.com
www.WasatchTech.com
