### ISSUE TITLE
setShowsUserLocation in mapView:didUpdateUserLocation: causes crash

### ISSUE THREAD

**Issue by mrabenhorst** [mapbox/DEPRECATED-mapbox-ios-sdk#445]
While trying to restrict the user's ability to report their location while outside the map bounds, I implemented a check and turn off script inside of mapView:didUpdateUserLocation: which sets showsUserLocation: to false if the userLocation is outside of the mapView's tilesource bounds. 

When I set showsUserLocation to FALSE the application crashes with error:
`'*** -[__NSSetM addObject:]: object cannot be nil'`

Tracing back to the problem, it appears that the crash occurs at the end of `locationManager:didUpdateToLocation:fromLocation:` on line 3582 (of release build) because self.userLocation is nil.

Perhaps the solution is to test whether self.userLocation is not nil.

**Comment by incanus** [comment]
I'm unclear here -- this is crashing because of code you added, or crashing in other scenarios?

**Comment by mrabenhorst** [comment]
It is crashing when I set `showsUserLocation` to `FALSE` inside of the delegate method `mapView:didUpdateUserLocation:` (where the delegate method is implemented by me). I don't see any other location where we have control over whether to show the user's location based on their position (i.e. if the tiles only cover a specific area and the user turns on the GPS outside of that area) except that delegate method. But if I stop user tracking in that delegate method, the App crashes.

**Comment by hasanadil** [comment]
I had the same issue, ended up on not relying on showsUserLocation for user's location on the map. Went to my instance of a location manager and then can control it finely.

**Comment by incanus** [comment]
Hmm, this shouldn't crash. Will investigate. A fix in your code (which might be a similar approach taken to fix in the SDK) would be to `dispatch_async()` the `BOOL` set in the main queue.

**Comment by incanus** [comment]
Ok, I couldn't replicate a crash exactly, but I did fix a check that should happen after calling the delegate to ensure in a couple places that we don't proceed if the delegate changed `showsUserLocation`.
