### ISSUE TITLE
showsUserLocation = NO

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#45]
Setting showsUserLocation to NO, after it's previously been YES crashes.

i.e.

mapView.showsUserLocation = YES;
mapView.showsUserLocation = NO;

The crash is when it's releasing all the related annotations. One of them has already been released.

**Comment by andreacremaschi** [comment]
confirmed

**Comment by russellquinn** [comment]
Fixed.
