### ISSUE TITLE
Disable panning?

### ISSUE THREAD

**Issue by nderkach** [mapbox/DEPRECATED-mapbox-ios-sdk#450]
What's the best way to disable panning while still allowing user to change zoom?

So far I came up just with tracking map position changes in RMMapView delegate and reassigning centerCoordinate property. Is there a better way?

**Comment by incanus** [comment]
You want this API: https://github.com/mapbox/mapbox-ios-sdk/blob/b83fc2ddf400b9e308fe0ccf87371f32b240d045/MapView/Map/RMMapView.h#L278-L285

**Comment by nderkach** [comment]
Hm, using this API I just constrain coordinates displayed on the map, right?
What I want to achieve is that a user is able to change zoom to any level, while not allowing him to pan the map, i.e. center the map at his current coordinate.

**Comment by incanus** [comment]
Ah, sorry. Yeah, I would recommend adding a boolean property then called `scrollEnabled` or similar and checking for that on relevant internals of `RMMapView`. Unfortunately I don't think there's a another way to do it in the present state.

**Comment by mohpor** [comment]
Hi @nderkach, I've had the same request for my own app, luckily I have zoom controllers (+ and - buttons) and what I did was to disable user interactions on map view as long as I wanted to disable panning and it works like a charm.
I'm guessing you are trying to draw on your map and you want to use the pan gesture for that reason, you can stop pan gesture from propagating in the view hierarchy, but that's more work, try disabling that user interaction instead.
`self.mapView.userInteractionEnabled=NO;`

**Comment by nderkach** [comment]
@mohpor I'd like zooming with pinching and tapping still available while panning is disabled.

I've almost been able to achieve that effect with

```
self.mapView.draggingEnabled = NO;
self.mapView.zoomingInPivotsAroundCenter = YES;
```

But pinching in and out still doesn't pivot against the center.

@incanus could you elaborate on how exactly I could use `scrollEnabled`?

**Comment by incanus** [comment]
I'm saying you would add a new property called `scrollEnabled`. Then, for any gestures (like pan) that would change the center, you can return early. See here for an example of how we do this in Mapbox GL: 

https://github.com/mapbox/mapbox-gl-cocoa/blob/a9831928449475e536b7780fe4db678e1bc0127b/mapbox-gl-cocoa/MGLMapView.mm#L387

**Comment by incanus** [comment]
Going to close this as an edge case since MapKit doesn't have this either.
