### ISSUE TITLE
showsUserLocation memory leak?

### ISSUE THREAD

**Issue by tmcw** [mapbox/DEPRECATED-mapbox-ios-sdk#452]
From @modernprogrammr's post http://themodernprogrammer.com/post/rmmapview-not-deallocating-memory-in-ios-this-could-be-the-problem/#comment-4265 

``` objc
- (void)viewWillDisappear:(BOOL)animated {
    if ([self isMovingFromParentViewController]) {
        _mapView.showsUserLocation = NO;
    }
    [super viewWillDisappear:animated];
}
```

Fixes a memory leak that otherwise occurs if showsUserLocation is true when maps are disposed of.

**Comment by incanus** [comment]
This is fixed as of https://github.com/mapbox/mapbox-ios-sdk/commit/2ad680611eb12c6c350d0914c92c1c42bd936132 and `1.2.0`.
