### ISSUE TITLE
Use of RMMapView in a controller, prevents controller dealloc

### ISSUE THREAD

**Issue by pivl** [mapbox/DEPRECATED-mapbox-ios-sdk#453]
If you initialize a RMMapView object, add it to controller's view hierarchy, RMMapView keeps a strong pointer to its view controller, so view controller's dealloc method never get called

**Comment by pivl** [comment]
setting
_mapView.hideAttribution = YES;
can fix the problem..

**Comment by incanus** [comment]
This is fixed as of https://github.com/mapbox/mapbox-ios-sdk/commit/2ad680611eb12c6c350d0914c92c1c42bd936132 and `1.2.0`.
