### ISSUE TITLE
RMTileCache protocol and class name issue

### ISSUE THREAD

**Issue by hasanadil** [mapbox/DEPRECATED-mapbox-ios-sdk#455]
Hi, It's a bit confusing to have both the interface and a protocol have the same name, RMTileCache. Given the relation below where the database/memory cache provides services that the tile cache manager uses, then would it better to have the protocol that RMDatabaseCache implements be called RMTileCache[Store | Source] or something along those lines.

RMDatabaseCache\* dbCacheStore = [[RMDatabaseCache alloc] initUsingCacheDir:YES];
RMTileCache\* tileCache = [[RMTileCache alloc] initWithExpiryPeriod:0];
[tileCache addCache:dbCacheStore];

Thanks

**Comment by incanus** [comment]
Yes, this is a bit confusing, but the whole `RMTileCache` mechanism is in need of rethinking, something that's been iterated on well in [MBXMapKit](http://mapbox.com/mbxmapkit) and will be architected similarly in [Mapbox GL](http://mapbox.com/mapbox-gl).
