### ISSUE TITLE
The internal scroll view doesn't respond to device rotation

### ISSUE THREAD

**Issue by maciekish** [mapbox/DEPRECATED-mapbox-ios-sdk#458]
Hi,
We are creating our RMMapView in a Storyboard. The initial size is for iPhone 5, but if we run on a 3.5 inch device or rotate the device the map renders and covers the entire screen, but the user tracking dot will be in the wrong place and the right side of the screen won't respond to swipes or taps.

Using the new View Debugger in the Xcode 6 beta (The NDA is not as restrictive this year) i can see that the RMMapScrollView never updates its size in response to the device rotation.

I can work around this with the following hack:
1) Change the instance variable _mapScrollView to a public property.
2) After rotation: mapView.mapScrollView.frame = mapView.superview.bounds;

Is this a known issue?

**Comment by hasanadil** [comment]
One thing I noticed that in the SDK, parts were using auto layout and other parts are still on springs. I had to add autoresizing to the mapView. And have its translatesAutoresizingMaskIntoConstraints set to yes (default).

[mapView setTranslatesAutoresizingMaskIntoConstraints:YES];
[mapView setAutoresizingMask:UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth];

Best

**Comment by maciekish** [comment]
Thanks, that's a better workaround as you don't have to modify the Pod. Still looking forward to real Autolayout support though.

**Comment by hasanadil** [comment]
Awesome! Yep, would be nice to have it all consistent at least.

**Comment by incanus** [comment]
Yeah, the approach with AutoLayout was to use it just in the parts that interact with the view controller top and bottom layout guides, since that was essential. Most of the rest of the SDK is using springs & struts still.

**Comment by incanus** [comment]
I think this manifests itself with gestures, too. Post-landscape rotation, the `RMMapOverlayView` doesn't resize. Adding some debug lines to it: 

``` objc
self.layer.borderColor = [[UIColor redColor] CGColor];
self.layer.borderWidth = 1;
```

![ios simulator screen shot nov 7 2014 10 53 12 am](https://cloud.githubusercontent.com/assets/17722/4958500/923a1e1e-66af-11e4-867e-dc857c009047.png)

![ios simulator screen shot nov 7 2014 10 53 15 am](https://cloud.githubusercontent.com/assets/17722/4958503/965790d0-66af-11e4-8fb3-1a058d0c4ca3.png)

After this, the rightmost area doesn't accept pan gestures.

**Comment by incanus** [comment]
@maciekish @hasanadil Can you check out the above commit and see if it addresses your problems?
