### ISSUE TITLE
add zoom convenience method

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#46]
We can animated zoom to a point, or animate zoom to a SW/NE bounds, but we can't easily animate zoom to a center point with a certain zoom level applied. Right now, we are calculating zoom meters manually and using the SW/NE zoom as a hack. This should be native.

**Comment by asutula** [comment]
This would be a great feature. In the meantime, given a RMMapView size, are you able to calculate a SW/NE bounds that results in a 'nice looking' zoom level (15 instead of 14.9, for example)? If so, I'd love to see that code! Thanks.

**Comment by incanus** [comment]
Going to take a quick look at this for the next release.
