### ISSUE TITLE
Adding support for annotation image positioning

### ISSUE THREAD

**Issue by hasanadil** [mapbox/DEPRECATED-mapbox-ios-sdk#460]
Hi, When setting an icon image, it's added with the image centered on the annotation. It works where the image is circular but if its a standard map pin image or a balloon,  then it doesn't work since the bottom tip of the pin needs to be where the annotation point is, not its center.

The cleanest way, I could think was to override the setImage method in RMPointAnnotation
- (void)setImage:(UIImage *)image {
  [(RMMarker *)[self layer] replaceUIImage:image anchorPoint:CGPointMake(0.5, 1)];
  }
- The default (defaultMarkerAnchorPoint) anchor is 0.5,0.5

One way, would be nice to have an enum provided in RMPointAnnotation (center, top, bottom, left, right etc). Which can then be passed alongside the image or just expose the anchor point in a public method from RMPointAnnotation, so the sdk users can specify the image position without needing to have a subclass.
- (void)setImage:(UIImage *)image withAnchorPoint:(CGPoint)point

Thanks

**Comment by incanus** [comment]
Check out `-[RMMarker initWithUIImage:anchorPoint:]`. I think in this case (and other custom scenarios), it's better to go straight to `RMMarker` by way of `RMAnnotation` rather than use the layer automatically provided by `RMPointAnnotation`.
