### ISSUE TITLE
Cache not saved after "killing" and relaunching the app

### ISSUE THREAD

**Issue by rsenerol** [mapbox/DEPRECATED-mapbox-ios-sdk#463]
Hi everyone!

When the user "kills" the app, turn on the airplane mode and relaunch it, the cache is not displayed and a new database seems to be recreated (not sure about that). Therefore, the map doesn't appear at all (offline mode).

This problem appears only if the user "kills" the app (I don't mean delete/uninstall the app).

Here how I init the RMMapView:

NSString *fullPath = [[NSBundle mainBundle] pathForResource:@"map_dev" ofType:@"json"];
NSString *tileJSON = [NSString stringWithContentsOfFile:fullPath encoding:NSASCIIStringEncoding error:NULL];

RMMapboxSource *onlineTileSource = [[RMMapboxSource alloc] initWithTileJSON:tileJSON];
[onlineTileSource setCacheable:YES];

RMMapView *mapView = [[RMMapView alloc] initWithFrame:[UIScreen mainScreen].bounds andTilesource:onlineTileSource];

Am I doing something wrong? The database storing the cache is not reused after relaunching the app?

Thanks!

**Comment by incanus** [comment]
@rsenerol Are you using the same metadata each time such that this info would stay the same? 

https://github.com/mapbox/mapbox-ios-sdk/blob/f47ae3d96a27661eb4f888660787bffdf0294492/MapView/Map/RMMapboxSource.m#L91
