### ISSUE TITLE
Please make 1.2.0 release available in cocoapods

### ISSUE THREAD

**Issue by drmarkpowell** [mapbox/DEPRECATED-mapbox-ios-sdk#464]
Cocoapods.org is still on version 1.1, and I'm itching to try 1.2.

**Comment by incanus** [comment]
On my list, but need to get onboard with the new Trunk model. In the meantime, you should be able to point at the `Mapbox.podspec` in the repo per: 

http://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by drmarkpowell** [comment]
Thanks for the tip, but I tried to follow this and I got an error, possibly due to some case sensitivity in the podspec filename (upper vs lowercase b)?  

Pre-downloading: `MapBox` from `https://github.com/mapbox/mapbox-ios-sdk`, tag `1.2.0`
[!] The name of the given podspec `Mapbox` doesn't match the expected one `MapBox`

If I change the pod name to ‘Mapbox’ I get this error:
 [!] Attempt to read non existent folder `/Users/mpowell/Workspaces/MarsImagesIOS/Pods/Mapbox`

-Mark

**Comment by metatheoretic** [comment]
I get the same error, and all of the dependent libraries present warnings in iOS 7.0+ because they are outdated.

**Comment by incanus** [comment]
Check out pod `Mapbox-iOS-SDK` for versions `1.2.0` and ongoing. 

Thanks for the lunch conversation, @drmarkpowell ;-)

**Comment by drmarkpowell** [comment]
Thank you, Justin! It was great to meet you.-MarkOn Wed, Jul 23, 2014 at 5:34 PM,  Justin R. Miller notifications@github.com wrote:             Check out pod Mapbox-iOS-SDK for versions 1.2.0 and ongoing. 

Thanks for the lunch conversation, @drmarkpowell ;-)
