### ISSUE TITLE
A way to only use offline tiles

### ISSUE THREAD

**Issue by benogle** [mapbox/DEPRECATED-mapbox-ios-sdk#467]
Is there a way to force the use of the cached tiles only? If there is no option / clean way to do this, I'm ok digging into a bit of code.

Use case: I am in a foreign country with a very expensive data plan, enabled only for small bits of data like an imessage. I would like to be able to give the app an 'offline' mode I can enable / disable regardless of connectivity.

Using SDK V1.1.0

**Comment by incanus** [comment]
Aside from using pre-bundled MBTiles with the `RMMBTilesSource`, no, you'll have to hack it a bit to _not_ hit the network. Keep in mind though that all network tile sources check the cache first, then only hit the network if cache isn't found. 

If you want to hack the network tile sources, you want to stop things at this line: 

https://github.com/mapbox/mapbox-ios-sdk/blob/f47ae3d96a27661eb4f888660787bffdf0294492/MapView/Map/RMAbstractWebMapSource.m#L79

See just above there where cache is consulted first.

**Comment by benogle** [comment]
This worked well, thanks. I created a subclass of `RMMapboxSource` and repimplemented the bits I needed.

**Comment by guidove** [comment]
Would setting the retryCount to 0 not have the same effect?

**Comment by incanus** [comment]
@guidove I think it might!

**Comment by guidove** [comment]
I can now confirm that it does. I had a chance to test it yesterday.

**Comment by incanus** [comment]
Cool, thanks for that, @guidove. Will leave this closed but this should show up in search results if people have questions around the same in the future.
