### ISSUE TITLE
Scale Bar existence?

### ISSUE THREAD

**Issue by eibenm** [mapbox/DEPRECATED-mapbox-ios-sdk#471]
I've successfully launched an App into the Apple Store now based off the MapBox iOS SDK using it's amazing offline tile caching features!

The one thing I've really noticed that's missing on our custom maps though is a Scale Bar.  I've perused through the MapBox docs, but I haven't seemed to find anything pertaining to that.  Is there a Scale Bar available through the iOS SDK?

**Comment by incanus** [comment]
No, the scale bar does not exist yet. Issue for it is here: https://github.com/mapbox/mapbox-ios-sdk/issues/325
