### ISSUE TITLE
Setting tiledLayerView layer contents to nil blocks UI

### ISSUE THREAD

**Issue by danlite** [mapbox/DEPRECATED-mapbox-ios-sdk#472]
In our application, the user can switch between maps, which sets a new tile source for the RMMapView. However, I've found that (in RMMapView) calling `tiledLayerView.layer.contents = nil` causes a noticeable UI lag. Below is the patched branch we're using in our application.

I'm not sure why the lag occurs, or if there are ramifications for removing the offending code, but I figured I'd at least mention it.

https://github.com/DanLite/mapbox-ios-sdk/commit/dfa8d9b89561ba96fcfff705e477565e49c43c92

I can set up a sample project to reproduce, if needed.

**Comment by incanus** [comment]
Hmm, interesting. This comes from the upstream project. Technically, the two calls for removing a tile source shouldn't need this, since the view/layer is removed from the hierarchy. Do you still see an unacceptable lag in the `-createMapView` and `-setDebugTiles:` methods or did you just remove these for completeness?

**Comment by danlite** [comment]
Yes, the lag I'm experiencing actually comes solely from `-createMapView`, through calling `-setTileSource:` (I'm replacing the only tile source with a new one). It's a several-second delay on an iPhone 5s, which I find strange for a seemingly harmless operation.

In my case, the `-setDebugTiles:` and `-removeTileSource[AtIndex]:` methods are not being called, but I removed the lines there for completeness.

**Comment by incanus** [comment]
I don't know too much about the deep layer rendering internals, but does this seem to happen only in certain scenarios, e.g. when done before the map view is added to the hierarchy, or only when it's in the hierarchy, or instantiated from a XIB/storyboard, etc.? I'm just wondering why no one else has reported it and it has been in the code for years at this point. Maybe that can shed some light as to a fix.

**Comment by danlite** [comment]
It occurs while the map view is in the view hierarchy, after being first instantiated from a XIB.

I'll aim to set up a sample project to demonstrate a general case.

**Comment by incanus** [comment]
@DanLite Any luck with a sample project? Also, check out the commits of the past few days which modify `viewDidLoad` and other early-stage stuff like XIB loading.

**Comment by danlite** [comment]
Unfortunately nothing conclusive came from the sample project – I was unable to consistently reproduce the problem I'm finding in my own app.

From what I've seen in both my app and the sample app, it almost seems to network-related. E.g. with tiles that load slowly, switching the map source mid-load will trigger the aforementioned UI lag.

Sorry I couldn't be more help. The sample project is here if you want to check it out for yourself, but like I said before, I can't guarantee you'll see the issue with it: https://github.com/DanLite/MapboxLagDemo

**Comment by incanus** [comment]
Thanks for digging, @DanLite. I'll close for now. I've not ever seen this.
