### ISSUE TITLE
Warning in Xcode with CocoaPods

### ISSUE THREAD

**Issue by frederik-jacques** [mapbox/DEPRECATED-mapbox-ios-sdk#474]
When you install the SDK via CocoaPods you'll get a warning in XCode 5.1.1 

```
ld: warning: directory not found for option '-L/PATH_OF_PROJECT/Pods/Mapbox/Proj4'
```

The folder Mapbox does not exist, instead it's called 'Mapbox-iOS-SDK'.

**Comment by incanus** [comment]
Thanks; this looks like a tweak needed after the pod rename. I'll get it.
