### ISSUE TITLE
Warning: I could not find the column named 'tile_data'

### ISSUE THREAD

**Issue by onato** [mapbox/DEPRECATED-mapbox-ios-sdk#475]
If the FMResultSet is nil then the following line causes the warning to be NSLog[ed] 

https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMBTilesSource.m#L126

Could you please wrap this in…

```
if(results) {
  …
  [results next];
  NSData *data = [results dataForColumn:@"tile_data"];
  …
}
```

This happens a lot if an mbtiles file does not contain all required tiles.

**Comment by incanus** [comment]
The `result` always comes back non-`nil` here, so the above fix instead makes sure that there were actual result columns returned in order to avoid the logging.

**Comment by onato** [comment]
Indeed, my silly mistake. Thanks for the fix!
