### ISSUE TITLE
Memory leak in RMShape.m

### ISSUE THREAD

**Issue by master-nevi** [mapbox/DEPRECATED-mapbox-ios-sdk#476]
There's a memory leak in RMShape.m which prevents the map view from being deallocated if the map view contains annotations backed by RMShape. The fix was simply to use a weak reference to the map view. See this commit:
https://github.com/master-nevi/mapbox-ios-sdk/commit/2009e55405be5e65a4f44c909357b77c53be4af9

**Comment by incanus** [comment]
Cherry-picked in 27972839b34ba82a7e1beec65e69df5cab67dfad. Thanks @master-nevi!
