### ISSUE TITLE
Change _compassButton location from upper right

### ISSUE THREAD

**Issue by davidchiles** [mapbox/DEPRECATED-mapbox-ios-sdk#479]
Is there a way to change the origin of the _compassButton on a RMMapview?

**Comment by incanus** [comment]
Not with public API, but you could do it yourself. It's meant to mimic MapKit's. 

Relevant code sections: 
- Initial frame: https://github.com/mapbox/mapbox-ios-sdk/blob/5b52bb307aca918320bdc7b766fce4d946a95796/MapView/Map/RMMapView.m#L323
- Constraints to keep it there: https://github.com/mapbox/mapbox-ios-sdk/blob/5b52bb307aca918320bdc7b766fce4d946a95796/MapView/Map/RMMapView.m#L517-L534

I'd say making this configurable is beyond the scope of this project, but you could do it in a fork.
