### ISSUE TITLE
Change placement of compassButton on RMMapView

### ISSUE THREAD

**Issue by chrisballinger** [mapbox/DEPRECATED-mapbox-ios-sdk#480]
We have a transparent search bar in the upper area of the map which covers up the compassButton when the compass is active. It seems like it would make sense to allow a configurable position so we could place it in the bottom-right or otherwise. 

This is where it is hardcoded, L323 of RMMapView.m:

``` obj-c
UIView *container = [[UIView alloc] initWithFrame:CGRectMake(self.bounds.size.width - compassImage.size.width - 5, 5, compassImage.size.width, compassImage.size.height)];
```

Seems like the containerView would need to be exposed somehow in order to change its layout constraints at runtime.

Thoughts?

**Comment by hasanadil** [comment]
This would be awesome to have! 

Also ability to change placement of the "Mapbox" and the info button at the bottom.

**Comment by incanus** [comment]
Heh, someone _just_ brought this up in the previous ticket: https://github.com/mapbox/mapbox-ios-sdk/issues/479

Gonna close this one — I'd take a PR but hopping on this isn't a priority right now.
