### ISSUE TITLE
iOS 8: Tap on RMUserTrackingBarButtonItem does not show my location

### ISSUE THREAD

**Issue by brosnic** [mapbox/DEPRECATED-mapbox-ios-sdk#481]
Hi, 

i'm testing with iOS 8 beta 5.
In my ViewController i have a RMMapView and a RMUserTrackingBarButtonItem.
When i'm tapping the button the activity indicator is showing on the button but nothing happens.
In iOS 7 everything is working.

Does anybody else have the same problem?

thanks for your help!
Mike

**Comment by incanus** [comment]
Are you testing on device or simulator? If simulator, are you sure location simulation is working? Does it work for Apple Maps?

**Comment by brosnic** [comment]
I tested on an iPad 4 and iPad 3.
For the Apple Maps it's working

**Comment by incanus** [comment]
Yep seeing this. Looking into it.

**Comment by incanus** [comment]
Ok, this should be fixed above in the `develop` branch — can you check it out @brosnic? Note that you have to add `NSLocationWhenInUseUsageDescription` to your app's `Info.plist` to comply with the new requirement of Core Location in iOS 8.

**Comment by brosnic** [comment]
Thanks, it seems to work.
Is it possible to create the framework for 1.3.0 (http://mapbox-ios-sdk.s3.amazonaws.com/index.html)? I just see it as pod...

**Comment by incanus** [comment]
Yes! Sorry about that; forgot. Will get that now.

**Comment by incanus** [comment]
This is up and reorganized per #369 at http://mapbox-ios-sdk.s3.amazonaws.com/index.html.
