### ISSUE TITLE
sdk trying to get zoom level 16 from mbtiles file though zoom max level is lower

### ISSUE THREAD

**Issue by noosxe** [mapbox/DEPRECATED-mapbox-ios-sdk#484]
Hi.
I'm using sdk version 1.3 from cocoapods.
When I add offline tile source mbtiles file I receive an exception:uncaught exception 'NSInternalInconsistencyException', reason: 'RMMBTilesSource: Armenia, zooms 6-13, supports interactivity tried to retrieve tile with zoomLevel 16, outside source's defined range 6.000000 to 13.000000'
But I have max zoom level specified as 13.
What can be the reason of this behaviour ?

**Comment by incanus** [comment]
Have you specified the map max zoom, or just indicated in the MBTiles that it is not supported outside of that range? You need to make sure that the map doesn't go outside of the tile source's range.

**Comment by noosxe** [comment]
Hi. Yes I have specified min and max zoom levels on the mapView object, but as I found out that behaviour was caused by using tilejson of my own for fetching online tiles, in tile json I had min and max zoom levels specified 0 - 17, so somehow when I was adding mbtiles file as second tile source, mapview was obeying my tilejson configs not min and max zoom levels set on mapview object.

**Comment by incanus** [comment]
Try setting the min and max again manually after configuring tile sources?

**Comment by noosxe** [comment]
Seems like that worked, thanks for your support.

**Comment by incanus** [comment]
Great!
