### ISSUE TITLE
GreateCircle crashed when start and end coordinate are the same

### ISSUE THREAD

**Issue by Blaumeiser** [mapbox/DEPRECATED-mapbox-ios-sdk#486]
GreateCircle crashed when start and end coordinate are the same.

Simply check if start- and end-coordinate are the same and return from layer-function.

**Comment by incanus** [comment]
I'd rather see this as an assertion per above so that the programmer catches this rather than a possible `nil` annotation.

**Comment by Blaumeiser** [comment]
Programmers will get knowlegde of this when the app is in the appstore.
Please add an assert.

**Comment by incanus** [comment]
Sorry to be unclear — I did add the assert in https://github.com/mapbox/mapbox-ios-sdk/commit/c56aa938eb70aec673feff55b8c2dc512fbe5529 above.
