### ISSUE TITLE
Map pointing to Antarctica on arm64, zoom broken

### ISSUE THREAD

**Issue by Thinkscape** [mapbox/DEPRECATED-mapbox-ios-sdk#490]
Given an app, using the latest version of mapbox sdk, with the following code in main controller:

``` objc
[self.mapView setCenterCoordinate:london animated:NO];
[self.mapView setZoom:12];
```

The map works fine on iPhone 5, but displays blank/empty tiles on iPhone 5s (arm64).

We've established, that changing the above code to:

``` objc
[self.mapView setZoom:12];
[self.mapView setCenterCoordinate:london animated:NO];
```

Fixes the problem, for some reason.

**Comment by incanus** [comment]
Probably related to #20, going to close here but link will be preserved for context.
