### ISSUE TITLE
error while running 

### ISSUE THREAD

**Issue by vaibhavvatts** [mapbox/DEPRECATED-mapbox-ios-sdk#497]
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by incanus** [comment]
Need more context on this; can you share some code?

**Comment by Aguidice** [comment]
I get this when I try to compile/run the sample Proj4.xcodeproj in the iOS SDK. Very new programmer.

clang: error: no such file or directory: '/Users/me/Documents/mapbox-ios-sdk-release/MapView/Map/FMDB/src/fmdb/FMDatabasePool.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by incanus** [comment]
Looks like you haven't setup the submodules per the `README`.
