### ISSUE TITLE
Location privacy notice

### ISSUE THREAD

**Issue by MarkMolina** [mapbox/DEPRECATED-mapbox-ios-sdk#504]
I think MapBox does something wrong with the Location Authorization when an app sets the showsUserLocation to YES.

Since iOS 8 apple added 2 authorisations conforming location services:
- requestWhenInUseAuthorization with plist key: NSLocationWhenInUseUsageDescription
- requestAlwaysAuthorization with plist key: NSLocationAlwaysUsageDescription

Correct me if I'm wrong but I think iOS8 shows the blue bar with the text: "Appname is Using Your Location" when an app asks for the always authorization. However when I set my mapview to show the userlocation and press the homebutton the blue bar is still visible. If I comment that line of code the blue bar is gone.

Since MapBox shouldn't do location updating in the background, the blue bar shouldn't be visible right?

![screen shot 2014-09-18 at 17 29 29](https://cloud.githubusercontent.com/assets/3329668/4322481/d4dcb81e-3f48-11e4-977d-fbb61e300a2d.png)

**Comment by incanus** [comment]
@MarkMolina Are you using the latest version of the SDK? We've added support for the finer-grained location control in iOS 8: 

https://github.com/mapbox/mapbox-ios-sdk/blob/509fa7df46ebd654d130ab2f530a8e380bf2bd59/MapView/Map/RMMapView.m#L3315-L3323

**Comment by MarkMolina** [comment]
Yes I updated with cocoapods to the most recent version which is I think 1.4.1. I also noticed that piece of code and I added the key (NSLocationWhenInUseUsageDescription ) to my plist.

So that blue bar will be shown when I start my app. Press the mapviewcontroller in my tabbar and then press the homebutton. If I change _mapView.showsUserLocation = YES; to NO it doesn't show the blue bar after pressing the home button.

Is this something with mapbox or am I doing something wrong? Feel free to ask me for particular parts of code if you think that will help.

**Comment by incanus** [comment]
@MarkMolina I'm definitely not seeing the same behavior as you — I just tried it with one of our example apps with both showing location as well as tracking location, and in both cases, the blue bar does not show up. Are you sure you're not using `CLLocationManager` somewhere else in your app? 

I'd recommend posting some simplified code that shows this happening. If you'd like to share some private code, feel free to email `help@mapbox.com` with an attachment.

**Comment by MarkMolina** [comment]
Sorry for the late response. I was working on another project.

So I created a test application. Basically it's a tabbarcontorller with two screen. The first screen has a location manager. The second a map view which shows the users location. 

Both screen ask for gps on the viewdidload. Now during testing I noticed something strange. After asking for always authorization on the first screen I press the home button. The blue bar isn't showing but the delegate is getting called.
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  [self dummyMethod];
  }
- (void)dummyMethod {
  _locationManager = [[CLLocationManager alloc] init];
  [_locationManager setDelegate:self];
  [_locationManager setDesiredAccuracy:kCLLocationAccuracyBest];
  [_locationManager startUpdatingLocation];
  
  [_locationManager requestAlwaysAuthorization];
  }

#pragma mark - CLLocationManager Delegates
- (void)locationManager:(CLLocationManager *)manager
  didUpdateToLocation:(CLLocation *)newLocation
         fromLocation:(CLLocation *)oldLocation {
  
  NSLog(@"Found new location: %@", newLocation);
  }

So now the blue bar just won't appear but Mapbox seems to be working correctly.
