### ISSUE TITLE
ios8 userLocation

### ISSUE THREAD

**Issue by Rimins** [mapbox/DEPRECATED-mapbox-ios-sdk#507]
On ios8 simulator or iPad2 (my test device) doesn`t detected user location. Please check this & update example "MapBox Me" with this feature.
Version 1.4.1.

**Comment by joaosobrinho** [comment]
I'm also having this issue in iOS8.1.
It's not detecting the user location.

**Comment by incanus** [comment]
Let's keep this over in https://github.com/mapbox/mapbox-ios-sdk/issues/519.
