### ISSUE TITLE
MapBox/MapBox.h file not found when building XCUnit test target

### ISSUE THREAD

**Issue by HiveHicks** [mapbox/DEPRECATED-mapbox-ios-sdk#508]
Each time I try to build my test target, I get this compilation error, although app target builds OK. I tried setting the correct Header Search Path for test target, but it doesn't seem to work.

**Comment by incanus** [comment]
Hmm, can you paste the full compile error line from Xcode? Something like this `Command-C` here should do it: 

![screen shot 2014-09-23 at 11 05 16 am](https://cloud.githubusercontent.com/assets/17722/4377167/33d2398c-434c-11e4-971d-53b10586dfb0.png)

**Comment by HiveHicks** [comment]
![](https://d2oawfjgoy88bd.cloudfront.net/526563d32cdc081b4d24db71/526563ea2cdc081b4d24dbab/5421ce620077913c5a7d1c16.png?Expires=1411588090&Signature=No7x6Rv~DDNUC4-3k4079V86skBItI72sYE3Vfg2Sc5lWlr2GfZmHUEAh8tQtnKum6HEmrvNZpWE9VPcYkhMdTHS1HVzHPrEO2advb5RP09xaoMSlNH70t2WNIC2p4mJxho6lmWj4osvDjnFYryBz3TxiWQYaNHVoL83-G16D2BqxNvDBBBsxhFlfghxKGsNbLmPQq6YOJ1MwsNIumbSVucEjcFHGbV-mdqQDWv0Mfte-zMqBDgjoSaFFgSW1TLs-bCk5Dw4l9ldulyBqt2YL0aMnhSqMC2qgZRfWsCqLg~lnGtE~hEyVyZ6W4JeL-fcLCMUlwlYC1~wDZVVu7dRHg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

![](https://d2oawfjgoy88bd.cloudfront.net/526563d32cdc081b4d24db71/526563ea2cdc081b4d24dbab/5421cf3338d38708ae385933.png?Expires=1411588281&Signature=ZeGr6s5ZKuloyz~RrSXNnhfvIKGphLqBs1QJ2AIpMCk12LP~chccp48yFKGwzP3fGiFIYRJPWsYh2kM9kTUDMKHylXAQXFYhY4tSxTsCGJUMp7LpQMua9lTGq7JLJQhLOEIZH6prijm7r8ouR9gnbC8fgPSk6KqUUYdXze9Mh2CWJk51zyahOJloS0HQusyRVqGbXUO9P0qNC1ASDaRFQy7qxsD1hwld7qeqxtFoH8scvmrVrZolDgwac3SV99APlUjKnT8Ov99JppXW9rvQDtDi1wxXf67N6AtkgTnlS6wAJqYlD6aulZBj1lBW~apQbsygkj38R6kq6RiK7LfADw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by HiveHicks** [comment]
Hmm, fixing Frameworks Search Path on another computer fixed the problem.
