### ISSUE TITLE
Shapes and lines not displaying on ios map

### ISSUE THREAD

**Issue by johnryan** [mapbox/DEPRECATED-mapbox-ios-sdk#520]
I added lines and shapes to my map in the mapbox web interface, but they don't show on the map. Is this a bug? Thanks.

**Comment by mohpor** [comment]
Two things @jfirebaugh 
1. Are you handling the appropriate delegate methods? You need to handle the `RMMapViewDelegate`'s `- (RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation;` to let the map know the type of layers are your newly added annotations (be them lines or shapes or any other types)
2. If So, are you setting the coordinate for the annotations and they are actually in your visible bounding box? you see, that delegate method I've mentioned above gets called only if the coordinate of the annotation is inside visible bounding box and the tricky point here is that the coordinate of the annotation doesn't have anything to do with the actual shape, so you can set it wherever you want but make sure it is a visible point.

If these points doesn't solve your problem, let me know, I'll help you get your lines and shapes on the map.
Cheers

**Comment by johnryan** [comment]
Thanks for the tip, but I think that is a different issue. What i'm seeing is that when I create shapes in the online map editor they are saved there, however they don't show up on the map. The layerForAnnotation method isn't called, and after inspecting the "tileJSON" property on the RMMapboxSource it doesn't look like any of the features I created are being returned there. Does that clarify?

Thanks!

**Comment by incanus** [comment]
Yes, this is covered here @johnryan: https://github.com/mapbox/mapbox-ios-sdk/issues/419

The fix should be pretty straightforward, but it just hasn't been a priority yet as we move more and more of our rendering to vector tiles instead of "external" GeoJSON/KML like the online editor supports.

**Comment by johnryan** [comment]
@incanus the issue I think is that, the json used to create the map doesn't include the features created on the web. I inspected the json used to create the map and don't see it there. Not sure if i have everything setup correctly. the docs on the web say to set an access token in the RMConfiguration, but that doesn't seem to be enabled.

**Comment by incanus** [comment]
Oh, I follow. That doesn't sound right. Can you pass a map ID here and I'll investigate & document the findings in this ticket? Or feel free to hit up `help@mapbox.com` for private discussion. 

Re: access token, yes, see here: https://github.com/mapbox/mapbox-ios-sdk/issues/494

**Comment by johnryan** [comment]
Awesome, thanks. Here's the mapid: johnryan.jlcik0f0

**Comment by incanus** [comment]
@johnryan I'm seeing features coming through ok using our API per: 

https://www.mapbox.com/developers/api/maps/#geojson

e.g. the direct link is: 

https://a.tiles.mapbox.com/v4/johnryan.jlcik0f0/features.json?access_token=pk.eyJ1Ijoiam9obnJ5YW4iLCJhIjoid1EwcGZmVSJ9.PIw1tBvC5bzgDx683vhorw

**Comment by johnryan** [comment]
@incanus ok, i can just use that to get the points...what i'm seeing is the app only hitting this URL:
https://api.tiles.mapbox.com/v3/johnryan.jlcik0f0.json?secure
which doesn't return any of that JSON. In that case the recommended approach is to hit the URL you provided, then modify the existing sdk to draw those points on the map?

**Comment by incanus** [comment]
If you look at that the contents of that TileJSON, it points to `https://a.tiles.mapbox.com/v3/johnryan.jlcik0f0/markers.geojsonp`, which has your features. The current SDK does draw points, just not `LineString` or other features that are polylines or polygons.
