### ISSUE TITLE
Metadata info isn't loading automatically to render the RMMapView (MBTiles)

### ISSUE THREAD

**Issue by cadizjavier** [mapbox/DEPRECATED-mapbox-ios-sdk#526]
I'm using the offline MBTiles tilesource without troubles. Right now i set the mapview constraints programatically. But reading the mbtiles spec there is a metadata table that already have that specific info, including minzoom, maxzoom, center etc.
The metadata isn't loading. Is this the correct behavior or i'm doing something wrong ?

**Comment by incanus** [comment]
@cadizjavier No, this data doesn't get applied to pan constraints automatically. Zoom info does, however. You should be able to grab a tile source's bounding box (MBTiles included) and pass it to the map view's constraints, though.
