### ISSUE TITLE
Error in logs from DB when i use .mbtiles file for tilesSource

### ISSUE THREAD

**Issue by glebpreger** [mapbox/DEPRECATED-mapbox-ios-sdk#527]
Can you help me, why i catch this logs errors and how can i disable them?

2014-10-14 22:04:10.606 myapp[7479:60b] DB Error: 1 "near "-": syntax error"
2014-10-14 22:04:10.607 myapp[7479:60b] DB Query: PRAGMA cache-size=100
2014-10-14 22:04:10.608 myapp[7479:60b] DB Path: /var/mobile/Applications/CF7D7C51-50EF-4477-991B-30C65CDA33F4/Documents/RMTileCache.db

I use latest SDK binary 1.4.1
My init code:

tilesSource = [[RMMBTilesSource alloc] initWithTileSetURL:[[NSBundle mainBundle] URLForResource:@"map" withExtension:@"mbtiles"]];
    mapView = [[RMMapView alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, self.view.frame.size.height) andTilesource:tilesSource];

```
[mapView setConstraintsSouthWest:CLLocationCoordinate2DMake(tilesSource.latitudeLongitudeBoundingBox.southWest.latitude, tilesSource.latitudeLongitudeBoundingBox.southWest.longitude) northEast:CLLocationCoordinate2DMake(tilesSource.latitudeLongitudeBoundingBox.northEast.latitude, tilesSource.latitudeLongitudeBoundingBox.northEast.longitude)];

[mapView setMaxZoom:tilesSource.maxZoom];
[mapView setMinZoom:tilesSource.minZoom];

UIView *backgroundView = [[UIView alloc] initWithFrame:mapView.bounds];
[backgroundView setBackgroundColor:[CBTFunctions getColorFromHex:@"#FCFBE7"]];
[mapView setBackgroundView:backgroundView];
[mapView setZoom:tilesSource.minZoom animated:NO];
[mapView setCenterCoordinate:tilesSource.centerCoordinate animated:NO];
[mapView setShowLogoBug:NO];
[mapView setHideAttribution:NO];
[mapView setDelegate:self];
[mapView setAdjustTilesForRetinaDisplay:YES];
[self.view insertSubview:mapView belowSubview:topBar];
```

**Comment by incanus** [comment]
This looks like FMDB verbosity. Without checking out your exact MBTiles I can't quite say, but I think a `Release` build should get rid of these in production.

**Comment by glebpreger** [comment]
Thanks for the answer

**Comment by briandeanlee** [comment]
I had this issue show up while updating from an older version to 1.4.1.  I needed to change the dash to an underscore so that the query says "PRAGMA cache_size=100" in:  RMDatabaseCache.m in the configureDBForFirstUse method.
/blee/

**Comment by bleft** [comment]
just updated to 1.5 and still getting this error:
Opening database at /Users/......./Documents/RMTileCache.db
2015-01-27 13:12:46.622 enerQuick[4647:918667] DB Error: 1 "near "-": syntax error"
2015-01-27 13:12:46.622 enerQuick[4647:918667] DB Query: PRAGMA cache-size=100

**Comment by incanus** [comment]
Fixed in https://github.com/mapbox/mapbox-ios-sdk/pull/558.
