### ISSUE TITLE
ios8 zooming bug

### ISSUE THREAD

**Issue by Rimins** [mapbox/DEPRECATED-mapbox-ios-sdk#529]
This is part of my code:
 CLLocationCoordinate2D southWest = CLLocationCoordinate2DMake(farSouthLatitude, farWestSouthLongtitude);
    CLLocationCoordinate2D northEast = CLLocationCoordinate2DMake(farNorthLatitude, farEastNorthLongtitude);  
 [self.mapView_ zoomWithLatitudeLongitudeBoundsSouthWest: southWest northEast: northEast animated:YES];
    CLLocationCoordinate2D projectedOrigin = [self.mapView_ projectedPointToCoordinate:self.mapView_.projectedOrigin];
    UIAlertView *alert = [[UIAlertView alloc] init];
    NSString \* coordMessage = [NSString stringWithFormat:@"southWest - latitude = %f, longtitude = %f;\n northEast - latitude = %f, longtitude = %f;\n boundsOrigin - latitude = %f, longtitude = %f", southWest.latitude, southWest.longitude, northEast.latitude, northEast.longitude, projectedOrigin.latitude, projectedOrigin.longitude];
    NSLog(coordMessage);
This code running in viewWillAppear of my controller.

This is NSLog for iOS7:
southWest - latitude = -16.849926, longtitude = -6.628284;
 northEast - latitude = -15.051765, longtitude = -4.757849;
 boundsOrigin - latitude = -14.909353, longtitude = -6.628217
Computing zoom is OK:)

But in iOS8 log:
southWest - latitude = -16.849926, longtitude = -6.628284;
 northEast - latitude = -15.051765, longtitude = -4.757849;
 boundsOrigin - latitude = 85.051129, longtitude = -180.000000

As you see the projectedOrigin is broken and this is a big trouble for me:(.

**Comment by mrabenhorst** [comment]
I believe this related to the same problem causing issue #502

**Comment by incanus** [comment]
Yes @Rimins can you clarify if you see this just on 64-bit?
