### ISSUE TITLE
[Bug] About takeSnapshot on ios 8.0

### ISSUE THREAD

**Issue by ReyLiang** [mapbox/DEPRECATED-mapbox-ios-sdk#533]
I Found a bug about [MapView takeSnapshot].
I run my code on ios 7.0.1(iphone 5s),"takeSnapshot" can run.but run code on ios 8.0 (iphone6&6 Plus). it run error.

error happend on this line "[self.layer renderInContext:UIGraphicsGetCurrentContext()];"
error is "Assertion failed: (transform_is_valid(m)), function CGPathRef CGPathCreateWithRect(CGRect, const CGAffineTransform *), file Paths/CGPath.cc, line 179."

I search Google, they introduced a bug on the renderInContext when the view contains 0 in the width.

So.I do something,fix this bug.
- (UIImage *)takeSnapshotAndIncludeOverlay:(BOOL)includeOverlay
  {
  _overlayView.hidden = !includeOverlay;
  
  UIGraphicsBeginImageContextWithOptions(self.bounds.size, self.opaque, [[UIScreen mainScreen] scale]);
  
  for (RMMapTiledLayerView *tiledLayerView in _tiledLayersSuperview.subviews)
  {
      tiledLayerView.useSnapshotRenderer = YES;
  }
  
  NSMutableArray \* tempRemoveLayers = [[NSMutableArray alloc] init];
  
  //get all subLayers
  for (CALayer \* layer in self.layer.sublayers) {
      [tempRemoveLayers addObject:layer];
  }
  
  //remove empty layer , don't know why
  //Assertion failed: (transform_is_valid(m)), function CGPathRef CGPathCreateWithRect(CGRect, const CGAffineTransform *), file Paths/CGPath.cc, line 179.
  for (CALayer \* layer in tempRemoveLayers) {
      if (layer.bounds.size.width == 0 || layer.bounds.size.height == 0 || layer.bounds.origin.x == 0) {
          [layer removeFromSuperlayer];
      }
  
  }
  
  [self.layer renderInContext:UIGraphicsGetCurrentContext()];
  
  //remove snapshot layers
  //if dont remove, mapview will empty, no tile show.
  for (CALayer \* layer in tempRemoveLayers) {
      if (layer.bounds.size.width != 0 && layer.bounds.size.height != 0 && layer.bounds.origin.x != 0) {
          [layer removeFromSuperlayer];
      }
  }
  
  for (RMMapTiledLayerView *tiledLayerView in _tiledLayersSuperview.subviews)
      tiledLayerView.useSnapshotRenderer = NO;
  
  UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
  
  UIGraphicsEndImageContext();
  
  _overlayView.hidden = NO;
  
  //if add removed layers to mapview
  for (CALayer \* layer in tempRemoveLayers) {
      [self.layer addSublayer:layer];
  }
  
  return image;
  } 

I'm not sure that is right.

**Comment by incanus** [comment]
@ReyLiang Thanks for finding & researching this. Is there any way that you could contribute you code as a concise pull request for easier testing and possible integration?

**Comment by ReyLiang** [comment]
sorry..
today I found my error.
because I do this:
-(RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation
{

```
if (annotation.isUserLocationAnnotation) {

    RMMarker * topMarker = [[RMMarker alloc] initWithUIImage:[UIImage imageNamed:@"mapview_locationtop"]];
    RMMarker * marker = [[RMMarker alloc] initWithUIImage:[UIImage imageNamed:@"mapview_location"]];
    [marker addSublayer:topMarker];

    topMarker.position = CGPointMake(marker.bounds.size.width / 2.0, marker.bounds.size.height / 2.0);

    return marker;
}

return nil;
```

}

I set topMarker.bounds , error is solved.
