### ISSUE TITLE
RMDatabaseCache causes exponential memory increase

### ISSUE THREAD

**Issue by Bhide** [mapbox/DEPRECATED-mapbox-ios-sdk#535]
I am trying my luck using Mapbox to download maps for offline usage. But hard luck. There's an exponential increase in memory usage and the app crashes eventually.

I am doing this.
RMMapboxSource *onlineSource = [[RMMapboxSource alloc] initWithMapID:kMapboxMapID];

```
RMMapView *mapView = [[RMMapView alloc] initWithFrame:self.view.bounds andTilesource:onlineSource];

CLLocationCoordinate2D coordinate = CLLocationCoordinate2DMake(19.474317, 72.829907);

mapView.zoom = 50;
mapView.maxZoom = 50;
```

for (id cache in mapView.tileCache.tileCaches)
    {
        if ([cache isKindOfClass:[RMDatabaseCache class]])
        {
            RMDatabaseCache *dbCache = (RMDatabaseCache *)cache;
            NSLog(@"current cache size: %lld", dbCache.fileSize);
            if (dbCache.fileSize < 20000)
            {
                [mapView.tileCache setBackgroundCacheDelegate:self];
                NSInteger minZoom = tileSource.minZoom;
                NSInteger maxZoom = tileSource.maxZoom; // here I am fetching all but this might be too much
                [mapView.tileCache beginBackgroundCacheForTileSource:tileSource southWest:tileSource.latitudeLongitudeBoundingBox.southWest northEast:tileSource.latitudeLongitudeBoundingBox.northEast minZoom:minZoom maxZoom:maxZoom];
            }

```
        break;
    }
}
```

But the memory shoots and app crashes. 
Anybody can help me ?? Thanks in advance.

**Comment by incanus** [comment]
Also on SO: http://stackoverflow.com/questions/26841671/rmdatabasecache-causes-exponential-memory-increase

**Comment by incanus** [comment]
``` objc
mapView.zoom = 50;
mapView.maxZoom = 50;
```

I'm not sure you want to do this. This is millions of times larger than the highest level of detail supported by MapKit.

**Comment by dinagaffney35** [comment]
#535#

-----Original Message-----
