### ISSUE TITLE
No custom defined polygons on Mapview

### ISSUE THREAD

**Issue by satheeshiOS** [mapbox/DEPRECATED-mapbox-ios-sdk#536]
Hi All,

I am getting the following error and didn't get the layers what i have drawn in the Mapbox,

DB Error: 1 "near "-": syntax error"
2014-11-11 17:17:53.918 Mawgif[50383:368773] DB Query: PRAGMA cache-size=100
2014-11-11 17:17:53.918 Mawgif[50383:368773] DB Path: /FFFF/FFFFFf/Library/Developer/CoreSimulator/Devices/0B1A047E-AA65-4B48-A37D-FBFAEB34EC7F/data/Containers/Data/Application/D542B1B7-89EA-49D3-9006-745297FF8B50/Documents/RMTileCache.db

I initialized my map view on viewsappear

RMMapboxSource *tileSource = [[RMMapboxSource alloc] initWithMapID:@"My map id"];

RMMapView *mapView=[[RMMapView alloc] initWithFrame:self.view.bounds andTilesource:tileSource centerCoordinate:CLLocationCoordinate2DMake(21.481888200000000000, 39.182974199999990000) zoomLevel:11 maxZoomLevel:1000 minZoomLevel:11 backgroundImage:nil];

[mapView addTileSource:[[RMMapboxSource alloc] initWithMapID:@"My map id" enablingDataOnMapView:mapView]];

mapView.delegate = self;

[self.view addSubview:mapView];
I am using iOS 8.1,iPhone 5s and map box version 1.4.1

Please help me to get rid of this.

**Comment by briandeanlee** [comment]
Please see: https://github.com/mapbox/mapbox-ios-sdk/issues/527

Seems to happen after upgrading to 1.4.1,  but it's an easy fix.

Brian Lee

/blee/
