### ISSUE TITLE
Be clearer about ios_sdk.sh

### ISSUE THREAD

**Issue by tmcw** [mapbox/DEPRECATED-mapbox-ios-sdk#537]
![2014-11-11 at 3 34 pm](https://cloud.githubusercontent.com/assets/32314/5000295/4bdc6f24-69b8-11e4-9003-cf5d46d86221.png)

This isn't clear enough for most people: specify in a terminal, where, how to run it.

**Comment by incanus** [comment]
I'm not sure if we can improve on this. The script is located at [the top of the repo](https://github.com/mapbox/mapbox-ios-sdk/blob/release/install_docs.sh) and is run by doing: 

``` bash
./install_docs.sh
```

i.e. how much more can we say about how to run a shell script?
