### ISSUE TITLE
Text on the bottom of text field - can't see what I'm writing

### ISSUE THREAD

**Issue by theerror** [mapbox/DEPRECATED-mapbox-ios-sdk#538]
When I'm editing user notes on Waypoints for example, (or some another text input field) and keyboard shows up, I' m unable to write at the end of log/text boxes. When keyboard shows up, it hide rest of text, so I can't see what I'm writing on bottom of this text fields.

The most problematic case is for example in waypoints in multicache, where coordinates to fill final stage are on the bottom of text field, I'm unable to fill it in. More screenshot
![img_0326](https://cloud.githubusercontent.com/assets/4508328/5007243/326d5ed0-6a4f-11e4-86db-bd7861379751.PNG)
![img_0327](https://cloud.githubusercontent.com/assets/4508328/5007242/326d48dc-6a4f-11e4-9577-9491e1b4f59c.PNG)

**Comment by incanus** [comment]
This is the wrong project.
