### ISSUE TITLE
Launching with no internet connection causes crash

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#54]
RMTileCache crashes if you try to instantiate a map view with a source from a URL, and there's no data connection.

**Comment by incanus** [comment]
See also alpstein/route-me#88

**Comment by russellquinn** [comment]
Right, possibly the bigger problem is mapbox-me having that as the reference code ;)

**Comment by incanus** [comment]
Let me know if you still see this in develop, but I can't replicate.

**Comment by russellquinn** [comment]
This now seems fixed. MapView no longer crashes if you pass in a a null RMMapBoxSource.
