### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by tgallende** [mapbox/DEPRECATED-mapbox-ios-sdk#543]
Hi,
I just updated to the new version of map box-ios-sdk in order to compile for arm64 architecture. I have changed the Mapview project settings - iOS deployment target 7.0- but I still get  the same errors:Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RMAnnotation", referenced from:
      objc-class-ref in TXSelecMapaViewController.o
      objc-class-ref in TXMapaUbicacionViewController.o
      objc-class-ref in TXMapaGeneralViewController.o
      objc-class-ref in TXMapaSemiModalViewController.o
      objc-class-ref in TXMapaPOIViewController.o
      objc-class-ref in TXMapaInteractivoViewController.o
      objc-class-ref in TXMapaRutaDiaViewController.o
      ...
  "_OBJC_CLASS_$_RMMBTilesSource", referenced from:
      objc-class-ref in TXSelecMapaViewController.o
      objc-class-ref in TXMapaUbicacionViewController.o
      objc-class-ref in TXMapaGeneralViewController.o
      objc-class-ref in TXMapaSemiModalViewController.o
      objc-class-ref in TXMapaPOIViewController.o
      objc-class-ref in TXMapaInteractivoViewController.o
      objc-class-ref in TXMapaRutaDiaViewController.o
      ...
  "_OBJC_CLASS_$_RMMapView", referenced from:
      objc-class-ref in TXSelecMapaViewController.o
      objc-class-ref in TXMapaUbicacionViewController.o
      objc-class-ref in TXMapaGeneralViewController.o
      objc-class-ref in TXMapaSemiModalViewController.o
      objc-class-ref in TXMapaPOIViewController.o
      objc-class-ref in TXMapaInteractivoViewController.o
      objc-class-ref in TXMapaRutaDiaViewController.o
      ...
  "_OBJC_CLASS_$_RMMarker", referenced from:
      objc-class-ref in TXSelecMapaViewController.o
      objc-class-ref in TXMapaUbicacionViewController.o
      objc-class-ref in TXMapaGeneralViewController.o
      objc-class-ref in TXMapaSemiModalViewController.o
      objc-class-ref in TXMapaPOIViewController.o
      objc-class-ref in TXMapaInteractivoViewController.o
      objc-class-ref in TXMapaRutaDiaViewController.o
      ...
  "_OBJC_CLASS_$_RMShape", referenced from:
      objc-class-ref in TXMapaRutaDiaViewController.o
      objc-class-ref in TXVentanaMapaController.o
      objc-class-ref in TXResumenRutaOfflineViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

What am I missing? Thanks a lot.....

**Comment by tgallende** [comment]
I forgot to comment  I integrated the sdk including the source code, dragging the MapView project into mine.

**Comment by incanus** [comment]
Double-check your build architectures for the `MapView` sub-project. I suspect they might have gotten overridden. The default is to build for 64-bit. 

https://github.com/mapbox/mapbox-ios-sdk/blob/7efc5320bfc9600d411ead5f861309517e89fd34/MapView/MapView.xcodeproj/project.pbxproj#L1063

**Comment by tgallende** [comment]
Hi incanus,
I just checked it. The build architectures where set to $(ARCHS_STANDARD_INCLUDING_64_BIT) as you said, the error is still here. Any other idea?

**Comment by incanus** [comment]
@tgallende How is it resolving in Xcode? i.e. here: 

![screen shot 2014-11-25 at 1 40 14 pm](https://cloud.githubusercontent.com/assets/17722/5192028/a61c3866-74a8-11e4-94f4-e56b5023cc7e.png)

**Comment by tgallende** [comment]
This way:
![image](https://cloud.githubusercontent.com/assets/4180020/5192235/025b3d50-74f6-11e4-957c-a6cc294b8675.png)
I have also tried adding manually armv7s but the result is the same....

**Comment by incanus** [comment]
Ok, can you upload your build log then? 

Copy & paste all into something like http://gist.github.com. 

![screen shot 2014-11-25 at 2 50 26 pm](https://cloud.githubusercontent.com/assets/17722/5193110/724aea64-74b2-11e4-9756-7c2bd75d2c86.png)

**Comment by tgallende** [comment]
Hi Justin,
I eventuallly discovered the problem, Thnaks to this question:
http://stackoverflow.com/questions/18408531/xcode-build-failure-undefined-symbols-for-architecture-x86-64?answertab=votes#tab-top
When I updated the MapView project to the last version in github the libMapBox.a dissapeared from Link With libraries in Build Phases. I was focused on x64 but the problem had nothing to do with that, just as simple as adding the library...... 2 days for this!!! 
Thanks ffor your time, i really appreciate your answers.

**Comment by incanus** [comment]
Glad to hear it's resolved!
