### ISSUE TITLE
Crash when i am drawing multiple line on map view.

### ISSUE THREAD

**Issue by tarun567** [mapbox/DEPRECATED-mapbox-ios-sdk#546]
Hi,

I am using MapBox open source SDK.

I am drawing multiple route on map view with help of  - 

 RMPath *drawPath = [[RMPath alloc] initWithContents:contents];
    [drawPath setLineColor:lineColor];
[[mapView.contents overlay] addSublayer:drawPath];

And when i will zoom and un zoom 3 or 4 times application crashed.

can you help me regarding this problem or any other way  draw route on map.

Thanks

**Comment by incanus** [comment]
You shouldn't add layers directly to the map, but rather return them from the `RMMapViewDelegate` method so that the map view can manage them.
