### ISSUE TITLE
Check for NSLocationWhenInUseUsageDescription ignores localized version

### ISSUE THREAD

**Issue by migo** [mapbox/DEPRECATED-mapbox-ios-sdk#548]
For iOS 8, there is now a check in RMMapView to see if the needed String is provided.
The check is as follows:

```
NSAssert([[[NSBundle mainBundle] infoDictionary] valueForKey:@"NSLocationWhenInUseUsageDescription"], @"For iOS 8 and above, your app must have a value for NSLocationWhenInUseUsageDescription in its Info.plist");
```

This only works if the String is provided in the mainBundle (info.plist). However, the string can also be provided in a localized version (in InfoPlist.strings) so that different languages can be supported.

Please change the check so that localized strings are also detected.

**Comment by taylortrimble** [comment]
Related, from the Bundle Programming Guide:

> The `NSBundle` class provides the `objectForInfoDictionaryKey:` and `infoDictionary` methods for retrieving information from the `Info.plist` file. The `objectForInfoDictionaryKey:` method returns the localized value for a key and is the preferred method to call. The `infoDictionary` method returns an `NSDictionary` with all of the keys from the property list; however, it does not return any localized values for these keys. For more information, see the _NSBundle Class Reference_.

**Comment by incanus** [comment]
Ah, thanks for flagging this.

**Comment by incanus** [comment]
Merged.
