### ISSUE TITLE
Compass tracking issues

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#55]
1. The rotation of the map is wrong for anything other than portrait orientation. (It's out by the number of degrees the device has been physically rotated.)
2. Changing the orientation of the view while compass tracking correctly keeps the confidence circle centered, but the blue dot is not re-centered (screenshot: https://dl.dropbox.com/u/44154592/compassRotating.png)
3. The blue dot doesn't change to use the compass tracking graphic used in Maps.
4. Less important, but the rotation is very jerky compared to Maps.

**Comment by incanus** [comment]
See also #40.

**Comment by incanus** [comment]
For 1., sorry if I'm being dense here, but does it behave differently from Maps.app?

**Comment by russellquinn** [comment]
Yep, Maps rotates the view, but north is still north. If you rotate a MapBox map, then north is no longer north.

**Comment by russellquinn** [comment]
(I'll email you a video.)

**Comment by incanus** [comment]
1. Still working on it. 
2. Thanks for this. Should be fixed above. 
3. Not sure what you mean. 
4. Will try to get to this.

**Comment by russellquinn** [comment]
1. I just mean that in Maps.app there's a "flashlight path" graphic around the blue dot showing that it's in "compass mode," which MapBox doesn't have. It's pretty useful as a reminder that you're in compass mode, etc.

**Comment by incanus** [comment]
You should have that -- are you copying all of the `Resources` into your app? While we don't have the varying widths on the path representing relative heading accuracy (yet), we do have one image in there that looks pretty good IMHO.

**Comment by russellquinn** [comment]
True, yes, but it's not showing. I'm pulling the latest from Develop straight into my project. The image is there and I single-stepped though the part where it's loaded and added to the view and, it loads properly, but it's not visible. I just get a naked blue dot in heading mode.

**Comment by incanus** [comment]
Hmm, I've never seen that before. This is on device, yes, so as to not be faking compass mode?

**Comment by russellquinn** [comment]
Yep, on both a real iPad and iPhone. Check out the latest beta of our app? Most of these things I'm reporting are demonstrable there.

**Comment by incanus** [comment]
Yeah, seeing the lack of path image. Can't replicate that either :-) Will keep at it.

**Comment by russellquinn** [comment]
You mean, you're seeing no path image in our app beta, but can't replicate it in other SDK uses?

**Comment by incanus** [comment]
I'm seeing no image in your beta, but I can't get it to happen anyplace else.

**Comment by incanus** [comment]
Re: the path image, can you double-check a couple things? 
1. Does the `alpha` ever get set to 1.0? See https://github.com/mapbox/mapbox-ios-sdk/blob/develop/MapView/Map/RMMapView.m#L2616-2620
2. What is the ordering like on the `RMMapView` subviews? I.e., is the path image on top of the scroll view, overlay view, etc. 
3. Try debug-printing the `position`/`frame`/`bounds` of the image view in question and make sure it's sane.

**Comment by incanus** [comment]
I just realized my misunderstanding of your north/rotation issue -- I've been looking at iPhone apps that don't rotate with device orientation. Thanks, your video was helpful there. On it.

**Comment by incanus** [comment]
Ok, as of 8d84650719c907a6b9b5597d02b43668da1869cd and d4adab7d022c0933e0b15a7b9e75cf091070f6ae, there should be proper device orientation compensation, as well as some other nice improvements to heading updates. I _think_ that other than the animation jerkiness (which I might spin off into another, lower priority ticket), we just have your app's specific problem with the heading graphic now. 

Just to confirm, you see this behave properly over in [MapBox Me](https://github.com/mapbox/mapbox-me), right? I.e., your experience matches the [screenshot](https://raw.github.com/mapbox/mapbox-me/master/screenshot.png)?

**Comment by russellquinn** [comment]
Observations, based on latest MapBox Me (and latest SDK from 'develop' branch):
1. The rotation of the map is still wrong when the device is orientated.
2. When in heading mode, the blue dot now stays centered when rotating the device, but the accuracy circle disappears, then flies in again from off screen.
3. When rotating the device and NOT in heading tracking mode, the blue dot also animates in from an incorrect location, as described in 2.
4. Entering heading tracking mode, then swiping, rotating, etc. a bunch until the mode cancels often leaves it in a state where pinch-zooming no longer works.
5. The heading graphic DOES appear in MapBox Me. I'll try investigating why it doesn't in our app further.

**Comment by incanus** [comment]
I'm not changing MapBox Me, FWIW, right now -- just the SDK.

**Comment by russellquinn** [comment]
I was using MapBox Me with the latest SDK. All these issues (except 5) are the same with the latest SDK in our app too.

**Comment by incanus** [comment]
Man, I just can't replicate any of these in testing on a iPhone 4S and iPad 3. Hmm.

**Comment by russellquinn** [comment]
Well, a little bit of good news, I removed the SDK from our app and re-added, and the heading graphic now appears! So that's no longer a problem.

**Comment by incanus** [comment]
I'm guessing maybe the image thing was related to a reference link that went awry somehow and not an actual copy into the project (which is fine; I do the reference myself).

**Comment by incanus** [comment]
Re: device orientation, does it work any better in 451bbc0d840cba93f0fc9018f1f5da4ae0f8a901 and before?

**Comment by incanus** [comment]
Definitely nailed a bug here now in bf9054ddd84b027492fe5caf2cb220330c4ddd9f.

**Comment by incanus** [comment]
Re: the accuracy circle swooping in, this is a general annotation issue that I filed upstream in alpstein/route-me#95. Not sure what to do there yet.

**Comment by russellquinn** [comment]
Device orientation / heading tracking seems to be working now!!

**Comment by incanus** [comment]
Cool, so I think we're set here now that smooth animation is over in #84?

**Comment by russellquinn** [comment]
If the animation problem when rotating is a Route-Me problem then I guess so, yeah. Did we fix:

Entering heading tracking mode, then swiping, rotating, etc. a bunch until the mode cancels often leaves it in a state where pinch-zooming no longer works.

?

**Comment by incanus** [comment]
Whoops, yeah, missed that (lotta stuff here). Will leave open.

**Comment by incanus** [comment]
Ok, going to close this lengthy ticket in favor of piecing the remaining tasks out. 
- #79 frozen tracking mode
- #84 smoother map heading rotation
- alpstein/route-me#95 annotations flying in on device rotation

Let me know if I missed any other outstanding issues here.
