### ISSUE TITLE
Merge Two tiles on RMMapView and shake annotation and polyline 

### ISSUE THREAD

**Issue by tarun567** [mapbox/DEPRECATED-mapbox-ios-sdk#552]
Hi,

I have two url of tiles,Can i merge two tiles in one map view ? Basically I want hybrid maps including street and satellite tiles.
My satellite url is .

http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/17/54681/93669

and  Street tiles are coming as transparent images,it have only names 

http://mapm.mapmyindia.com/map-india?fun=labels&lwM=57616337.000000&twM=22226993.000000&zf=16.000000&ssf=1

is there any possibilities ?

and my second issue is  - 
I am using RMAnnotaion  for add marker and polyline with help of RMShape and RMMarker,
But when i am doing scroll or zoom then they are shaking to their position.

is there any solution ?

Thanks

**Comment by incanus** [comment]
Tile merging: You can add multiple tile sources to `mapView.tileSources`, or you can look into `RMCompositeSource`, which composites the layers' pixels together and then caches the result. 

Re: shaking, this is covered here: https://github.com/mapbox/mapbox-ios-sdk/issues/72
