### ISSUE TITLE
CRS.simple

### ISSUE THREAD

**Issue by romeo4934** [mapbox/DEPRECATED-mapbox-ios-sdk#556]
Dear all,
I have tiles with L.CRS.simple
I was wondering if we could use mapbox-ios-sdk ?, Do I need to tweak some method? Which method RMProject ? @incanus ?
Thank you so much for your answer!
Best regards,
Antoine

**Comment by incanus** [comment]
Hello @antoineherzog. Despite the presence of `RMProjection`, this library doesn't support projections other than Spherical Mercator.

**Comment by romeo4934** [comment]
Thank you for your fast answer @incanus  ;) 
Do you think it will be easy to do a pull request to update the repo to enable a simple L.CRS.simple projection ?
Best regards,
Antoine

**Comment by incanus** [comment]
I don't know — I don't know enough about that projection. As long as it works with a square map, though, I think it might be doable. Our SDK is based on a square content view in a `UIScrollView`. 

You might look at Leaflet's SRS's to determine what's involved as a model.

**Comment by romeo4934** [comment]
it is do indoor mapping, so it is pretty basic, we should just remove the conversion between lat long coordinate to projection point?
