### ISSUE TITLE
error when building cocoapods version

### ISSUE THREAD

**Issue by mackuba** [mapbox/DEPRECATED-mapbox-ios-sdk#559]
I've added `Mapbox-iOS-SDK` to the `Podfile` and called `pod install`. It installed everything correctly. Then I tried to build it, but it failed. Apparently MapBox pulls several other pods as dependencies, and one of them - GRMustache - displays a build error: "Semantic issue - Too many arguments to a function call, expected 0, have 3" (GRMustacheContext.m:650).

**Comment by jcmendez** [comment]
Same issue here.  Is this fixed by https://github.com/albertschulz/mapbox-ios-sdk/commit/5800bce094d8b36528e7897e81ff33d1bb7cc3c2 ?

**Comment by albertschulz** [comment]
Yes, that was the reason for the update

**Comment by cguess** [comment]
Has this been merged? The Cocoapods version still requires 6.8.3

**Comment by jcmendez** [comment]
I don't think so.  I have been able to work on my project with the podspec
I checked in on my forked repo.

Would love to hear from the mapbox folks.  Looking at the commit dates, it
seems not much love is coming to this sdk.  Maybe there is more effort
going into the GL-vector based mapping sdk?  Just speculating...

On Mon, Jan 19, 2015 at 12:18 PM, Christopher Guess <
notifications@github.com> wrote:

> Has this been merged? The Cocoapods version still requires 6.8.3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapbox/mapbox-ios-sdk/issues/559#issuecomment-70529147
> .

## 

_Juan C. Méndez_
+1-954-205-6824
+1-706-363-3952 (+1-70-MENDEZ-JC)
http://jcmendez.info
@jcmendez_us

**Comment by incanus** [comment]
Hmm, this shouldn't be causing a fatal problem. Will take a look. 

You are correct @jcmendez that the main focus right now is the GL SDK, which will replace this project as well as MBXMapKit eventually. Think of it as SDK 2.0 though...

**Comment by incanus** [comment]
Closing as GRMustache has been updated in the recent releases. Someone post back if still seeing a problem here.

**Comment by GHrama** [comment]
I am still getting the same error,what can I do?

**Comment by incanus** [comment]
@GHrama can you paste the exact error you are seeing?

**Comment by mitchellporter** [comment]
I am still seeing this same error that @mackuba was experiencing using Xcode 7. I installed the pod by adding the following line to my pod file: `pod 'MapBox', '~> 1.1'`

Any ideas how to install via cocoapods but avoid this error?

**Comment by friedbunny** [comment]
@mitchellporter You'll want something more like this in your `Podfile`:

``` ruby
pod 'Mapbox-iOS-SDK', '~> 2.0'
```

Also check out the [install guide section on Cocoapods](https://www.mapbox.com/ios-sdk/#cocoapods).

**Comment by friedbunny** [comment]
... hrm, sorry. That advice assumes you want the new iOS SDK (which you should).

Presuming you want the old SDK, set the version to `1.6` or so.

**Comment by mitchellporter** [comment]
@friedbunny Unfortunately I have to use the old SDK for now.

I noticed the old SDK has both a `1.6.0` and a `1.6.1`

Do I need to use pod `'MapBox', '~> 1.6.1'` to get the most recent version or should it be pod `'MapBox', '~> 1.6'`?

I realize that's more of a cocoapods question but I've never had to modify the version before.

**Comment by friedbunny** [comment]
The [`'MapBox'` cocoapod](https://cocoapods.org/pods/MapBox) was deprecated at 1.1.0, so that'll be rather old and difficult to predict behavior-wise.

The old raster SDK (this repo) became the [`Mapbox-iOS-SDK` pod](https://cocoapods.org/pods/Mapbox-iOS-SDK), which has been taken over by the [GL SDK](https://github.com/mapbox/mapbox-gl-native) as of version 2.0. 

To get the latest release of this raster SDK, pin to version 1.6-and-above:

``` ruby
pod 'Mapbox-iOS-SDK', '~> 1.6'
```

This will get you any potential 1.x updates but not update you to 2.0. Using `~> 1.6.1` would keep you at 1.6.x, if you prefer. See [this section](http://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions) of the Cocoapods guide for more information on version pinning syntax.

**Comment by mitchellporter** [comment]
@friedbunny Thanks for the help I'm up and running with 1.6.1 and everything works perfectly cheers!
