### ISSUE TITLE
I want to use a multi-threaded tile download

### ISSUE THREAD

**Issue by conpota** [mapbox/DEPRECATED-mapbox-ios-sdk#56]
// blocking
UIImage *tileImage = [[mapView tileSource] imageForTile:RMTileMake(x, y, zoom) inCache:[mapView tileCache]];

**Comment by incanus** [comment]
@conpota, have a look at the `develop-bench` branch for some work here. In particular, try `mapView.asynchronousRedraw = YES` and `mapView.missingTilesDepth = 1` and see how that works for you. You can track related progress on this issue at alpstein/route-me#35
