### ISSUE TITLE
MBTiles vector tiles support

### ISSUE THREAD

**Issue by cadizjavier** [mapbox/DEPRECATED-mapbox-ios-sdk#567]
Is there any plan to support vector tiles in the Mapbox iOS SDK.
Looking at the [Mapbox GL FAQ](https://github.com/mapbox/mapbox-gl-cocoa/blob/master/FAQ.md) it seems that in the future will be some kind of integration between Mapbox GL and the Mapbox iOS SDK.
What is the roadmap on this ?
I'm specially interested in the offline support through local MBTiles.

**Comment by ljbade** [comment]
There is an issue for offline support over at Mapbox GL https://github.com/mapbox/mapbox-gl-native/issues/584

**Comment by incanus** [comment]
@cadizjavier GL will replace the iOS SDK when it's mature, so MBTiles support will come in that project.
