### ISSUE TITLE
Class method +configuration not allowed in Swift

### ISSUE THREAD

**Issue by jonastreub** [mapbox/DEPRECATED-mapbox-ios-sdk#568]
When using Mapbox in a Swift project, it's impossible to use `[RMConfiguration configuration]`, since Swift does not generate an appropriate method for this (see also [this SO answer](http://stackoverflow.com/a/24367632)).

Giving it a slightly different method name would work.

**Comment by JohnRbk** [comment]
Same issue here. If you want a short-term workaround, here is what I did:

I created an RMConfiguration category (something like `RMConfiguration+Workaround.m` and `RMConfiguration+Workaround.h`) in Objective-C. Within the category definition, implement an alias for the `configuration` class-member method using some other name. After including the category in your bridging header, you can easily call the alias in Swift.

**Comment by incanus** [comment]
Oh, interesting. Thanks for this flag @jonastreub. This comes from the upstream project, and though I haven't typically liked to diverge in past for little things, this makes sense now because: 
1. This is an oddly-named singleton. 
2. Upstream is no longer an active project. 

I'll get a fix in for this.

**Comment by incanus** [comment]
Ok, give the above branch a try and see how it works for you @jonastreub @JohnRbk? This seems to be a Swift compiler hinting issue as structurally, this is the same — I just called it `sharedInstance` now. 

``` swift
RMConfiguration.sharedInstance().accessToken = "pk......"
```

**Comment by incanus** [comment]
More on this: 

http://stackoverflow.com/questions/24148464/how-to-call-an-objective-c-singleton-from-swift

> A followup: because class methods like `+[XYZThing thing]` are treated like initializers by the ObjC to Swift translator (even if that doesn't seem to fully work right now), that naming pattern is a bad idea for singletons.

**Comment by JohnRbk** [comment]
I ran a quick test and it seems like your update works. Without any call to set the accessToken, running a proxy shows my app making requests to  `https://api.tiles.mapbox.com/v3/...`

I added the following line:

`RMConfiguration.sharedInstance().accessToken = "<<API KEY>>"`

...and I can see API calls to `https://api.tiles.mapbox.com/v4/...`

Seems like it works fine.

Thanks for the fix.

**Comment by jonastreub** [comment]
@incanus Thanks for the quick fix!

**Comment by incanus** [comment]
Ok, merged into `develop` and will make it into the next release!
