### ISSUE TITLE
maxZoom beyond level 18

### ISSUE THREAD

**Issue by maciekish** [mapbox/DEPRECATED-mapbox-ios-sdk#569]
Hi,
Im having some issues zooming beyond zoom level 18 with our new satellite tiles. It seems like MapBox gets limited by the maximum UIScrollView zoom and caps out at 18.

Have i missed something? Is there any way to load tiles beyond level 18?

Thanks
Maciej

**Comment by maciekish** [comment]
Further digging reveals that the UIScrollView zoomScale is probably not to blame. I think the culprit is with this row in `drawLayer` in `RMMapTiledLayerView.m`:

```
float zoom    = log2(bounds.size.width / rect.size.width);
```

This value seems to cap out at 18 when zoomScale is 65535. Why?

**Comment by maciekish** [comment]
Furthermore it looks like iOS stops decreasing the rect size, `rect.size.width` is the same value if we try to zoom beyond zoom level 18.

**Comment by ljbade** [comment]
looks like a 16 bit number?

**Comment by maciekish** [comment]
Which one?

**Comment by ljbade** [comment]
The "65535" the maximum value of a 16bit unsigned integer. Are any of the variables 16bit numbers?

**Comment by maciekish** [comment]
I think zoomScale was a red herring, it continues well beyond 16 bits but it seems like the context size passed in by the UIScrollView never goes smaller than 0.0009765625 width and height.

Zoom level 16 is 0.00390625 x 0.00390625 (half that of 15)
Zoom level 17 is 0.001953125 z 0.001953125 (half that of 16)
Zoom level 18 is 0.0009765625 x 0.0009765625 (half that of 17)
Zoom level 19 is 0.0009765625 x 0.0009765625 (same as 18)
Zoom level 20 is 0.0009765625 x 0.0009765625 (same as 18)

This comes from `- (void)drawLayer:(CALayer *)layer inContext:(CGContextRef)context` in `RMMapTiledLayerView`

Looks like the UIScrollView is throwing in the towel?

**Comment by maciekish** [comment]
Turns out we never returned a `maxZoom` on the actual tile source itself. We only set the `maxZoom` on the RMMapView object which isn't enough. Once we started returning 19 for `maxZoom`in our tile source it just started working.

Closing this as a PEBKAC :)

**Comment by petaren** [comment]
As a developer using Mapbox, how do I increase the maxZoom from 18 on iOS?
