### ISSUE TITLE
RMPath marker doesn't rotate correctly

### ISSUE THREAD

**Issue by webventil** [mapbox/DEPRECATED-mapbox-ios-sdk#57]
When in user tracking mode, the RMPath Marker should rotate opposite the map. Because it is fixed with one point in due to RMAnnotation it doesn't rotate correctly.

**Comment by incanus** [comment]
I believe this is expected behavior, since a path or shape is specified in geo coordinates, and as such should rotate with the map, not opposite it. If you want a shape that does not move, use a view or layer on top of the map view. 

Feel free to re-open if I'm misunderstanding.

**Comment by webventil** [comment]
Yes, it should rotate in the same direction the map does. It rotates with the map, but only around the starting point. Maybe I'm doing something wrong. When i try to add a RMPath or RMShape, I create an RMAnnotation and add it to the map.
Since issue #50 was fixed, the rotation of "normal" annotations are working fine. 

RMAnnotation *pathAnnotation =  [RMAnnotation annotationWithMapView:mapView coordinate:[[routingPoints objectAtIndex:0] coordinate] andTitle:nil];  (when i only call the init method, the path will be created but at the west coast of Africa)

I pass the points of the pass as part of an NSDictionaory in pathAnnotation.userInfo.
In the layerForAnnotation delegate Method I create my RMPath or RMShape, and add the coordinates using the addLineToCoordinate function, but the path still rotates around this one point, i used for RMAnnotation.

**Comment by incanus** [comment]
Ah, I gotcha. I'll look at this.

**Comment by incanus** [comment]
I've got this fixed in upstream at alpstein/route-me#91. Look for this in `develop` momentarily, and thanks for the report.
