### ISSUE TITLE
get working with CocoaPods 0.36b & frameworks

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#580]
Per http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/ we need to get with the upcoming CocoaPods which works with dynamic frameworks and thus Swift. 

MBXMapKit checks out ok as-is, but is: 
- A much smaller project. 
- An easy naming scheme (`MBXMapKit` vs. `Mapbox-iOS-SDK`, which has illegal characters for Clang modules). 
- Far fewer headers. 
- No dependencies itself. 

Looks like we need stuff like: 
- Podspec `module_name = 'Mapbox_iOS_SDK'`
- Podspec `public_header_files` that lines up with [`Mapbox.h`](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/Mapbox.h)
- ??

**Comment by friedbunny** [comment]
CocoaPods 0.36.0 [was released today](http://blog.cocoapods.org/CocoaPods-0.36/) and nothing appears to be broken, at least.

When forcing the podfile into `use_frameworks!` mode everything compiles and runs, but we get `Apple Mach-O Linker Warning: Embedded dylibs/frameworks only run on iOS 8 or later` for each pod.

Using `#import "Mapbox.h"` still works, too.

**Comment by friedbunny** [comment]
ERrrrrrrrchhhhhhhhh. Hold up, looks like it's still got the old pods in there, too.

**Comment by friedbunny** [comment]
I think the existing podspec is good to go, with the optional addition of:

```
m.public_header_files = 'Mapbox.h'
```

~~Why not rename?~~
- ~~Changing the pod name would break consumers' existing podfiles (is my understanding)~~
- `Mapbox-iOS-SDK` automatically gets renamed to `Mapbox_iOS_SDK` where it matters, anyway

Have not yet tested this out in a Swift project.

**Comment by friedbunny** [comment]
`podfile` for testing:

```
pod 'Mapbox-iOS-SDK', :git => 'https://github.com/friedbunny/mapbox-ios-sdk.git', :branch => '0.36-cocoapods'
#pod 'mapbox-ios-sdk'

use_frameworks!
```

**Comment by friedbunny** [comment]
And Xcode is melting my brain.

In order to get the pod working as a framework we'll have to change most `[NSBundle mainBundle]` to `[NSBundle bundleForClass:[self class]]`.

Upon actually using the right path for `m.public_header_files = 'MapView/Map/Mapbox.h'`, it seems like it'd be easier to use `*.h` rather than `Mapbox.h`.

**Comment by jbardini** [comment]
It looks like only `[RMMapView pathForBundleResourceNamed:ofType:]` needs to use `[NSBundle bundleForClass]`, as the other places that use `[NSBundle mainBundle]` seem to intend to access the application bundle.

Everything seems to be working fine with either static lib and framework: 1184dad6a535b96509263ee07dc74dccd13fffbf

**Comment by incanus** [comment]
How do things look with the above two commits? I've been hacking a bit to get the SDK working in CocoaPods 0.36.3 with `use_frameworks!` and a Swift app and this appears to work well.

**Comment by jbardini** [comment]
I've been using it for a while and had no problems so far.

**Comment by incanus** [comment]
The [1.6.1 release](https://github.com/mapbox/mapbox-ios-sdk/blob/release/CHANGELOG.md#161) recently rolled these in and CocoaPods works well.
