### ISSUE TITLE
Turn on mapbox tiles in offline mode

### ISSUE THREAD

**Issue by bilby91** [mapbox/DEPRECATED-mapbox-ios-sdk#584]
I'm working on a fork that support caching for multiple tiles, caching all the active tiles of the map.

I have managed to cache the tiles in a db cache. 

While trying to start using the Mapbox cached tiles I realice that a request is performed in order to create the RMTileSource for the tile. 

Is there a way to bypass this ? Any suggestion ?

**Comment by incanus** [comment]
Yes, the first time, grab the `tileJSON` property and cache it for future use in instantiation.
