### ISSUE TITLE
Unsynchronized panning of RMShape

### ISSUE THREAD

**Issue by taylortrimble** [mapbox/DEPRECATED-mapbox-ios-sdk#586]
[This GIF](http://cl.ly/image/0M3U0V2E3F33) demonstrates the bug I'm seeing:
- I add an `RMAnnoation` to the map view
- I set the bounding box for that annotation
- I supply an `RMShape` for that annotation's layer
- I pan the map

Observed: the `RMShape` "scrolls faster than" my map does.

Any ideas?
#### Code

The custom classes here are trivial.

Here's how I add the annotations:

``` objc
    // Fetch service areas and add service area annotations.
    [TNTServiceArea fetch:^(NSArray *serviceAreas, TNTServiceError *error) {
        if (error) {
            NSLog(@"Error fetching service areas: %@", error);
            return;
        }

        for (TNTServiceArea *serviceArea in serviceAreas) {
            // Annotations can only have one coordinate, but its layer may be a polygon with many coordinates.
            // Create an annotation with the first coordinate and store the rest for rendering the poloygon later.
            TNTLocation *start = (TNTLocation *)serviceArea.coordinates[0];
            RMAnnotation *annotation = [[RMAnnotation alloc] initWithMapView:mapView coordinate:start.coordinate andTitle:nil];
            annotation.annotationType = TNTAnnotationTypeServiceArea;

            NSMutableArray *locations = [[NSMutableArray alloc] initWithCapacity:[serviceArea.coordinates count]];
            for (TNTLocation *point in serviceArea.coordinates) {
                [locations addObject:[[CLLocation alloc] initWithLatitude:point.coordinate.latitude
                                                                longitude:point.coordinate.longitude]];
            }

            [annotation setBoundingBoxFromLocations:locations];
            annotation.userInfo = locations;

            [mapView addAnnotation:annotation];
        }
    }];
```

and here's how I supply the layer:

``` objc
- (RMMapLayer *)mapView:(RMMapView *)mapView layerForAnnotation:(RMAnnotation *)annotation
{
    TNTConfig *config = [TNTConfig sharedInstance];

    if ([annotation.annotationType isEqualToString:TNTAnnotationTypeServiceArea]) {
        RMShape *shape = [[RMShape alloc] initWithView:mapView];
        shape.lineColor = [config majorBrandColor];
        shape.lineWidth = 5.0;
        shape.lineJoin = kCALineJoinRound;

        for (CLLocation *location in annotation.userInfo) {
            [shape addLineToCoordinate:location.coordinate];
        }

        return shape;
    }

    return nil;
}
```

**Comment by taylortrimble** [comment]
While this was certainly an interesting observation, this is my fault. Some of my annotation layers change their appearance when centered (within a radius) on the map; I was re-rendering layers for **every** annotation on **every** map move. Talk about a performance issue!

I'm now only re-rendering the layers I need to, and this issue is solved.

**Comment by maciekish** [comment]
How did you actually fix this? What was the code change?

**Comment by taylortrimble** [comment]
I had the following inside `mapViewRegionDidChange:`:

``` objc
for (RMAnnotation *annotation in mapView.visibleAnnotations) {
    if (!annotation.isUserLocationAnnotation)
        annotation.layer = [self mapView:mapView layerForAnnotation:annotation];
    }
}
```

I had originally added this so I could update the appearance of point annotations for certain zoom levels as the user zoomed in real time. However, my scope was too broad: I was reloading the layer of every annotation that wasn't the user location annotation. This included an `RMShape` annotation I was adding at a later time, which caused the reported issue.

I had gotten rid of the annotations that required the live feedback mechanism, so my entire solution was to remove those 5 lines of code from `mapViewRegionDidChange:`.

**Comment by maciekish** [comment]
I have a similar issue but it's probably not the same. Thanks anyway, maybe your explanation will at least help someone else :)

**Comment by taylortrimble** [comment]
You bet. Good luck!
