### ISSUE TITLE
Some Tiles are not shown in iPhone Simulator 6 and iphone 6s

### ISSUE THREAD

**Issue by arodriguezju** [mapbox/DEPRECATED-mapbox-ios-sdk#596]
Hi, 
I am testing an App with maps from Mapbox (iOS 8), and everything works fine, but in the iPhone 6 and iPhone 6s not all the tiles are shown.

![image](https://cloud.githubusercontent.com/assets/11327550/6500632/935a7fa8-c30e-11e4-9fb0-be530ca5b6ca.png)

Unfortunately I just have an iphone 4s, and it works great there and in the others simulators.

```
-(void)initMap{
_mapView = [[RMMapView alloc] initWithFrame:self.bounds];    
 _mapView.zoom=15;
_mapView.centerCoordinate=CLLocationCoordinate2DMake(41.503, -5.748);   
_mapView.delegate=self;
RMMapboxSource *tileSource = [[RMMapboxSource alloc] initWithMapID:@"trackid"];
 _mapView.tileSource=tileSource;
dispatch_async(dispatch_get_main_queue(), ^{
    if(_mapView.tileSource!=nil){
          [self addSubview:_mapView];
        _initialized=YES;
    }
 });
 }
```

Do you know if this is just an issue with the simulator? Thanks!

**Comment by arodriguezju** [comment]
I have tried with the latest version of Mapbox. Im using XCode 6.1 and the simulators iOS8.1....
I have tried setting the zoom and center with :
       [_mapView setZoom:15 atCoordinate:CLLocationCoordinate2DMake(41.503, -5.748) animated:NO];
But no luck...

Thanks for the help!

**Comment by incanus** [comment]
Hmm, very strange & never seen this before. Do you see the same effect @arodriguezju with the sample apps such as [`mapbox-ios-example`](https://github.com/mapbox/mapbox-ios-example)?

**Comment by arodriguezju** [comment]
The example works perfectly. The difference is that I am placing the map inside a UIView from the storyboard. It uses Autolayout. What I don´t understand is why just in iPhone 6 and 6s...

I will keep on trying things...I hope I´ll find something..

Thanks!

**Comment by arodriguezju** [comment]
So, i found the solution.
After checking every setting of my project I found out that the responsible of the error is.........:drums:
This key in the .plist file:
"Render With Edge Antialiasing"

Deleted and working perfectly.

Why it works in iPhone 5, 5s, 4s and not in 6 and 6s.... ? Some questions in life are not meant to be answered...

Thanks anyway ;). At least now I have the latest SDK Version.

**Comment by incanus** [comment]
> "Render With Edge Antialiasing"

I'm not even sure what this means... which `.plist` file is this? Is this a `route-me.plist` thing?

**Comment by arodriguezju** [comment]
In the info.plist file of the application. 

I used that key in the past because I had some problems resizing images. According to Apple:
"Specifies whether Core Animation layers use antialiasing when drawing does not align to pixel boundaries. See UIViewEdgeAntialiasing for details."
https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html

**Comment by incanus** [comment]
Fascinating! Hadn't seen this. I'm going to close here but good to know!
