### ISSUE TITLE
isAnnotationOnScreen

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#60]
If annotations are clustered, then isAnnotationOnScreen for the underlying annotations correctly returns NO.

If you zoom in far enough, that they become unclustered, then they correctly return YES.

However, if you then zoom back out so they are reclustered, those annotations still return YES for isAnnotationOnScreen. This should be set back to NO?

**Comment by trasch** [comment]
`isAnnotationOnScreen` really only checks if the annotation position is inside of the screen rect. You need to check for a valid layer to check if an annotation is on screen and not clustered.

**Comment by incanus** [comment]
Closing as resolved upstream.
