### ISSUE TITLE
Duplicate symbol on projects with FMDB

### ISSUE THREAD

**Issue by starock** [mapbox/DEPRECATED-mapbox-ios-sdk#607]
In my app, I was using FMDB(version 2.5) till now. I want to use the MapBox framework(1.6), which also uses FMDB. When I add this framework to my project, I get the error "40 duplicate symbols for architecture armv7".

I read through the error and noticed that all the symbols duplicated are in FMDB.

Please suggest how can I use both FMDB(independently in my app) along with MapBox(which uses FMDB internally).

**Comment by nejra** [comment]
I wonder how is this fixed if I link MapBox static lib to my project?
