### ISSUE TITLE
Update images for iOS examples

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/DEPRECATED-mapbox-ios-sdk#608]
The images on the iOS examples say "MapBox" in the bottom left corner! Let's update them so they say Mapbox (at least).

![screen shot 2015-03-18 at 7 29 39 pm](https://cloud.githubusercontent.com/assets/2523165/6723447/33d279a4-cda5-11e4-80f2-bae1d0e991de.png)
![screen shot 2015-03-18 at 7 29 46 pm](https://cloud.githubusercontent.com/assets/2523165/6723448/33d28bc4-cda5-11e4-98b8-409bf330b4bb.png)
![screen shot 2015-03-18 at 7 29 53 pm](https://cloud.githubusercontent.com/assets/2523165/6723446/33d265ae-cda5-11e4-972c-faeef601465a.png)

/cc @incanus @tatsvc

**Comment by tatsvc** [comment]
Thanks for flagging this @lyzidiamond!

We should probably also change the frames we are using here to the ones we use on all the other pages on the website.

**Comment by incanus** [comment]
Cool, this would be great. What's more, we should update the actual examples. Also we need them for https://www.mapbox.com/mbxmapkit/. But we can do it in stages.

**Comment by tatsvc** [comment]
@incanus Do you want to voice about this today, or do you not need my help with anything?
I'll make sure there's also a light colored iframe in css like this one:

![screen shot 2015-03-19 at 8 42 19 am](https://cloud.githubusercontent.com/assets/2894119/6730530/e3eb71e2-ce13-11e4-9675-c0c1daf9f53e.png)

**Comment by lyzidiamond** [comment]
@incanus yes, also let me know if/how I can help.

**Comment by incanus** [comment]
So I'm a little tight for bandwidth right now, but if you really wanted to run with it @lyzidiamond you could check out the new guide series to get going with iOS: 

https://www.mapbox.com/guides/mobile/

Piggyback that with playing with the examples a bit could net you some ideas for clarifications / other/new ideas. 

But that's kind of a big lift; completely understand if you don't want to grab it. Scaling iOS dev experience (especially for folks with fresh :eyes:) is part of the broader goal, though. 

Like, for example, just to update these screenshots would need someone to build an app housing to paste them into (they are not whole apps, but just core "view" logic). That expertise is limited to myself, @bleege, @1ec5, and (now!) @katydecorah and maybe a couple others if pressed.

**Comment by katydecorah** [comment]
@lyzidiamond @incanus I can update the screenshots 

..I really just want to show off my new iOS skills :wink:

**Comment by tatsvc** [comment]
I would love to jump on this as well / help out. I have [a little bit of iOS experience](http://tatiana.be/project/oclock/) but I would love to dive more into this.

**Comment by incanus** [comment]
Dev program invite sent to @tatsvc. FWIW that's only needed to run on a device; you can always run in a sim with a free account.

**Comment by lyzidiamond** [comment]
I would love @tatsvc and @katydecorah to run with this!

**Comment by bleege** [comment]
Great job on the new examples and code!  Let me know when there's interest in acquiring some Android skills!  :-)

**Comment by tatsvc** [comment]
:grimacing: babysteps @bleege

**Comment by incanus** [comment]
>  Let me know when there's interest in acquiring some Android skills

![you-tried-gold-star](https://cloud.githubusercontent.com/assets/17722/6827775/c3ae8b00-d2c6-11e4-906a-6891f31ac8e9.png)
