### ISSUE TITLE
Determining user or program-initated interaction

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#61]
I'm trying to determine if delegate methods like afterMapMove and afterMapZoom are being called because the program has requested a move, or if the user has interacted with the map.

I'm basically trying to cancel a secondary tracking mechanism if the user touches the map, but leave it activated when this mechanism itself moves the map.

RMMapView cancels the primary tracking by doing things like checking scrollView.pinchGestureRecognizer.state in scrollViewDidZoom, etc. But the afterMapZoom delegate is called in both cases.

Also afterMapMove is called from various places (after user dragging, after any map move, etc.)

Setting an ignore-delegate-callbacks flag in my parent ViewController isn't possible either, as the delegates get called a different number of times and later in the thread, making it impossible to know when to unset the flag.

Any ideas?

**Comment by incanus** [comment]
Maybe it would be useful to have an additional argument to these delegate callbacks, indicating whether they were user-driven or not (`BOOL`). I could see this being useful for: 
- `beforeMapMove:`
- `afterMapMove:`
- `beforeMapZoom:`
- `afterMapZoom:`
- `mapViewRegionDidChange:`

**Comment by russellquinn** [comment]
Yes, that sounds very useful.

**Comment by incanus** [comment]
@russellquinn, have a look at the `develop-61` branch for some renamed/updated delegate methods related to this. I think this does what you need. If this looks good, I'll propose a pull to upstream.

**Comment by incanus** [comment]
In the case of something like the two-finger single-tap to zoom out, you will want to also pay attention to that delegate callback, as technically, the zoom out comes after that gesture, not during it.

**Comment by russellquinn** [comment]
Yes, this seems useful.

**Comment by incanus** [comment]
And working ok? I know there are some issues with `afterMapZoom:` (see #70) but I will address those separately.

**Comment by russellquinn** [comment]
Yes, it seemed to in a quick test.

**Comment by incanus** [comment]
Ok, I'm going to put it into `develop` then.

**Comment by incanus** [comment]
Closing since in main branch of development.
