### ISSUE TITLE
Cocoapods + Swift & bridging header issue

### ISSUE THREAD

**Issue by frederik-jacques** [mapbox/DEPRECATED-mapbox-ios-sdk#616]
Hi all,

I've tried to implement Mapbox SDK with Cocoapods version 0.36

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.1'
pod 'IJReachability', :git => 'https://github.com/Isuru-Nanayakkara/IJReachability.git'
pod 'Mapbox-iOS-SDK', '~> 1.6.0'
```

But when I add the Mapbox header file to the bridging header file (which you need to use Objc code in Swift files), I get `#import "Mapbox-iOS-SDK/Mapbox.h" file not found`

It looks like all paths are set correctly (framework search paths, etc.)

**Comment by friedbunny** [comment]
With the new Cocoapods try doing something like this instead:

``` objc
#import <Mapbox_iOS_SDK/Mapbox.h>
```

Dashes are considered illegal characters and get converted to underscores by Cocoapods as part of their dynamic framework support. Check out #580 for the status of 0.36 support.

**Comment by frederik-jacques** [comment]
Thnx! Fixed it :)

**Comment by pgherveou** [comment]
Hey @frederik-jacques, is this trick still working? I can't make it work
I have created a test Project here
 https://github.com/pgherveou/TestMapBox/blob/master/Podfile

it does not matter wether I use dash or underscore I still get the file not found error
