### ISSUE TITLE
Annotations can have sub-pixel positioning, leading to blurry rendering

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#62]
It seems like they are always initially shown correctly, but after scrolling they can fall on sub-pixel positions. It's only really visible on non-Retinal Display divices.

Screenshot 1:
https://dl.dropbox.com/u/44154592/Screen%20Shot%202012-07-06%20at%2013.11.33.png

Screenshot 2:
https://dl.dropbox.com/u/44154592/Screen%20Shot%202012-07-06%20at%2013.12.48.png

**Comment by incanus** [comment]
Closing this as a dupe in favor of the upstream alpstein/route-me#103.
