### ISSUE TITLE
add animated marker example

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#622]
Per chat, a useful [example](https://www.mapbox.com/mapbox-ios-sdk/examples/) would be an animated annotation layer. 

Example in how the user location dot is done: https://github.com/mapbox/mapbox-ios-sdk/blob/2ca520dd960b8c0f8ed88279826b4057cf4f4147/MapView/Map/RMMapView.m#L3623-L3666

Basic animation steps: https://github.com/mapbox/mapbox-ios-sdk/blob/2ca520dd960b8c0f8ed88279826b4057cf4f4147/MapView/Map/RMMapView.m#L3646-L3654

Static marker: https://www.mapbox.com/mapbox-ios-sdk/examples/marker-custom-image

In order of increasing complexity, this could be: 
- A `transform`-based `CABasicAnimation` like the user dot layers. 
- A two-frame toggling animation that switches the layer's `contents`. 
- A multi-frame animation via `CAKeyframeAnimation`. 

/cc @geografa @tatsvc

**Comment by tatsvc** [comment]
Got the basic animation working!

![simple-cabasicanimation](https://cloud.githubusercontent.com/assets/2894119/7394625/b488d4ac-ee62-11e4-941a-37c923866afa.gif)

Will work on a `CAKeyframeAnimation` now!

**Comment by incanus** [comment]
So cool!

**Comment by tatsvc** [comment]
I'm SO excited :tada:  `CAKeyframeAnimation`

![cakeyframeanimation](https://cloud.githubusercontent.com/assets/2894119/7395177/4b10b27a-ee66-11e4-9632-93cc097f7715.gif)

**Comment by friedbunny** [comment]
This is going to make an awesome tutorial. :100:

**Comment by BramsOffChain** [comment]
Awesome!
Speaking of animations, what about animations when moving marker between different lat/lng on the map? Is it possible to get a smooth displacement of the marker?

**Comment by incanus** [comment]
> Speaking of animations, what about animations when moving marker between different lat/lng on the map? Is it possible to get a smooth displacement of the marker?

Yes, take a look at how drag and drop of markers is implemented in the SDK. Essentially: 
- Copy the marker's contents to an animatable duplicate layer
- Hide the marker layer
- Update animated layer's `position`, optionally with animation. 
- When complete, hide the animator, show the marker, and update its `coordinate` so the value sticks

**Comment by BramsOffChain** [comment]
Thanks for the quick reply

Basically for now I'm moving the marker thanks to the setCoordinates method, can you provide a quick example for creating an animatable duplicate layer and update layer position?
Also, do I have to provide the x/y position by converting the lat/lng one to update the layer position?

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-ios-sdk/blob/edbe9905299ddbf8b32e41d8978b7b3265eef8f8/MapView/Map/RMMapView.m#L1796-L1857 is the best we have right now; sorry, no direct tutorials for this use case right now.

**Comment by tatsvc** [comment]
This is live
