### ISSUE TITLE
still cannot draw RMPolyline under the user blue dot

### ISSUE THREAD

**Issue by andreinechaev** [mapbox/DEPRECATED-mapbox-ios-sdk#626]
![ios simulator screen shot may 4 2015 8 46 02 pm](https://cloud.githubusercontent.com/assets/3097332/7465470/9faf3036-f29e-11e4-8da5-2e267689e129.png)

I tried to attach zPositions to different types of annotations but without stable result. It seems that every time it redraws the map and all annotations on it. And somehow adjust default zPositions to layers. iOS8.0-8.3 MapBox 1.6.1

**Comment by andreinechaev** [comment]
I found a method, which should be overridden for sorting annotation layers. Closing the issue.

**Comment by incanus** [comment]
Yep, you want the delegate method: 

https://www.mapbox.com/mapbox-ios-sdk/api/Protocols/RMMapViewDelegate.html#//api/name/annotationSortingComparatorForMapView:
