### ISSUE TITLE
Could not build Objective-C module 'Mapbox_iOS_SDK'

### ISSUE THREAD

**Issue by mhergon** [mapbox/DEPRECATED-mapbox-ios-sdk#632]
Hi,

I'm getting this error, any help for this?
Project in Swift with Cocoapods

Podfile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

pod 'Mapbox-iOS-SDK'
pod 'RealmSwift'
```

And the error...
![captura de pantalla 2015-05-19 a las 13 27 46](https://cloud.githubusercontent.com/assets/621373/7701826/3329f836-fe2b-11e4-9519-935bc7889fa6.png)

I tried with a Bridge.h file but get the same error...

**UPDATE**

```
/Users/mhergon/Desktop/GeohashMapbox/GeohashMapbox/GeohashMapbox-Bridging-Header.h:5:9: note: while building module 'Mapbox_iOS_SDK' imported from /Users/mhergon/Desktop/GeohashMapbox/GeohashMapbox/GeohashMapbox-Bridging-Header.h:5:
#import <Mapbox_iOS_SDK/Mapbox.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/mhergon/Library/Developer/Xcode/DerivedData/GeohashMapbox-beaklgmanpobmmghfxmsmlccbprj/Build/Products/Debug-iphoneos/Pods/Mapbox_iOS_SDK.framework/Headers/Pods-Mapbox-iOS-SDK-umbrella.h"
        ^
/Users/mhergon/Library/Developer/Xcode/DerivedData/GeohashMapbox-beaklgmanpobmmghfxmsmlccbprj/Build/Products/Debug-iphoneos/Pods/Mapbox_iOS_SDK.framework/Headers/Pods-Mapbox-iOS-SDK-umbrella.h:3:9: note: in file included from /Users/mhergon/Library/Developer/Xcode/DerivedData/GeohashMapbox-beaklgmanpobmmghfxmsmlccbprj/Build/Products/Debug-iphoneos/Pods/Mapbox_iOS_SDK.framework/Headers/Pods-Mapbox-iOS-SDK-umbrella.h:3:
#import "Mapbox.h"
        ^
/Users/mhergon/Library/Developer/Xcode/DerivedData/GeohashMapbox-beaklgmanpobmmghfxmsmlccbprj/Build/Products/Debug-iphoneos/Pods/Mapbox_iOS_SDK.framework/Headers/Mapbox.h:31:9: note: in file included from /Users/mhergon/Library/Developer/Xcode/DerivedData/GeohashMapbox-beaklgmanpobmmghfxmsmlccbprj/Build/Products/Debug-iphoneos/Pods/Mapbox_iOS_SDK.framework/Headers/Mapbox.h:31:
#import "RMAnnotation.h"
        ^
/Users/mhergon/Library/Developer/Xcode/DerivedData/GeohashMapbox-beaklgmanpobmmghfxmsmlccbprj/Build/Products/Debug-iphoneos/Pods/Mapbox_iOS_SDK.framework/Headers/RMAnnotation.h:29:9: error: 'RMFoundation.h' file not found
#import "RMFoundation.h"
        ^
/Users/mhergon/Desktop/GeohashMapbox/GeohashMapbox/GeohashMapbox-Bridging-Header.h:5:9: error: could not build module 'Mapbox_iOS_SDK'
#import <Mapbox_iOS_SDK/Mapbox.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/mhergon/Desktop/GeohashMapbox/GeohashMapbox/GeohashMapbox-Bridging-Header.h'
```

Thanks!

**Comment by PSTDev** [comment]
All you have to do is create a file named &lt;YourProjectName&gt;-Bridging-Header.h and put there #import &lt;Mapbox.h&gt;

**Comment by mhergon** [comment]
PSTDev, I already tried, but does not work...

![captura de pantalla 2015-05-19 a las 16 11 36](https://cloud.githubusercontent.com/assets/621373/7704974/d863b68c-fe41-11e4-8fc5-aa88dcff62bb.png)

**Comment by PSTDev** [comment]
Try #import &lt;Mapbox.h&gt;, without Mapbox_iOS_SDK.

**Comment by mhergon** [comment]
@PSTDev with 

```
#import <Mapbox.h>
```

or

```
#import "Mapbox.h"
```

Error: 'Mapbox.h' file not found

**Comment by PSTDev** [comment]
Check if you have Mapbox.h in your Pods project in Workspace
![screen shot 2015-05-19 at 17 18 08](https://cloud.githubusercontent.com/assets/4547974/7705150/35e433fa-fe4b-11e4-9cc7-534c2db39dda.png)

**Comment by mhergon** [comment]
Yes, it's all right ...
<img src="https://cloud.githubusercontent.com/assets/621373/7705184/0294b3ce-fe43-11e4-8d44-779a48ea649b.png" width="300">

**Comment by mhergon** [comment]
Finally, it works!
I selected all .h from Mapbox-iOS-SDK folder on Pods and I made Public. After this, works fine!

But this procedure is correct?

![captura_de_pantalla_2015-05-19_a_las_16_29_43](https://cloud.githubusercontent.com/assets/621373/7705416/6797ec7c-fe44-11e4-8f72-d5dea99e9105.png)

**Comment by PSTDev** [comment]
I have Project target for all headers
![screen shot 2015-05-19 at 17 35 55](https://cloud.githubusercontent.com/assets/4547974/7705557/a1f1e82e-fe4d-11e4-8c12-cd562fca6224.png)

**Comment by mhergon** [comment]
It is a very strange issue...

**Comment by friedbunny** [comment]
This is the same basic issue as #631.
