### ISSUE TITLE
consider making Caches the default

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#65]
Currently local tile caches exist in `Documents` by default, but can be put in `Caches` using the `useCachesDirectory` directive in a `routeme.plist` file. Might want to make this the default behavior.

**Comment by incanus** [comment]
This does factor into client-side caching of tiles, though, in that `Caches` could get cleared out indiscriminately. Let's leave this as is for now.

**Comment by bentford** [comment]
I realize this is 2 years old, but we were recently rejected from the AppStore for storing map box tiles in the `Documents` directory.  Defaulting to the `Documents` directory may not be the best choice these days.

**Comment by incanus** [comment]
Yeah, addressing this over in https://github.com/mapbox/mapbox-ios-sdk/pull/410. Sorry about that @bentford. It seems to generally be ok right now, but depending on reviewer can cause a problem.
