### ISSUE TITLE
Converting a CGPoint to a CLLocation or CLLocationCoordinate2D (Question)

### ISSUE THREAD

**Issue by mitchellporter** [mapbox/DEPRECATED-mapbox-ios-sdk#671]
So based on how my app functions I need to be able to draw the polygon annotation using an array of `CGPoints`. This works fine by default in the 2.0 SDK, but in version 1.6 the polygon's initialization method wants an array of `CLLocation` objects.

So I need to convert my `CGPoints` to `CLLocation` objects or `CLLocationCoordinate2D's`

I found the following `StackOverflow` answer which allows you to do this using `MapKit`: http://stackoverflow.com/a/16230174/3344977

But it seems kind of foolish to use `MapKit` and initialize an `MKMapView` that no one will ever see just so I can utilize this one function, and now that I think about it there's no way to guarantee that the `MKMapView` would be in sync with the real `RMMapView` so this workaround would be unreliable anyways.

I've been looking through the mapbox legacy API docs and can't seem to find a similar function, so I'm hoping that one exists and I've simply made a mistake.

Is there any way to convert a `CGPoint` to a `CLLocation` or `CLLocationCoordinate2D` using the mapbox legacy iOS SDK?

Thanks.

**Comment by incanus** [comment]
Yep, check out [this example](https://www.mapbox.com/mapbox-ios-sdk-legacy/examples/converting-points/). You want API like `-[RMMapView pixelToCoordinate:]`.

**Comment by mitchellporter** [comment]
@incanus Thanks!
