### ISSUE TITLE
Method "selectAnnotation: animated:" doesn't work.

### ISSUE THREAD

**Issue by sw1mming** [mapbox/DEPRECATED-mapbox-ios-sdk#679]
I'm using pods to load Mapbox:
pod 'Mapbox-iOS-SDK', '~> 3.0'

And when I'm trying call method:
- (void)selectAnnotation:(id <MGLAnnotation>)annotation animated:(BOOL)animated;

it doesn't work.

Annotation is on screen and I pass actual annotation object to this method.

**Comment by 1ec5** [comment]
This is the repository for the former Mapbox iOS SDK that displays raster map tiles. The “Mapbox-iOS-SDK” pod installs a newer SDK that displays vector map tiles; please report bugs in that SDK in the [mapbox/mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native) repository.

Regarding the issue you’re seeing, you need to [implement `-mapView:annotationCanShowCallout:`](https://www.mapbox.com/help/first-steps-ios-sdk/#tapping) in your MGLMapViewDelegate to return `YES` in order for a callout to appear when the annotation is selected. The annotation also needs to have a title.
