### ISSUE TITLE
How to set my own annotation pin instead of default pin?

### ISSUE THREAD

**Issue by abhinesh01** [mapbox/DEPRECATED-mapbox-ios-sdk#681]
#679 #![screen shot 2016-02-05 at 3 18 00 pm](https://cloud.githubusercontent.com/assets/16958309/12842895/cc5bf1ee-cc1b-11e5-873c-a5d4d925c365.png)

 I tried to use imageForAnnotation delegate method. ios Mapbox 3.0.1 sdk

**Comment by 1ec5** [comment]
Hi, this repository is for versions of the Mapbox iOS SDK below 2.0 that displayed raster maps. You’re using the newer, vector-based Mapbox iOS SDK, which is located in the [mapbox/mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/ios) repository. Please open issues there.

**Comment by abhinesh01** [comment]
Hi, 
I have seen in same place that map box idk 1.6 is deprecated is it true? if true, Where do i get sdk 2.0 version?

Thanks.

**Comment by 1ec5** [comment]
Based on the screenshot above, you already have the newer version (3.0 is better than 2.0).

**Comment by abhinesh01** [comment]
i like the things user defined map style but i  wonder sdk 3.0 can be used for fetching location details through annotation marker and can marker be in air while dragging map, i dnt see any supporting delegate methods to implement for this type actions.

thanks.

**Comment by 1ec5** [comment]
> fetching location details through annotation marker

Answered in mapbox/mapbox-gl-native#3843.

> can marker be in air while dragging map

I’m not sure I understand what you’re asking. The SDK doesn’t currently allow you to drag a marker, but please open an issue in the mapbox/mapbox-gl-native repository about this so we can prioritize the work appropriately. If you’re asking about the reverse – dragging the map while keeping the annotation stationary – you’ll need to implement the marker as a UIView that’s positioned above the map.

Again, let’s continue the discussion at the mapbox/mapbox-gl-native repository, where the SDK you’re using is being developed.
