### ISSUE TITLE
afterMapZoom 

### ISSUE THREAD

**Issue by mccpower** [mapbox/DEPRECATED-mapbox-ios-sdk#70]
I think that is missing in this method a call to know when the zoom has finished like is applied with the scroll move
- (void)scrollViewDidEndZooming:(UIScrollView *)scrollView withView:(UIView *)view atScale:(float)scale
  {
  _mapScrollViewIsZooming = NO;
  
  [self correctPositionOfAllAnnotations];
  }

So I think that should be something like this:
- (void)scrollViewDidEndZooming:(UIScrollView *)scrollView withView:(UIView *)view atScale:(float)scale
  {
  _mapScrollViewIsZooming = NO;
  if (_delegateHasAfterMapZoom)
      [_delegate afterMapZoom:self];
  [self correctPositionOfAllAnnotations];
  }

**Comment by incanus** [comment]
This is being worked on over in #90. Closing here.
