### ISSUE TITLE
enhance GeoJSON support

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#71]
Per [this suppert issue](http://support.mapbox.com/discussions/mapbox-ios-sdk/119-geojson-support-for-mapbox-ios-sdk), it would be cool to handle GeoJSON like we do in the iPad app, which is to treat it as a first-class data type. For example, you could grab a GeoJSON file, pass it to the SDK, and have it turned into `RMShape` and `RMMarker` etc. automatically.

**Comment by incanus** [comment]
Flow here would be something like this: 

```
RMGeoJSONAnnotation = [[RMGeoJSONAnnotation alloc] initWithString:json]; 
```

Then add that to the map and your'e done, providing it's points or lines or whatever else we support in the class. Layer gets created automatically.

**Comment by incanus** [comment]
We more of less do this already with [simplestyle](http://mapbox.com/developers/simplestyle/) already in things like `-[RMMapBoxSource initWithMapID:enablingDataOnMapView:]`. No use duplicating effort when we have a standard for this.

**Comment by incanus** [comment]
Reopening as we could benefit from taking a look at this again.

**Comment by gongpengjun** [comment]
I love the idea. Please add geojson file support as soon as possible.

**Comment by incanus** [comment]
Related: https://github.com/mapbox/mapbox-ios-sdk/issues/365

**Comment by mohpor** [comment]
I have used GeoJSON to display markers and even roads on MapBox iOS SDK, let me know how can I share the experience.

**Comment by incanus** [comment]
To clarify, this can be done now per this: https://www.mapbox.com/mapbox-ios-sdk/examples/drawing-geojson-shape/

This ticket is to automate and simplify some of those interactions.

**Comment by incanus** [comment]
Let's stick with this done server-side in simplestyle when it comes to auto-translation of GeoJSON styling into local features. This leans on #419.
