### ISSUE TITLE
RMPath flicker while the map is being scrolled

### ISSUE THREAD

**Issue by mouse4d** [mapbox/DEPRECATED-mapbox-ios-sdk#73]
while scrolling the map the RMPath overlay is scrolled also, but sometimes it is drawn with an offset (a location where it was just a moment ago) for just a fraction of a second, after that it gets to it's normal place , and this creates a sensation of flickering.

**Comment by incanus** [comment]
Please check out `RMShape`, as it addresses this. `RMPath` use is deprecated.
