### ISSUE TITLE
Deprecated warning

### ISSUE THREAD

**Issue by romaonthego** [mapbox/DEPRECATED-mapbox-ios-sdk#74]
RMMapBoxSource.m generates deprecated warning in Xcode 4.4 on line 153
return [self initWithInfo:mutableInfoDictionary];

I like to keep my projects warnings-free, is there a workaround?

**Comment by incanus** [comment]
Yeah, I will be getting to this. A workaround would be just to just comment out the calling method. It's only used in our own legacy code, hence the deprecation.
