### ISSUE TITLE
Another heading-tracking-mode rotation glitch

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#76]
Rotating from portrait to landscape (or vice versa) when in heading-tracking mode, can cause the map to zoom out significantly (city-level say), which is weird anyway, but also all the markers are "dancing" around their rotation access, independently of each other, or where they should be pointing.

**Comment by incanus** [comment]
I see the zoom issue, which I'll work on, and above I've fixed the rotation issue. It was previously the case that out-of-sight (i.e. `layer`-less) annotations did not get the rotation applied until the next heading update after they were made visible. Now they always get drawn with any appropriate rotation applied.

**Comment by incanus** [comment]
Ok, have a look here. I fixed a number of things related to device rotation, centering/zooming on location updates, and I think the annotation rotation issue was resolved above.

**Comment by incanus** [comment]
Pretty sure this one is set now.
