### ISSUE TITLE
Heading-tracking rotation again.

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#77]
When rotating the map in compass mode, you can't tap any annotations. If this is the expected behavior then it should probably cancel tracking (as it does when you scroll) because it seems like tapping just doesn't work to the user. Additionally, tapping randomly over the screen one time, resulted in one marker becoming stretched, so maybe tapping is still enabled, but the coordintate system is screwed?

See image: https://dl.dropbox.com/u/44154592/Screen%20Shot%202012-07-26%20at%2014.34.51.png

**Comment by incanus** [comment]
This is related somehow the transform being applied to annotations when the map is rotated. They don't hit test in the same place -- eventually you can find a spot where no annotation is seen, but is able to be tapped and activates some annotation. Working on it.

**Comment by incanus** [comment]
I think this is fixed. Let me know if you see otherwise and/or any side effects, but I think I got it.

**Comment by russellquinn** [comment]
Heading-tracking actually seems completely broken to me with the latest pull from develop. It initially orientates, but then doesn't react when I turn the device.

**Comment by incanus** [comment]
Check again here; fixes sent up.

**Comment by incanus** [comment]
Pretty sure this has been resolved last week.

**Comment by russellquinn** [comment]
Yep! Seems to be fixed.
