### ISSUE TITLE
Interaction disabled after rotating device in heading-tracking mode

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#79]
This seems to have started recently, but after entering, rotating, then leaving compass-tracking mode, user interaction with the map becomes erratic (sometimes it accepts nothing, sometimes only swipes in one direction, sometimes no tapping)

**Comment by incanus** [comment]
Let me know if you're still seeing this. Bunch of fixes here.

**Comment by russellquinn** [comment]
Yep, I just emailed you a video.

**Comment by incanus** [comment]
Got it. Closing in favor of #55, which also tracks this.

**Comment by incanus** [comment]
Reopening to track separately.

**Comment by russellquinn** [comment]
Right, yep, to confirm this one isn't fixed.

**Comment by incanus** [comment]
I've not always had good luck reproducing this one, either, so please give it a try with the latest changes, in case maybe it was related to bad user location data (#59) and/or user location annotation intercepts (#92).

**Comment by russellquinn** [comment]
I'll keep an eye on this.

**Comment by incanus** [comment]
Going to close in the meantime. Feel free to reopen if it appears again.
