### ISSUE TITLE
Tracking can still be enabled where there is no tile source

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#80]
The MapView no longer crashes, but user location can still be toggled on and off, this causes the location dot to appear, then vanish and spurious updated-location events are triggered, even though in my test case I was in airplane mode.

**Comment by incanus** [comment]
Unlike Maps.app, I don't think a `UIAlert` should be shown, but the `mapView:didFailToLocateUserWithError:` callback should trigger, I think. And I agree the dot should not show. I've updated `RMMapView` to do this.

**Comment by russellquinn** [comment]
Agreed.
