### ISSUE TITLE
Cache not used if tile source is invalid on launch

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#81]
If the online source is null, then the map view no longer crashes, but it doesn't use the provided cache

For example, if you launch the app _with_ a data connection, then lose it, the map view will continue serving from the local cache, but if you launch without a data connection (so that RMMapBoxSource can't be created) then the cache is ignored

**Comment by incanus** [comment]
Ah, good catch. But if the TileJSON for the `RMMapBoxSource` can't be fetched, nothing is known about the tile source. Thus, either a local TileJSON should be applied, or a a network test should be performed and a fallback source provided (or error dialog).

**Comment by russellquinn** [comment]
Okay. Though it seems that, ideally, there should be some way of auto-using the existing cache if it exists for the URL that can no longer be reached?

**Comment by incanus** [comment]
Yeah, agree. I will look into a cache. See #82.
