### ISSUE TITLE
add bulk downloader

### ISSUE THREAD

**Issue by incanus** [mapbox/DEPRECATED-mapbox-ios-sdk#83]
We should build an API for bulk download of a given bounding box & zoom range. Enough people are doing this anyway due to [our caching policy](http://mapbox.com/blog/ios-sdk-caching/).

**Comment by futureshape** [comment]
Here's some really **quick & dirty** code that I cobbled together so far for Cycle Hire App (based on an example I in a route-me discussion thread long time ago). 

Obviously this replicates some of the x/y/zoom calculations that are already part of the library, so these should be replaced.

Since this will probably be a long running process, a bulk downloader API should include the capability to report back some kind of progress, and allow the process to be cancelled.

```
    const int MINZOOM = 13;
    const int MAXZOOM = 17;

    // TODO: calculate these from list of cycle hire locations
    const float MINLAT = 51.483145;  //minimum and max lattitude in degrees
    const float MAXLAT = 51.542138;  
    const float MINLONG = -0.2242237;  //min and max longitutde in degrees 
    const float MAXLONG = -0.002275;

    for (int zoom = MINZOOM; zoom <= MAXZOOM; zoom++){
        [hud setLabelText:[NSString stringWithFormat:@"Downloading zoom level %d", zoom]];
        int n = pow(2.0, zoom);   //n=2^ZOOM
        int xMin = floor(((MINLONG + 180.0) / 360.0) * n);  //longitude in degrees
        int yMax = floor((1.0 - (logf(tanf(MINLAT * M_PI / 180.0) + 1.0 / cosf(MINLAT * M_PI / 180.0)) / M_PI)) / 2.0 * n);  //latitude in degrees 
        int xMax = floor(((MAXLONG + 180.0) / 360.0) * n);  //longitude in degrees
        int yMin = floor((1.0 - (logf(tanf(MAXLAT * M_PI / 180.0) + 1.0 / cosf(MAXLAT * M_PI / 180.0)) / M_PI)) / 2.0 * n);
        NSLog(@"n=%d, xMin=%d, xMax=%d, yMin=%d, yMax=%d",n,xMin,xMax,yMin,yMax);
        int totalTiles = (xMax + 1 - xMin) * (yMax + 1 - yMin);
        NSLog(@"Total tiles for this zoom level: %d", totalTiles);
        for (int x = xMin; x<=xMax; x++){
            // TODO: Create & drain autorelease pool for each iteration of the outer loop (we don't use the returned UIImages)
            for (int y = yMin; y <= yMax; y++){
                int currentTiles = (x - xMin) * (yMax + 1 - yMin) + (y - yMin + 1);
                NSLog(@"Downloading zoom=%d,x=%d,y=%d (%d/%d)", zoom, x, y, currentTiles, totalTiles);
                hud.progress = ((float) currentTiles) / totalTiles;
                UIImage *tileImage = [mapView.tileSource imageForTile:RMTileMake(x, y, zoom) inCache:[mapView tileCache]];
            }
        } 
    } 
```

**Comment by incanus** [comment]
Nice, thanks. Yeah, I'm hoping to make use of the tile calculation stuff that's already in there. And I agree, I'm thinking an `NSOperationQueue` or something like that.

**Comment by incanus** [comment]
Possibly consider use of http://blog.mugunthkumar.com/products/ios-framework-introducing-mknetworkkit/

**Comment by coder90** [comment]
Hi. So when do you plan to implement that bulk download api ? I'm writing an app which needs map data preloaded later to be used offline.

**Comment by incanus** [comment]
I will be working on that soon, as I have just returned from a vacation. It's a major push for the next release.

**Comment by incanus** [comment]
Work on this is happening in the [downloader](https://github.com/mapbox/mapbox-ios-sdk/tree/downloader) branch. Current status: 
- `RMTileCache` now has a `backgroundCacheDelegate` which can be notified of progress. 
- Background downloading can now be fully cancelled. 
- Initial delegate notification indicates how many tiles will need to be downloaded, regardless of which ones already may have been. 
- Capable of being run without a UI (e.g., map view). 

I did use some of @futureshape's code above for tile determination. 

I'd love some feedback on how this works for people. Still working on a UI element.

**Comment by incanus** [comment]
I should also point out that the simplest incarnation of this for a given `RMTileCache` is `- (void)beginBackgroundCacheForTileSource:(id <RMTileSource>)tileSource southWest:(CLLocationCoordinate2D)southWest northEast:(CLLocationCoordinate2D)northEast minZoom:(float)minZoom maxZoom:(float)maxZoom;`

**Comment by coder90** [comment]
This thing maybe cool. I'll try it soon if I found free time, just will replace my own implementation.

**Comment by chrismccall-org** [comment]
I'd love to give this a try, it takes care of a very important requirement. I'm new to CocoaPods... is there any way to install this branch via CocoaPods?

**Comment by incanus** [comment]
@chrismccall-org, I think you are looking for something like this: 

https://github.com/CocoaPods/CocoaPods/wiki/Changing-your-local-cocoapods-for-new-versions

**Comment by chrismccall-org** [comment]
That's exactly what I'm looking for. Mapbox is a great use case for cocoapods, thanks a million!

**Comment by incanus** [comment]
No UI element for this in the short term.

**Comment by incanus** [comment]
This is now merged into `develop` and the `downloader` branch is no more.
