### ISSUE TITLE
Text blurriness

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#87]
I'm having an issue with getting my UILabels inside labels RMMarkers on pixel boundaries. Currently they're always blurry on non-Retina Displays:

https://dl.dropbox.com/u/44154592/Screen%20Shot%202012-08-07%20at%2012.52.18.png

When a user taps a marker, I create a new UIView, which contains UILabels amongst other things, then set the .label property of the RMMarker. Everything is CGRectIntegral'ed, but I'm getting the RMMarker itself isn't?

Any ideas?

**Comment by incanus** [comment]
Quick question here: have you considered an approach as mentioned in #23, where you overlay a `UIView` above the map when a marker is tapped, then when the map is tapped again or moved, the view is dismissed? This works at a different level than the `RMMarker` directly. 

Anyway, nothing comes to mind here yet, but I thought I'd throw that out.

**Comment by russellquinn** [comment]
It needs to scroll with the map after shown :(

**Comment by incanus** [comment]
Yeah, you could still move it using the delegate, but it might just be a workaround. Will see if I can look at this soon.

**Comment by incanus** [comment]
Possibly related, just noting for future research -- per a [support issue](http://support.mapbox.com/discussions/mapbox-ios-sdk/152-syncing-map-view-with-another-layer) it seems that `UIScrollView` can operate on sub-pixel boundaries: 

> I think it's due to the fact that the scroll view internally will allow you to scroll by amounts that aren't full pixels but it causes off by one errors when mapping back to pixel positions.

**Comment by incanus** [comment]
Not sure I understood your related comment [over here](https://github.com/mapbox/mapbox-ios-sdk/issues/31#issuecomment-7774023) about this -- is this still an issue?

**Comment by russellquinn** [comment]
Sorry, I meant that if we drew clustered markers above regular markers, then there could be the possibility of a label being shown under a clustered marker. (This won't ever happen if everything is always in latitude order, and we don't prioritise clusters.)

So, I was just thinking that if the text-blurriness problem is because the .label is attached to the same CALayer as the annotation pin, and that a solution might be to implement a new callout/label system by showing one at a time always at the very top zPosition (so we can correctly snap to pixels to avoid blur) then this would also fix the labels-behind-clusters problem.

And, yes, text blurriness is still an issue.

**Comment by incanus** [comment]
I'm not sure I'm seeing things being any blurrier than anything else on retina devices. Is there a specific point you could highlight to show me what you mean? 

I did check around on some code, as well as add my own labels to a test app, but things look ok to me.

**Comment by russellquinn** [comment]
The blurriness is often subtle, but definitely there. I just did some poking around and the annotations definitely aren't aligned to pixels.

If I log the position CGPoints of the RMMarker layers right before I set a .label then they're all fractions:

555.557434, 423.187012
585.611450, 435.866058
606.143066, 413.090424
526.336487, 384.518890

So, I tried snapping them to pixel boundaries when you click them:

self.position = CGPointMake(round(self.position.x), round(self.position.y));

...and the whole annotation (regular pin graphic too) gets noticeably sharper when you click.

**Comment by incanus** [comment]
Ah, that helps. I will work on trying that internally.

**Comment by incanus** [comment]
Re: the comment above about callouts and label ordering, yeah, it's on the radar at #23, where I will probably use a map view subview to ensure that it's above markers and other annotation layers. That will likely go into 0.5.0.

**Comment by incanus** [comment]
Since there is some complexity to where exactly to put this in the SDK, is this a workable solution for you for now? I've opened a ticket upstream to discuss where to best handle this internally, since it sounds like it needs to happen during gestural interaction.

**Comment by russellquinn** [comment]
Well, the problem comes back when you move the map with the label open, and it'd be nice to have all pin icons rendering sharply all the time.

Having said that, snapping to the pixel boundary on a display-label tap is a probably a workable solution for now. Stopping that text being blurry when the label shows will fix the most obvious/common annoyance. So, definitely lower the priority on this if it's a chunk of work.

**Comment by incanus** [comment]
Well, mostly I'm unsure where to best do this, which is why I opened the upstream case for some input. I'm guessing eventually it might go in `correctPositionOfAllAnnotations`.

**Comment by russellquinn** [comment]
Right. One resulting issue might be that general marker animations/scrolls become jerkier, because they're all snapping to pixel boundaries. But, on the other hand, aligning text and sprites to pixel boundaries is a very real display issue to make sure they render correctly/sharply. But, yeah, i think it's going to be more complex than just rounding in correctPositionOfAllAnnotations. I'll just force snap when the label is shown for now. That'll fix our most common use case.

**Comment by incanus** [comment]
Yeah, might make sense to just do it on did end dragging / did end deceleration / did change center.

**Comment by russellquinn** [comment]
That sounds like the right direction.

**Comment by incanus** [comment]
Back on this again. I think doing it in the correction routine will not be jerky due to https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMMapView.m#L1383 I'm addressing this because it also shows up with #23 callouts since they are sublayers of annotation markers.

**Comment by incanus** [comment]
Closing this as a dupe in favor of the upstream alpstein/route-me#103.
