### ISSUE TITLE
Location dot blocks annotation taps

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#92]
If the dot is directly on an annotation, often it's in front and the annotation can't be tapped. Also, if the confidence circle is huge, then nothing underneath it can be selected.

**Comment by incanus** [comment]
Please also confirm #92 is not again an issue for you with this; isn't for me.

**Comment by russellquinn** [comment]
It seems like the location dot is always under the annotations now. Yes, seems fixed.
