### ISSUE TITLE
Continuous pan across date line

### ISSUE THREAD

**Issue by artisanglobal** [mapbox/DEPRECATED-mapbox-ios-sdk#96]
Any plans to add continuous pan across the date line? Thanks.

**Comment by incanus** [comment]
This was discussed in the upstream project at alpstein/route-me#45, but no real movement on it. It may be possible with something like abutting multiple content views together. 

I'll try to have a look at this in the future, so I'll leave this ticket open as well. In the meantime, you could try out the branch mentioned in the above ticket.

**Comment by afarnham** [comment]
I have done thinking about this in the past and one option I considered was something like the "infinite" scrollView as demonstrated by Eliza Block in one of the WWDC 2011 videos (forget which video precisely). 

This is example from Apple is based on the demo code from that video:

https://developer.apple.com/library/ios/#samplecode/StreetScroller/Listings/StreetScroller_InfiniteScrollView_m.html#//apple_ref/doc/uid/DTS40011102-StreetScroller_InfiniteScrollView_m-DontLinkElementID_5

The general idea is to create a scroll view wider than the screen and continually recenter it when you have scroll some distance from the center of the scroll view, but not to the point that an edge has been moved into view. 

To implement this you would have to divorce the scroll view contentOffset, bounds and contentSize from the code that calculates screen position coordinate conversions and instead keep the current visible map view state in it's own model (see RMMapView centerProjectedPoint and setCenterProjectedPoint for example).

**Comment by incanus** [comment]
I've just recently implemented an infinite scroll view for the [RMLoadingTileView](https://github.com/mapbox/mapbox-ios-sdk/blob/release/MapView/Map/RMLoadingTileView.m), which is a background behind the map tiles that moves with the map and scrolls everywhere it does, but does not use `CATiledLayer` so that its own image loads are never seen. This provides a gridded background much like MapKit. It's pretty smooth, so this strategy is a good one (in case you needed another vote beyond Apple's). 

I wonder if we could just do a simpler infinite scroll this way. However, it wouldn't work when the full world was visible because the illusion wouldn't be convincing/possible. But when zoomed in, it might be.

**Comment by incanus** [comment]
Assigned to [Tender discussion #261](http://support.mapbox.com/discussions/mapbox-ios-sdk/261-ios6-maps-are-driving-me-crazy).

**Comment by followben** [comment]
Hi Justin. Great work with MapBox iOS SDK - would very much like to use it on a (very large) client project. Unfortunately wrapping across the date line is one of our requirements. Is this issue likely to be resolved anytime soon?

**Comment by incanus** [comment]
This is not an area I've been working on of late. It's just not as high on the priority list. Sorry about that.

**Comment by RowanWillson** [comment]
Any chance of a bump for this issue; I had a look at the endless-scrolling branch but couldn't see how it worked easily...

**Comment by incanus** [comment]
This continues to be lower priority. You will probably want to look into iOS 7 to see where this should be headed...

**Comment by incanus** [comment]
To be more clear, http://github.com/mapbox/mbxmapkit, which is based on Apple's MapKit in iOS 7+, is a good way to get cross-date line functionality in the near term.

**Comment by incanus** [comment]
Recommended approaches here are either [MBXMapKit](http://mapbox.com/mbxmapkit) or [Mapbox GL](http://mapbox.com/mapbox-gl).
