### ISSUE TITLE
Disabling Location Services crashes MapBox

### ISSUE THREAD

**Issue by russellquinn** [mapbox/DEPRECATED-mapbox-ios-sdk#98]
You can recreate this in the sample app I've already provided.
1. Run the app with Location Services enabled
2. Multitask to Settings app, disable Location Services
3. Switch back to app, it's correctly disabled location
4. Back to Settings and reenable
5. Switch back to app and it crashes here:
   
   if ([newLocation distanceFromLocation:oldLocation])
       _accuracyCircleAnnotation.coordinate = newLocation.coordinate;

in RMMapView.h

**Comment by russellquinn** [comment]
(_accuracyCircleAnnotation has been deallocated)

**Comment by incanus** [comment]
I think this was a temporary glitch due to in-progress work on #31. Are you still seeing this?

**Comment by russellquinn** [comment]
Yep, this is still broken with the latest in develop.

Get the latest of our app and go through the steps above. It crashes hard every time.

**Comment by russellquinn** [comment]
Thanks, this seems fixed now. It actually had bigger implications, because you couldn't stop Location Services when the app went into the background and then restart them again when relaunched, but all good now.

**Comment by russellquinn** [comment]
I take that back, it's still broken with the same issue in a different place, but now it throws an exception as soon as you touch the map, rather than immediately.

This line:

 BOOL flag = _userLocationAnnotation.layer.isHidden;

In:
- (CALayer *)overlayHitTest:(CGPoint)point

In:

RMMapOverlayView.m

With exception:

**\* -[RMUserLocation layer]: message sent to deallocated instance

**Comment by incanus** [comment]
Ack, I was seeing that in testing for a while but it went away. I have an idea about it...
